In [ ]:
import pandas as pd
import mysql.connector

con = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    password = '4774',
    database = 'classicmodels'
)

cursor = con.cursor()
cursor.execute('SHOW TABLES')
nomTau = [row[0] for row in cursor.fetchall()]

dataBase = {}

for taul in nomTau:
    cursor.execute(f'select * from {taul}')
    dades = cursor.fetchall()
    colu = cursor.column_names
    df = pd.DataFrame(dades,columns=colu)
    dataBase[taul] = df

In [2]:
dataBase['customers']

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,France,1370.0,21000.00
1,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,None,Las Vegas,NV,83030,USA,1166.0,71800.00
2,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611.0,117300.00
3,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",None,Nantes,None,44000,France,1370.0,118200.00
4,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,None,Stavern,None,4110,Norway,1504.0,81700.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,486,Motor Mint Distributors Inc.,Salazar,Rosa,2155559857,11328 Douglas Av.,None,Philadelphia,PA,71270,USA,1323.0,72600.00
118,487,Signal Collectibles Ltd.,Taylor,Sue,4155554312,2793 Furth Circle,None,Brisbane,CA,94217,USA,1165.0,60300.00
119,489,"Double Decker Gift Stores, Ltd",Smith,Thomas,(171) 555-7555,120 Hanover Sq.,None,London,None,WA1 1DP,UK,1501.0,43300.00
120,495,Diecast Collectables,Franco,Valarie,6175552555,6251 Ingle Ln.,None,Boston,MA,51003,USA,1188.0,85100.00
121,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,New Zealand,1612.0,110000.00

In [ ]:
import pandas as pd
import mysql.connector

conx = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    password = '4774',
    database = 'classicmodels'
)

cursor = conx.cursor()
cursor.execute('SHOW TABLES')
nomTaulas = [row[0] for row in cursor.fetchall()]


baseDatos = {}

for taau in nomTaulas:
    cursor.execute(f'select * from {taau}')
    lineas = cursor.fetchall()
    col = cursor.column_names
    df = pd.DataFrame(lineas,columns=col)
    baseDatos[taau] = df

In [10]:
baseDatos['orderdetails']

      orderNumber productCode  quantityOrdered priceEach  orderLineNumber
0           10100    S18_1749               30    136.00                3
1           10100    S18_2248               50     55.09                2
2           10100    S18_4409               22     75.46                4
3           10100    S24_3969               49     35.29                1
4           10101    S18_2325               25    108.06                4
...           ...         ...              ...       ...              ...
2991        10425    S24_2300               49    127.79                9
2992        10425    S24_2840               31     31.82                5
2993        10425    S32_1268               41     83.79               11
2994        10425    S32_2509               11     50.32                6
2995        10425    S50_1392               18     94.92                2

[2996 rows x 5 columns]

In [7]:
import pandas as pd
import mysql.connector


connect = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    password = '4774',
    database = 'classicmodels'
)

cursor = connect.cursor()
cursor.execute('SHOW TABLES')
nombres_tablas = [row[0] for row in cursor.fetchall()]

db = {}

for taulas in nombres_tablas:
    cursor.execute(f'select * from {taulas}')
    lineas2 = cursor.fetchall()
    columnas2 = cursor.column_names
    df = pd.DataFrame(lineas2,columns=columnas2)
    db[taulas] = df

In [ ]:
import pandas as pd
import mysql.connector
import matplotlib.pyplot as plt
import seaborn as sns

connect = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    password = '4774',
    database = 'classicmodels'
                          )

cursor = connect.cursor()
cursor.execute('SHOW TABLES')
nombre_tablas = [row[0] for row in cursor.fetchall()]

db_classic = {}

for tablas in nombre_tablas:
    cursor.execute(f'select * from {tablas}')
    lineas = cursor.fetchall()
    columnas = cursor.column_names
    df = pd.DataFrame(lineas,columns=columnas)
    db_classic[tablas] = df

In [7]:
db_classic['customers']

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,France,1370.0,21000.00
1,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,None,Las Vegas,NV,83030,USA,1166.0,71800.00
2,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611.0,117300.00
3,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",None,Nantes,None,44000,France,1370.0,118200.00
4,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,None,Stavern,None,4110,Norway,1504.0,81700.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,486,Motor Mint Distributors Inc.,Salazar,Rosa,2155559857,11328 Douglas Av.,None,Philadelphia,PA,71270,USA,1323.0,72600.00
118,487,Signal Collectibles Ltd.,Taylor,Sue,4155554312,2793 Furth Circle,None,Brisbane,CA,94217,USA,1165.0,60300.00
119,489,"Double Decker Gift Stores, Ltd",Smith,Thomas,(171) 555-7555,120 Hanover Sq.,None,London,None,WA1 1DP,UK,1501.0,43300.00
120,495,Diecast Collectables,Franco,Valarie,6175552555,6251 Ingle Ln.,None,Boston,MA,51003,USA,1188.0,85100.00
121,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,New Zealand,1612.0,110000.00

In [14]:
import pandas as pd
import mysql.connector
from pandas.api.types import(is_numeric_dtype,is_object_dtype,is_datetime64_any_dtype)
import matplotlib.pyplot as plt
import seaborn as sns


connect = mysql.connector.connect(
    host = 'localhost',
    user ='root',
    password = '4774',
    database = 'classicmodels'
)

cursor = connect.cursor()
cursor.execute('SHOW TABLES')
tablas_name = [row[0] for row in cursor.fetchall()]

db_classic_models = {}

for tablas in tablas_name:
    cursor.execute(f'select * from {tablas}')
    datos = cursor.fetchall()
    cursor_column_names = cursor.column_names
    df = pd.DataFrame(datos, columns = cursor_column_names)
    db_classic_models[tablas] = df

connect.close()

In [15]:
db_classic_models['customers']

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",None,Nantes,None,44000,France,1370.0,21000.00
1,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,None,Las Vegas,NV,83030,USA,1166.0,71800.00
2,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611.0,117300.00
3,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",None,Nantes,None,44000,France,1370.0,118200.00
4,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,None,Stavern,None,4110,Norway,1504.0,81700.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,486,Motor Mint Distributors Inc.,Salazar,Rosa,2155559857,11328 Douglas Av.,None,Philadelphia,PA,71270,USA,1323.0,72600.00
118,487,Signal Collectibles Ltd.,Taylor,Sue,4155554312,2793 Furth Circle,None,Brisbane,CA,94217,USA,1165.0,60300.00
119,489,"Double Decker Gift Stores, Ltd",Smith,Thomas,(171) 555-7555,120 Hanover Sq.,None,London,None,WA1 1DP,UK,1501.0,43300.00
120,495,Diecast Collectables,Franco,Valarie,6175552555,6251 Ingle Ln.,None,Boston,MA,51003,USA,1188.0,85100.00
121,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',None,Auckland,None,None,New Zealand,1612.0,110000.00