In [1]:
# Library for opening url and creating requests
import urllib.request

# for parsing all the tables present on the website (analyse (a string or text) into logical syntactic components)
from html_table_parser.parser import HTMLTableParser

import pandas as pd

In [2]:

def url_get_contents(url):

    '''
    Opens a website and read its binary contents (HTTP Response Body)
    '''
    request = urllib.request.Request(url=url)
    file = urllib.request.urlopen(request)

    return file.read()

In [3]:
# defining the html contents of a URL.
xhtml = url_get_contents('https://en.wikipedia.org/wiki/Wimbledon_Championships').decode('utf-8')

# defining the HTMLTableParser object
parser = HTMLTableParser()

# feeding the html contents in the HTMLTableParser object
parser.feed(xhtml)

# create df with the parser tables and select [ ] the desired one

prize_money = pd.DataFrame(parser.tables[1])
prize_money

,0,1,2,3,4,5,6
0,Year,Gentlemen's singles,Gentlemen's doubles (pair),Ladies' singles,Ladies' doubles (pair),Mixed doubles (pair),Total for tournament
1,1968,"£2,000",£800,£750,£500,£450,"£26,150"
2,1969,"£3,000","£1,000","£1,500",£600,£500,"£33,370"
3,1970,"£3,000","£1,000","£1,500",£600,£500,"£41,650"
4,1971,"£3,750",£750,"£1,800",£450,£375,"£37,790"
5,1972,"£5,000","£1,000","£3,000",£600,£500,"£50,330"
6,1973,"£5,000","£1,000","£3,000",£600,£500,"£52,400"
7,1974,"£10,000","£2,000","£7,000","£1,200","£1,000","£97,100"
8,1975,"£10,000","£2,000","£7,000","£1,200","£1,000","£114,875"
9,1976,"£12,500","£3,000","£10,000","£2,400","£2,000","£157,740"
10,1977,"£15,000","£6,000","£13,500","£5,200","£3,000","£222,540"
11,1978,"£19,000","£7,500","£17,100","£6,500","£4,000","£279,023"
12,1979,"£20,000","£8,000","£18,000","£6,930","£4,200","£277,066"
13,1980,"£20,000","£8,400","£18,000","£7,276","£4,420","£293,464"
14,1981,"£21,600","£9,070","£19,400","£7,854","£4,770","£322,136"
15,1982,"£41,667","£16,666","£37,500","£14,450","£6,750","£593,366"
16,1983,"£66,600","£26,628","£60,000","£23,100","£12,000","£978,211"
17,1984,"£100,000","£40,000","£90,000","£34,700","£18,000","£1,461,896"
18,1985,"£130,000","£47,500","£117,000","£41,100","£23,400","£1,934,760"
19,1986,"£140,000","£48,500","£126,000","£42,060","£25,200","£2,119,780"
20,1987,"£155,000","£53,730","£139,500","£46,500","£27,900","£2,470,020"
21,1988,"£165,000","£57,200","£148,500","£49,500","£29,700","£2,612,126"
22,1989,"£190,000","£65,870","£171,000","£56,970","£34,200","£3,133,749"
23,1990,"£230,000","£94,230","£207,000","£81,510","£40,000","£3,819,730"
24,1991,"£240,000","£98,330","£216,000","£85,060","£41,720","£4,010,970"
25,1992,"£265,000","£108,570","£240,000","£93,920","£46,070","£4,416,820"
26,1993,"£305,000","£124,960","£275,000","£108,100","£53,020","£5,048,450"
27,1994,"£345,000","£141,350","£310,000","£122,200","£60,000","£5,682,170"
28,1995,"£365,000","£149,540","£328,000","£129,300","£63,500","£6,025,550"
29,1996,"£392,500","£160,810","£353,000","£139,040","£68,280","£6,465,910"
30,1997,"£415,000","£170,030","£373,500","£147,010","£72,200","£6,884,952"
31,1998,"£435,000","£178,220","£391,500","£154,160","£75,700","£7,207,590"
32,1999,"£455,000","£186,420","£409,500","£167,770","£79,180","£7,595,330"
33,2000,"£477,500","£195,630","£430,000","£176,070","£83,100","£8,056,480"
34,2001,"£500,000","£205,000","£462,500","£189,620","£87,000","£8,525,280"
35,2002,"£525,000","£210,000","£486,000","£194,250","£88,500","£8,825,320"
36,2003,"£575,000","£210,000","£535,000","£194,250","£88,500","£9,373,990"
37,2004,"£602,500","£215,000","£560,500","£200,000","£90,000","£9,707,280"
38,2005,"£630,000","£218,500","£600,000","£203,250","£90,000","£10,085,510"
39,2006,"£655,000","£220,690","£625,000","£205,280","£90,000","£10,378,710"
40,2007,"£700,000","£222,900","£700,000","£222,900","£90,000","£11,282,710"
41,2008,"£750,000","£230,000","£750,000","£230,000","£92,000","£11,812,000"
42,2009,"£850,000","£230,000","£850,000","£230,000","£92,000","£12,550,000"
43,2010,"£1,000,000","£240,000","£1,000,000","£240,000","£92,000","£13,725,000"
44,2011,"£1,100,000","£250,000","£1,100,000","£250,000","£92,000","£14,600,000"
45,2012,"£1,150,000","£260,000","£1,150,000","£260,000","£92,000","£16,060,000"
46,2013,"£1,600,000","£300,000","£1,600,000","£300,000","£92,000","£22,560,000"
47,2014,"£1,760,000","£325,000","£1,760,000","£325,000","£96,000","£25,000,000"
48,2015,"£1,880,000","£340,000","£1,880,000","£340,000","£100,000","£26,750,000"
49,2016,"£2,000,000","£350,000","£2,000,000","£350,000","£100,000","£28,100,000"
50,2017,"£2,200,000","£400,000","£2,200,000","£400,000","£100,000","£31,600,000"
51,2018,"£2,250,000","£450,000","£2,250,000","£450,000","£110,000","£34,000,000"
52,2019,"£2,350,000","£540,000","£2,350,000","£540,000","£116,000","£38,000,000"
53,2021,"£1,700,000","£480,000","£1,700,000","£480,000","£100,000","£35,016,000"
54,2022,"£2,000,000","£540,000","£2,000,000","£540,000","£124,000","£40,350,000"
55,2023,"£2,350,000","£600,000","£2,350,000","£600,000","£128,000","£44,700,000"
56,2024,"£2,700,000","£650,000","£2,700,000","£650,000","£130,000","£50,000,000"
57,2025,"£3,000,000","£680,000","£3,000,000","£680,000","£135,000","£53,550,000"

In [4]:
WIM_prizemoney_2025 = pd.DataFrame(parser.tables[2])
WIM_prizemoney_2025 = WIM_prizemoney_2025.iloc[0:2,:]
WIM_prizemoney_2025

,0,1,2,3,4,5,6,7,8,9,10,11
0,Event,W,F,SF,QF,Round of 16,Round of 32,Round of 64,Round of 128 1,Q3,Q2,Q1
1,Singles,"£3,000,000","£1,520,000","£775,000","£400,000","£240,000","£152,000","£99,000","£66,000","£41,500","£26,000","£15,500"

In [5]:
# limpiar df y poner las columnas en su sitio
WIM_clean = WIM_prizemoney_2025.iloc[1:].copy()
WIM_clean.columns = WIM_prizemoney_2025.iloc[0]

In [6]:
WIM_clean

,Event,W,F,SF,QF,Round of 16,Round of 32,Round of 64,Round of 128 1,Q3,Q2,Q1
1,Singles,"£3,000,000","£1,520,000","£775,000","£400,000","£240,000","£152,000","£99,000","£66,000","£41,500","£26,000","£15,500"

In [7]:
WIM_clean = WIM_clean[['W','F','SF','QF','Round of 16','Round of 32','Round of 64','Round of 128 1','Q3','Q2','Q1']] = WIM_clean[['W','F','SF','QF','Round of 16','Round of 32','Round of 64','Round of 128 1','Q3','Q2','Q1']].replace('[\£,]', '', regex=True).astype(float)
WIM_clean

,W,F,SF,QF,Round of 16,Round of 32,Round of 64,Round of 128 1,Q3,Q2,Q1
1,3000000.0,1520000.0,775000.0,400000.0,240000.0,152000.0,99000.0,66000.0,41500.0,26000.0,15500.0

RANKING POINTS

In [8]:
ranking_points_2025 = pd.DataFrame(parser.tables[3])
ranking_points_2025 = ranking_points_2025.iloc[[0,1],:]
duplicate = ranking_points_2025.iloc[1,:].copy()

In [9]:
ranking_points_2025

         0          1     2     3    4    5    6    7   8     9
0    Event          W     F    SF   QF   4R   3R   2R  1R  None
1  Singles  Gentlemen  2000  1300  800  400  200  100  50    10

In [10]:
duplicate

0      Singles
1    Gentlemen
2         2000
3         1300
4          800
5          400
6          200
7          100
8           50
9           10
Name: 1, dtype: object

In [11]:
ladies = duplicate.replace('Gentlemen','Ladies')
ladies

0    Singles
1     Ladies
2       2000
3       1300
4        800
5        400
6        200
7        100
8         50
9         10
Name: 1, dtype: object

In [12]:
ranking_points_2025 = pd.concat([ranking_points_2025.iloc[:1], pd.DataFrame([ladies]), ranking_points_2025.iloc[1:]], ignore_index=True)
ranking_points_2025

         0          1     2     3    4    5    6    7   8     9
0    Event          W     F    SF   QF   4R   3R   2R  1R  None
1  Singles     Ladies  2000  1300  800  400  200  100  50    10
2  Singles  Gentlemen  2000  1300  800  400  200  100  50    10

#### ( (IPC Año Actual - IPC Año Anterior) / IPC Año Anterior ) * 100 = Porcentaje de Aumento del IPC por año. ####

In [13]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)

### US OPEN

In [14]:
# defining the html contents of a URL.
xhtml = url_get_contents('https://en.wikipedia.org/wiki/US_Open_(tennis)').decode('utf-8')

# defining the HTMLTableParser object
parser = HTMLTableParser()

# feeding the html contents in the HTMLTableParser object
parser.feed(xhtml)

# create df with the parser tables and select [ ] the desired one

US_prize_money = pd.DataFrame(parser.tables[5])
US_prize_money = US_prize_money.iloc[0:2,:]
US_prize_money

,0,1,2,3,4,5,6,7,8,9,10,11
0,Event,W,F,SF,QF,Round of 16,Round of 32,Round of 64,Round of 128,Q3,Q2,Q1
1,Singles,"$3,000,000","$1,800,000","$775,000","$455,000","$284,000","$191,000","$123,000","$81,500","$45,000","$34,500","$22,000"

In [15]:
# limpiar df y poner las columnas en su sitio
df_US_prize = US_prize_money.iloc[1:].copy()
df_US_prize.columns = US_prize_money.iloc[0]

In [16]:
df_US_prize[['W','F','SF','QF','Round of 16','Round of 32','Round of 64','Round of 128','Q3','Q2','Q1']] = df_US_prize[['W','F','SF','QF','Round of 16','Round of 32','Round of 64','Round of 128','Q3','Q2','Q1']].replace('[\$,]', '', regex=True).astype(float);
df_US_prize

<>:1: SyntaxWarning: invalid escape sequence '\$'
<>:1: SyntaxWarning: invalid escape sequence '\$'
C:\Users\Usuario\AppData\Local\Temp\ipykernel_19324\259149408.py:1: SyntaxWarning: invalid escape sequence '\$'
  df_US_prize[['W','F','SF','QF','Round of 16','Round of 32','Round of 64','Round of 128','Q3','Q2','Q1']] = df_US_prize[['W','F','SF','QF','Round of 16','Round of 32','Round of 64','Round of 128','Q3','Q2','Q1']].replace('[\$,]', '', regex=True).astype(float);

,Event,W,F,SF,QF,Round of 16,Round of 32,Round of 64,Round of 128,Q3,Q2,Q1
1,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00

### ROLAND GARROS

In [17]:
# defining the html contents of a URL.
xhtml = url_get_contents('https://en.wikipedia.org/wiki/French_Open').decode('utf-8')

# defining the HTMLTableParser object
parser = HTMLTableParser()

# feeding the html contents in the HTMLTableParser object
parser.feed(xhtml)

# create df with the parser tables and select [ ] the desired one

RG_prize_money = pd.DataFrame(parser.tables[1])
RG_prize_money = RG_prize_money.iloc[0:2,:]
RG_prize_money

,0,1,2,3,4,5,6,7,8,9,10,11
0,Event,Winner,Finalist,Semifinals,Quarterfinals,Round of 16,Round of 32,Round of 64,Round of 128,Q3,Q2,Q1
1,Singles,"€2,550,000","€1,275,000","€690,000","€440,000","€265,000","€168,000","€117,000","€78,000","€43,000","€29,500","€21,000"

In [18]:
# limpiar df y poner las columnas en su sitio
RG_prize_clean = RG_prize_money.iloc[1:].copy()
RG_prize_clean.columns = RG_prize_money.iloc[0]
RG_prize_clean

,Event,Winner,Finalist,Semifinals,Quarterfinals,Round of 16,Round of 32,Round of 64,Round of 128,Q3,Q2,Q1
1,Singles,"€2,550,000","€1,275,000","€690,000","€440,000","€265,000","€168,000","€117,000","€78,000","€43,000","€29,500","€21,000"

In [19]:
RG_prize_clean[['Winner','Finalist','Semifinals','Quarterfinals','Round of 16','Round of 32','Round of 64','Round of 128','Q3','Q2','Q1']] = RG_prize_clean[['Winner','Finalist','Semifinals','Quarterfinals','Round of 16','Round of 32','Round of 64','Round of 128','Q3','Q2','Q1']].replace('[\€,]', '', regex=True).astype(float);
RG_prize_clean

,Event,Winner,Finalist,Semifinals,Quarterfinals,Round of 16,Round of 32,Round of 64,Round of 128,Q3,Q2,Q1
1,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00

### AUSTRALIAN OPEN

In [20]:
# defining the html contents of a URL.
xhtml = url_get_contents('https://en.wikipedia.org/wiki/Australian_Open').decode('utf-8')

# defining the HTMLTableParser object
parser = HTMLTableParser()

# feeding the html contents in the HTMLTableParser object
parser.feed(xhtml)

# create df with the parser tables and select [ ] the desired one

AUS_prize_money = pd.DataFrame(parser.tables[3])
AUS_prize_money = AUS_prize_money.iloc[0:2,:]
AUS_prize_money

,0,1,2,3,4,5,6,7,8,9,10,11
0,Event,W,F,SF,QF,4R,3R,2R,1R,Q3,Q2,Q1
1,Singles,"A$3,500,000","A$1,900,000","A$1,100,000","A$665,000","A$420,000","A$290,000","A$200,000","A$132,000","A$72,000","A$49,000","A$35,000"

In [21]:
aus_prize_clean = AUS_prize_money.iloc[1:].copy()
aus_prize_clean.columns = AUS_prize_money.iloc[0]
aus_prize_clean

,Event,W,F,SF,QF,4R,3R,2R,1R,Q3,Q2,Q1
1,Singles,"A$3,500,000","A$1,900,000","A$1,100,000","A$665,000","A$420,000","A$290,000","A$200,000","A$132,000","A$72,000","A$49,000","A$35,000"

In [22]:
aus_prize_clean = aus_prize_clean[['W','F','SF','QF','4R','3R','2R','1R','Q3','Q2','Q1']] = aus_prize_clean[['W','F','SF','QF','4R','3R','2R','1R','Q3','Q2','Q1']].replace('[A$U$,]', '', regex=True).astype(float)
aus_prize_clean

,W,F,SF,QF,4R,3R,2R,1R,Q3,Q2,Q1
1,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00

3500000/(1.03 ** (2024-x))

DF YEARS -- df_years = pd.DataFrame({'year': range(2000, 2025)})

In [23]:
df_years = pd.DataFrame({'year': range(2000, 2025)})
df_years

    year
0   2000
1   2001
2   2002
3   2003
4   2004
5   2005
6   2006
7   2007
8   2008
9   2009
10  2010
11  2011
12  2012
13  2013
14  2014
15  2015
16  2016
17  2017
18  2018
19  2019
20  2020
21  2021
22  2022
23  2023
24  2024

US OPEN

In [24]:
us_prize_years = pd.merge(df_years,df_US_prize, how='cross')
us_prize_years

,year,Event,W,F,SF,QF,Round of 16,Round of 32,Round of 64,Round of 128,Q3,Q2,Q1
0,2000,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
1,2001,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
2,2002,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
3,2003,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
4,2004,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
5,2005,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
6,2006,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
7,2007,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
8,2008,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
9,2009,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
10,2010,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
11,2011,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
12,2012,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
13,2013,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
14,2014,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
15,2015,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
16,2016,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
17,2017,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
18,2018,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
19,2019,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
20,2020,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
21,2021,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
22,2022,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
23,2023,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
24,2024,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00

In [25]:
us_prize_rename = us_prize_years.rename(columns={'Round of 16':'R16','Round of 32':'R32','Round of 64':'R64','Round of 128':'R128'})
us_prize_rename

,year,Event,W,F,SF,QF,R16,R32,R64,R128,Q3,Q2,Q1
0,2000,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
1,2001,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
2,2002,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
3,2003,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
4,2004,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
5,2005,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
6,2006,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
7,2007,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
8,2008,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
9,2009,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
10,2010,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
11,2011,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
12,2012,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
13,2013,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
14,2014,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
15,2015,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
16,2016,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
17,2017,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
18,2018,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
19,2019,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
20,2020,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
21,2021,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
22,2022,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
23,2023,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00
24,2024,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00

ROLAND GARROS

In [26]:
df_RG_prize_clean = pd.merge(df_years,RG_prize_clean,how='cross')
df_RG_prize_rename = df_RG_prize_clean.rename(columns={'Winner':'W','Finalist':'F','Semifinals':'SF','Quarterfinals':'QF','Round of 16':'R16','Round of 32':'R32','Round of 64':'R64','Round of 128':'R128'})
df_RG_prize_rename

,year,Event,W,F,SF,QF,R16,R32,R64,R128,Q3,Q2,Q1
0,2000,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
1,2001,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
2,2002,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
3,2003,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
4,2004,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
5,2005,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
6,2006,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
7,2007,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
8,2008,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
9,2009,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
10,2010,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
11,2011,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
12,2012,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
13,2013,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
14,2014,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
15,2015,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
16,2016,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
17,2017,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
18,2018,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
19,2019,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
20,2020,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
21,2021,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
22,2022,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
23,2023,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00
24,2024,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00

WIMBLEDON

In [27]:
df_Wimbledon_clean = pd.merge(df_years,WIM_clean,how='cross')
df_Wimbledon_rename = df_Wimbledon_clean.rename(columns={'Round of 128 1':'R128','Round of 64':'R64','Round of 32':'R32','Round of 16':'R16'})
df_Wimbledon_rename

,year,W,F,SF,QF,R16,R32,R64,R128,Q3,Q2,Q1
0,2000,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
1,2001,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
2,2002,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
3,2003,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
4,2004,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
5,2005,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
6,2006,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
7,2007,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
8,2008,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
9,2009,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
10,2010,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
11,2011,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
12,2012,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
13,2013,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
14,2014,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
15,2015,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
16,2016,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
17,2017,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
18,2018,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
19,2019,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
20,2020,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
21,2021,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
22,2022,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
23,2023,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00
24,2024,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00

AUSTRALIAN OPEN CSV

In [43]:
df_aus_prize_clean = pd.merge(df_years,aus_prize_clean,how='cross')
df_aus_prize_rename = df_aus_prize_clean.rename(columns={'4R':'R16','3R':'R32','2R':'R64','1R':'R128'})
df_aus_prize_rename

,year,W,F,SF,QF,R16,R32,R64,R128,Q3,Q2,Q1
0,2000,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
1,2001,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
2,2002,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
3,2003,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
4,2004,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
5,2005,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
6,2006,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
7,2007,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
8,2008,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
9,2009,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
10,2010,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
11,2011,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
12,2012,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
13,2013,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
14,2014,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
15,2015,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
16,2016,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
17,2017,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
18,2018,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
19,2019,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
20,2020,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
21,2021,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
22,2022,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
23,2023,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00
24,2024,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00

BUCLE PARA RENOMBRAR COLUMNAS DESPUES DE NORMALIZAR LAS TABLAS DE PREMIOS Y AÑADIR LA REGRESIÓN POR AÑO DEL 2.54% DE IPC

In [29]:
diccionario_rondas = {
    'W':'W',
    'F':'F',
    'SF':'SF',
    'QF':'QF',
    'R16':'R16',
    'R32':'R32',
    'R64':'R64',
    'R128':'R128',
    'Q3':'Q3',
    'Q2':'Q2',
    'Q1':'Q1'
}

for rounds,columna in diccionario_rondas.items():
    df_Wimbledon_rename[columna] = df_Wimbledon_rename[rounds] / (1.0254 ** (2024 - df_Wimbledon_rename['year']))

In [30]:
df_Wimbledon_rename['tourney key'] = "WIMBLEDON - " + df_Wimbledon_rename['year'].astype(str)
df_Wimbledon_rename

,year,W,F,SF,QF,R16,R32,R64,R128,Q3,Q2,Q1,tourney key
0,2000,1643167.14,832538.02,424484.84,219088.95,131453.37,83253.80,54224.52,36149.68,22730.48,14240.78,8489.70,WIMBLEDON - 2000
1,2001,1684903.58,853684.48,435266.76,224653.81,134792.29,85368.45,55601.82,37067.88,23307.83,14602.50,8705.34,WIMBLEDON - 2001
2,2002,1727700.13,875368.07,446322.53,230360.02,138216.01,87536.81,57014.10,38009.40,23899.85,14973.40,8926.45,WIMBLEDON - 2002
3,2003,1771583.72,897602.42,457659.13,236211.16,141726.70,89760.24,58462.26,38974.84,24506.91,15353.73,9153.18,WIMBLEDON - 2003
4,2004,1816581.94,920401.52,469283.67,242210.93,145326.56,92040.15,59947.20,39964.80,25129.38,15743.71,9385.67,WIMBLEDON - 2004
5,2005,1862723.12,943779.72,481203.47,248363.08,149017.85,94377.97,61469.86,40979.91,25767.67,16143.60,9624.07,WIMBLEDON - 2005
6,2006,1910036.29,967751.72,493426.04,254671.51,152802.90,96775.17,63031.20,42020.80,26422.17,16553.65,9868.52,WIMBLEDON - 2006
7,2007,1958551.21,992332.61,505959.06,261140.16,156684.10,99233.26,64632.19,43088.13,27093.29,16974.11,10119.18,WIMBLEDON - 2007
8,2008,2008298.41,1017537.86,518810.42,267773.12,160663.87,101753.79,66273.85,44182.57,27781.46,17405.25,10376.21,WIMBLEDON - 2008
9,2009,2059309.19,1043383.32,531988.21,274574.56,164744.74,104338.33,67957.20,45304.80,28487.11,17847.35,10639.76,WIMBLEDON - 2009
10,2010,2111615.65,1069885.26,545500.71,281548.75,168929.25,106988.53,69683.32,46455.54,29210.68,18300.67,10910.01,WIMBLEDON - 2010
11,2011,2165250.68,1097060.35,559356.43,288700.09,173220.05,109706.03,71453.27,47635.52,29952.63,18765.51,11187.13,WIMBLEDON - 2011
12,2012,2220248.05,1124925.68,573564.08,296033.07,177619.84,112492.57,73268.19,48845.46,30713.43,19242.15,11471.28,WIMBLEDON - 2012
13,2013,2276642.35,1153498.79,588132.61,303552.31,182131.39,115349.88,75129.20,50086.13,31493.55,19730.90,11762.65,WIMBLEDON - 2013
14,2014,2334469.07,1182797.66,603071.18,311262.54,186757.53,118279.77,77037.48,51358.32,32293.49,20232.07,12061.42,WIMBLEDON - 2014
15,2015,2393764.58,1212840.72,618389.18,319168.61,191501.17,121284.07,78994.23,52662.82,33113.74,20745.96,12367.78,WIMBLEDON - 2015
16,2016,2454566.20,1243646.88,634096.27,327275.49,196365.30,124364.69,81000.68,54000.46,33954.83,21272.91,12681.93,WIMBLEDON - 2016
17,2017,2516912.18,1275235.51,650202.31,335588.29,201352.97,127523.55,83058.10,55372.07,34817.29,21813.24,13004.05,WIMBLEDON - 2017
18,2018,2580841.75,1307626.49,666717.45,344112.23,206467.34,130762.65,85167.78,56778.52,35701.64,22367.30,13334.35,WIMBLEDON - 2018
19,2019,2646395.13,1340840.20,683652.08,352852.68,211711.61,134084.02,87331.04,58220.69,36608.47,22935.42,13673.04,WIMBLEDON - 2019
20,2020,2713613.57,1374897.54,701016.84,361815.14,217089.09,137489.75,89549.25,59699.50,37538.32,23517.98,14020.34,WIMBLEDON - 2020
21,2021,2782539.35,1409819.94,718822.67,371005.25,222603.15,140981.99,91823.80,61215.87,38491.79,24115.34,14376.45,WIMBLEDON - 2021
22,2022,2853215.85,1445629.37,737080.76,380428.78,228257.27,144562.94,94156.12,62770.75,39469.49,24727.87,14741.62,WIMBLEDON - 2022
23,2023,2925687.54,1482348.35,755802.61,390091.67,234055.00,148234.84,96547.69,64365.13,40472.01,25355.96,15116.05,WIMBLEDON - 2023
24,2024,3000000.00,1520000.00,775000.00,400000.00,240000.00,152000.00,99000.00,66000.00,41500.00,26000.00,15500.00,WIMBLEDON - 2024

In [31]:
diccionario_rondas = {
    'W':'W',
    'F':'F',
    'SF':'SF',
    'QF':'QF',
    'R16':'R16',
    'R32':'R32',
    'R64':'R64',
    'R128':'R128',
    'Q3':'Q3',
    'Q2':'Q2',
    'Q1':'Q1'
}

for rounds,columna in diccionario_rondas.items():
    df_aus_prize_rename[columna] = df_aus_prize_rename[rounds] / (1.0254 ** (2024 - df_aus_prize_rename['year']))

In [32]:
df_aus_prize_rename['tourney key'] = "AUSTRALIAN OPEN - " + df_aus_prize_rename['year'].astype(str)
df_aus_prize_rename

,year,W,F,SF,QF,R16,R32,R64,R128,Q3,Q2,Q1,tourney key
0,2000,1917028.33,1040672.52,602494.62,364235.38,230043.40,158839.49,109544.48,72299.35,39436.01,26838.40,19170.28,AUSTRALIAN OPEN - 2000
1,2001,1965720.84,1067105.60,617797.98,373486.96,235886.50,162874.01,112326.91,74135.76,40437.69,27520.09,19657.21,AUSTRALIAN OPEN - 2001
2,2002,2015650.15,1094210.08,633490.05,382973.53,241878.02,167011.01,115180.01,76018.81,41464.80,28219.10,20156.50,AUSTRALIAN OPEN - 2002
3,2003,2066847.67,1122003.02,649580.70,392701.06,248021.72,171253.09,118105.58,77949.68,42518.01,28935.87,20668.48,AUSTRALIAN OPEN - 2003
4,2004,2119345.60,1150501.90,666080.05,402675.66,254321.47,175602.92,121105.46,79929.61,43597.97,29670.84,21193.46,AUSTRALIAN OPEN - 2004
5,2005,2173176.98,1179724.64,682998.48,412903.63,260781.24,180063.24,124181.54,81959.82,44705.35,30424.48,21731.77,AUSTRALIAN OPEN - 2005
6,2006,2228375.67,1209689.65,700346.64,423391.38,267405.08,184636.84,127335.75,84041.60,45840.87,31197.26,22283.76,AUSTRALIAN OPEN - 2006
7,2007,2284976.41,1240415.77,718135.44,434145.52,274197.17,189326.62,130570.08,86176.25,47005.23,31989.67,22849.76,AUSTRALIAN OPEN - 2007
8,2008,2343014.82,1271922.33,736376.08,445172.81,281161.78,194135.51,133886.56,88365.13,48199.16,32802.21,23430.15,AUSTRALIAN OPEN - 2008
9,2009,2402527.39,1304229.16,755080.04,456480.20,288303.29,199066.56,137287.28,90609.60,49423.42,33635.38,24025.27,AUSTRALIAN OPEN - 2009
10,2010,2463551.59,1337356.58,774259.07,468074.80,295626.19,204122.85,140774.38,92911.09,50678.78,34489.72,24635.52,AUSTRALIAN OPEN - 2010
11,2011,2526125.80,1371325.43,793925.25,479963.90,303135.10,209307.57,144350.05,95271.03,51966.02,35365.76,25261.26,AUSTRALIAN OPEN - 2011
12,2012,2590289.39,1406157.10,814090.95,492154.98,310834.73,214623.98,148016.54,97690.91,53285.95,36264.05,25902.89,AUSTRALIAN OPEN - 2012
13,2013,2656082.74,1441873.49,834768.86,504655.72,318729.93,220075.43,151776.16,100172.26,54639.42,37185.16,26560.83,AUSTRALIAN OPEN - 2013
14,2014,2723547.24,1478497.08,855971.99,517473.98,326825.67,225665.34,155631.27,102716.64,56027.26,38129.66,27235.47,AUSTRALIAN OPEN - 2014
15,2015,2792725.34,1516050.90,877713.68,530617.82,335127.04,231397.24,159584.31,105325.64,57450.35,39098.15,27927.25,AUSTRALIAN OPEN - 2015
16,2016,2863660.57,1554558.59,900007.61,544095.51,343639.27,237274.73,163637.75,108000.91,58909.59,40091.25,28636.61,AUSTRALIAN OPEN - 2016
17,2017,2936397.55,1594044.38,922867.80,557915.53,352367.71,243301.51,167794.15,110744.14,60405.89,41109.57,29363.98,AUSTRALIAN OPEN - 2017
18,2018,3010982.04,1634533.11,946308.64,572086.59,361317.85,249481.37,172056.12,113557.04,61940.20,42153.75,30109.82,AUSTRALIAN OPEN - 2018
19,2019,3087460.99,1676050.25,970344.88,586617.59,370495.32,255818.20,176426.34,116441.39,63513.48,43224.45,30874.61,AUSTRALIAN OPEN - 2019
20,2020,3165882.50,1718621.93,994991.64,601517.67,379905.90,262315.98,180907.57,119399.00,65126.73,44322.35,31658.82,AUSTRALIAN OPEN - 2020
21,2021,3246295.91,1762274.92,1020264.43,616796.22,389555.51,268978.80,185502.62,122431.73,66780.94,45448.14,32462.96,AUSTRALIAN OPEN - 2021
22,2022,3328751.83,1807036.71,1046179.15,632462.85,399450.22,275810.87,190214.39,125541.50,68477.18,46602.53,33287.52,AUSTRALIAN OPEN - 2022
23,2023,3413302.13,1852935.44,1072752.10,648527.40,409596.26,282816.46,195045.84,128730.25,70216.50,47786.23,34133.02,AUSTRALIAN OPEN - 2023
24,2024,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00,AUSTRALIAN OPEN - 2024

In [33]:
diccionario_rondas = {
    'W':'W',
    'F':'F',
    'SF':'SF',
    'QF':'QF',
    'R16':'R16',
    'R32':'R32',
    'R64':'R64',
    'R128':'R128',
    'Q3':'Q3',
    'Q2':'Q2',
    'Q1':'Q1'
}

for rounds,columna in diccionario_rondas.items():
    df_RG_prize_rename[columna] = df_RG_prize_rename[rounds] / (1.0254 ** (2024 - df_RG_prize_rename['year']))

In [34]:
df_RG_prize_rename['tourney key'] = "ROLAND GARROS - " + df_RG_prize_rename['year'].astype(str)
df_RG_prize_rename

,year,Event,W,F,SF,QF,R16,R32,R64,R128,Q3,Q2,Q1,tourney key
0,2000,Singles,1396692.07,698346.03,377928.44,240997.85,145146.43,92017.36,64083.52,42722.35,23552.06,16157.81,11502.17,ROLAND GARROS - 2000
1,2001,Singles,1432168.04,716084.02,387527.82,247119.19,148833.15,94354.60,65711.24,43807.49,24150.28,16568.22,11794.33,ROLAND GARROS - 2001
2,2002,Singles,1468545.11,734272.56,397371.03,253396.02,152613.51,96751.21,67380.31,44920.20,24763.70,16989.05,12093.90,ROLAND GARROS - 2002
3,2003,Singles,1505846.16,752923.08,407464.25,259832.28,156489.89,99208.69,69091.76,46061.18,25392.70,17420.57,12401.09,ROLAND GARROS - 2003
4,2004,Singles,1544094.65,772047.33,417813.85,266432.02,160464.74,101728.59,70846.70,47231.13,26037.67,17863.06,12716.07,ROLAND GARROS - 2004
5,2005,Singles,1583314.65,791657.33,428426.32,273199.39,164540.54,104312.49,72646.20,48430.80,26699.03,18316.78,13039.06,ROLAND GARROS - 2005
6,2006,Singles,1623530.85,811765.42,439308.35,280138.66,168719.87,106962.03,74491.42,49660.94,27377.19,18782.02,13370.25,ROLAND GARROS - 2006
7,2007,Singles,1664768.53,832384.27,450466.78,287254.18,173005.36,109678.87,76383.50,50922.33,28072.57,19259.09,13709.86,ROLAND GARROS - 2007
8,2008,Singles,1707053.65,853526.83,461908.63,294550.43,177399.69,112464.71,78323.64,52215.76,28785.61,19748.27,14058.09,ROLAND GARROS - 2008
9,2009,Singles,1750412.81,875206.41,473641.11,302032.01,181905.65,115321.31,80313.06,53542.04,29516.77,20249.87,14415.16,ROLAND GARROS - 2009
10,2010,Singles,1794873.30,897436.65,485671.60,309703.63,186526.05,118250.48,82353.01,54902.01,30266.49,20764.22,14781.31,ROLAND GARROS - 2010
11,2011,Singles,1840463.08,920231.54,498007.66,317570.10,191263.81,121254.04,84444.78,56296.52,31035.26,21291.63,15156.75,ROLAND GARROS - 2011
12,2012,Singles,1887210.84,943605.42,510657.05,325636.38,196121.91,124333.89,86589.67,57726.45,31823.56,21832.44,15541.74,ROLAND GARROS - 2012
13,2013,Singles,1935146.00,967573.00,523627.74,333907.54,201103.41,127491.97,88789.05,59192.70,32631.87,22386.98,15936.50,ROLAND GARROS - 2013
14,2014,Singles,1984298.71,992149.35,536927.89,342388.80,206211.43,130730.27,91044.29,60696.20,33460.72,22955.61,16341.28,ROLAND GARROS - 2014
15,2015,Singles,2034699.89,1017349.95,550565.85,351085.47,211449.20,134050.82,93356.82,62237.88,34310.63,23538.69,16756.35,ROLAND GARROS - 2015
16,2016,Singles,2086381.27,1043190.64,564550.23,360003.04,216820.01,137455.71,95728.08,63818.72,35182.12,24136.57,17181.96,ROLAND GARROS - 2016
17,2017,Singles,2139375.36,1069687.68,578889.80,369147.12,222327.24,140947.08,98159.58,65439.72,36075.74,24749.64,17618.39,ROLAND GARROS - 2017
18,2018,Singles,2193715.49,1096857.74,593593.60,378523.46,227974.35,144527.14,100652.83,67101.89,36992.07,25378.28,18065.89,ROLAND GARROS - 2018
19,2019,Singles,2249435.86,1124717.93,608670.88,388137.95,233764.90,148198.13,103209.41,68806.27,37931.66,26022.89,18524.77,ROLAND GARROS - 2019
20,2020,Singles,2306571.53,1153285.77,624131.12,397996.66,239702.53,151962.36,105830.93,70553.95,38895.13,26683.87,18995.29,ROLAND GARROS - 2020
21,2021,Singles,2365158.45,1182579.23,639984.05,408105.77,245790.98,155822.20,108519.03,72346.02,39883.06,27361.64,19477.78,ROLAND GARROS - 2021
22,2022,Singles,2425233.48,1212616.74,656239.65,418471.66,252034.07,159780.09,111275.42,74183.61,40896.09,28056.62,19972.51,ROLAND GARROS - 2022
23,2023,Singles,2486834.41,1243417.20,672908.13,429100.84,258435.73,163838.50,114101.81,76067.88,41934.85,28769.26,20479.81,ROLAND GARROS - 2023
24,2024,Singles,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00,ROLAND GARROS - 2024

In [35]:
df_RG_prize_rename_new = df_RG_prize_rename.drop('Event',axis='columns')
df_RG_prize_rename_new

,year,W,F,SF,QF,R16,R32,R64,R128,Q3,Q2,Q1,tourney key
0,2000,1396692.07,698346.03,377928.44,240997.85,145146.43,92017.36,64083.52,42722.35,23552.06,16157.81,11502.17,ROLAND GARROS - 2000
1,2001,1432168.04,716084.02,387527.82,247119.19,148833.15,94354.60,65711.24,43807.49,24150.28,16568.22,11794.33,ROLAND GARROS - 2001
2,2002,1468545.11,734272.56,397371.03,253396.02,152613.51,96751.21,67380.31,44920.20,24763.70,16989.05,12093.90,ROLAND GARROS - 2002
3,2003,1505846.16,752923.08,407464.25,259832.28,156489.89,99208.69,69091.76,46061.18,25392.70,17420.57,12401.09,ROLAND GARROS - 2003
4,2004,1544094.65,772047.33,417813.85,266432.02,160464.74,101728.59,70846.70,47231.13,26037.67,17863.06,12716.07,ROLAND GARROS - 2004
5,2005,1583314.65,791657.33,428426.32,273199.39,164540.54,104312.49,72646.20,48430.80,26699.03,18316.78,13039.06,ROLAND GARROS - 2005
6,2006,1623530.85,811765.42,439308.35,280138.66,168719.87,106962.03,74491.42,49660.94,27377.19,18782.02,13370.25,ROLAND GARROS - 2006
7,2007,1664768.53,832384.27,450466.78,287254.18,173005.36,109678.87,76383.50,50922.33,28072.57,19259.09,13709.86,ROLAND GARROS - 2007
8,2008,1707053.65,853526.83,461908.63,294550.43,177399.69,112464.71,78323.64,52215.76,28785.61,19748.27,14058.09,ROLAND GARROS - 2008
9,2009,1750412.81,875206.41,473641.11,302032.01,181905.65,115321.31,80313.06,53542.04,29516.77,20249.87,14415.16,ROLAND GARROS - 2009
10,2010,1794873.30,897436.65,485671.60,309703.63,186526.05,118250.48,82353.01,54902.01,30266.49,20764.22,14781.31,ROLAND GARROS - 2010
11,2011,1840463.08,920231.54,498007.66,317570.10,191263.81,121254.04,84444.78,56296.52,31035.26,21291.63,15156.75,ROLAND GARROS - 2011
12,2012,1887210.84,943605.42,510657.05,325636.38,196121.91,124333.89,86589.67,57726.45,31823.56,21832.44,15541.74,ROLAND GARROS - 2012
13,2013,1935146.00,967573.00,523627.74,333907.54,201103.41,127491.97,88789.05,59192.70,32631.87,22386.98,15936.50,ROLAND GARROS - 2013
14,2014,1984298.71,992149.35,536927.89,342388.80,206211.43,130730.27,91044.29,60696.20,33460.72,22955.61,16341.28,ROLAND GARROS - 2014
15,2015,2034699.89,1017349.95,550565.85,351085.47,211449.20,134050.82,93356.82,62237.88,34310.63,23538.69,16756.35,ROLAND GARROS - 2015
16,2016,2086381.27,1043190.64,564550.23,360003.04,216820.01,137455.71,95728.08,63818.72,35182.12,24136.57,17181.96,ROLAND GARROS - 2016
17,2017,2139375.36,1069687.68,578889.80,369147.12,222327.24,140947.08,98159.58,65439.72,36075.74,24749.64,17618.39,ROLAND GARROS - 2017
18,2018,2193715.49,1096857.74,593593.60,378523.46,227974.35,144527.14,100652.83,67101.89,36992.07,25378.28,18065.89,ROLAND GARROS - 2018
19,2019,2249435.86,1124717.93,608670.88,388137.95,233764.90,148198.13,103209.41,68806.27,37931.66,26022.89,18524.77,ROLAND GARROS - 2019
20,2020,2306571.53,1153285.77,624131.12,397996.66,239702.53,151962.36,105830.93,70553.95,38895.13,26683.87,18995.29,ROLAND GARROS - 2020
21,2021,2365158.45,1182579.23,639984.05,408105.77,245790.98,155822.20,108519.03,72346.02,39883.06,27361.64,19477.78,ROLAND GARROS - 2021
22,2022,2425233.48,1212616.74,656239.65,418471.66,252034.07,159780.09,111275.42,74183.61,40896.09,28056.62,19972.51,ROLAND GARROS - 2022
23,2023,2486834.41,1243417.20,672908.13,429100.84,258435.73,163838.50,114101.81,76067.88,41934.85,28769.26,20479.81,ROLAND GARROS - 2023
24,2024,2550000.00,1275000.00,690000.00,440000.00,265000.00,168000.00,117000.00,78000.00,43000.00,29500.00,21000.00,ROLAND GARROS - 2024

In [36]:
diccionario_rondas = {
    'W':'W',
    'F':'F',
    'SF':'SF',
    'QF':'QF',
    'R16':'R16',
    'R32':'R32',
    'R64':'R64',
    'R128':'R128',
    'Q3':'Q3',
    'Q2':'Q2',
    'Q1':'Q1'
}

for rounds,columna in diccionario_rondas.items():
    us_prize_rename[columna] = us_prize_rename[rounds] / (1.0254 ** (2024 - us_prize_rename['year']))

In [37]:
us_prize_rename['tourney key'] = "US OPEN - " + df_RG_prize_rename['year'].astype(str)
us_prize_rename

,year,Event,W,F,SF,QF,R16,R32,R64,R128,Q3,Q2,Q1,tourney key
0,2000,Singles,1643167.14,985900.28,424484.84,249213.68,155553.16,104614.97,67369.85,44639.37,24647.51,18896.42,12049.89,US OPEN - 2000
1,2001,Singles,1684903.58,1010942.15,435266.76,255543.71,159504.21,107272.19,69081.05,45773.21,25273.55,19376.39,12355.96,US OPEN - 2001
2,2002,Singles,1727700.13,1036620.08,446322.53,262034.52,163555.61,109996.91,70835.71,46935.85,25915.50,19868.55,12669.80,US OPEN - 2002
3,2003,Singles,1771583.72,1062950.23,457659.13,268690.20,167709.93,112790.83,72634.93,48128.02,26573.76,20373.21,12991.61,US OPEN - 2003
4,2004,Singles,1816581.94,1089949.17,469283.67,275514.93,171969.76,115655.72,74479.86,49350.48,27248.73,20890.69,13321.60,US OPEN - 2004
5,2005,Singles,1862723.12,1117633.87,481203.47,282513.01,176337.79,118593.37,76371.65,50603.98,27940.85,21421.32,13659.97,US OPEN - 2005
6,2006,Singles,1910036.29,1146021.77,493426.04,289688.84,180816.77,121605.64,78311.49,51889.32,28650.54,21965.42,14006.93,US OPEN - 2006
7,2007,Singles,1958551.21,1175130.73,505959.06,297046.93,185409.51,124694.43,80300.60,53207.31,29378.27,22523.34,14362.71,US OPEN - 2007
8,2008,Singles,2008298.41,1204979.05,518810.42,304591.93,190118.92,127861.67,82340.23,54558.77,30124.48,23095.43,14727.52,US OPEN - 2008
9,2009,Singles,2059309.19,1235585.52,531988.21,312328.56,194947.94,131109.35,84431.68,55944.57,30889.64,23682.06,15101.60,US OPEN - 2009
10,2010,Singles,2111615.65,1266969.39,545500.71,320261.71,199899.61,134439.53,86576.24,57365.56,31674.23,24283.58,15485.18,US OPEN - 2010
11,2011,Singles,2165250.68,1299150.41,559356.43,328396.35,204977.06,137854.29,88775.28,58822.64,32478.76,24900.38,15878.51,US OPEN - 2011
12,2012,Singles,2220248.05,1332148.83,573564.08,336737.62,210183.48,141355.79,91030.17,60316.74,33303.72,25532.85,16281.82,US OPEN - 2012
13,2013,Singles,2276642.35,1365985.41,588132.61,345290.76,215522.14,144946.23,93342.34,61848.78,34149.64,26181.39,16695.38,US OPEN - 2013
14,2014,Singles,2334469.07,1400681.44,603071.18,354061.14,220996.41,148627.86,95713.23,63419.74,35017.04,26846.39,17119.44,US OPEN - 2014
15,2015,Singles,2393764.58,1436258.75,618389.18,363054.29,226609.71,152403.01,98144.35,65030.60,35906.47,27528.29,17554.27,US OPEN - 2015
16,2016,Singles,2454566.20,1472739.72,634096.27,372275.87,232365.60,156274.05,100637.21,66682.38,36818.49,28227.51,18000.15,US OPEN - 2016
17,2017,Singles,2516912.18,1510147.31,650202.31,381731.68,238267.69,160243.41,103193.40,68376.11,37753.68,28944.49,18457.36,US OPEN - 2017
18,2018,Singles,2580841.75,1548505.05,666717.45,391427.67,244319.69,164313.59,105814.51,70112.87,38712.63,29679.68,18926.17,US OPEN - 2018
19,2019,Singles,2646395.13,1587837.08,683652.08,401369.93,250525.41,168487.16,108502.20,71893.73,39695.93,30433.54,19406.90,US OPEN - 2019
20,2020,Singles,2713613.57,1628168.14,701016.84,411564.72,256888.75,172766.73,111258.16,73719.84,40704.20,31206.56,19899.83,US OPEN - 2020
21,2021,Singles,2782539.35,1669523.61,718822.67,422018.47,263413.73,177155.01,114084.11,75592.32,41738.09,31999.20,20405.29,US OPEN - 2021
22,2022,Singles,2853215.85,1711929.51,737080.76,432737.74,270104.43,181654.74,116981.85,77512.36,42798.24,32811.98,20923.58,US OPEN - 2022
23,2023,Singles,2925687.54,1755412.52,755802.61,443729.28,276965.09,186268.77,119953.19,79481.18,43885.31,33645.41,21455.04,US OPEN - 2023
24,2024,Singles,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00,US OPEN - 2024

In [38]:
us_prize_rename_new = us_prize_rename.drop('Event',axis='columns')
us_prize_rename_new

,year,W,F,SF,QF,R16,R32,R64,R128,Q3,Q2,Q1,tourney key
0,2000,1643167.14,985900.28,424484.84,249213.68,155553.16,104614.97,67369.85,44639.37,24647.51,18896.42,12049.89,US OPEN - 2000
1,2001,1684903.58,1010942.15,435266.76,255543.71,159504.21,107272.19,69081.05,45773.21,25273.55,19376.39,12355.96,US OPEN - 2001
2,2002,1727700.13,1036620.08,446322.53,262034.52,163555.61,109996.91,70835.71,46935.85,25915.50,19868.55,12669.80,US OPEN - 2002
3,2003,1771583.72,1062950.23,457659.13,268690.20,167709.93,112790.83,72634.93,48128.02,26573.76,20373.21,12991.61,US OPEN - 2003
4,2004,1816581.94,1089949.17,469283.67,275514.93,171969.76,115655.72,74479.86,49350.48,27248.73,20890.69,13321.60,US OPEN - 2004
5,2005,1862723.12,1117633.87,481203.47,282513.01,176337.79,118593.37,76371.65,50603.98,27940.85,21421.32,13659.97,US OPEN - 2005
6,2006,1910036.29,1146021.77,493426.04,289688.84,180816.77,121605.64,78311.49,51889.32,28650.54,21965.42,14006.93,US OPEN - 2006
7,2007,1958551.21,1175130.73,505959.06,297046.93,185409.51,124694.43,80300.60,53207.31,29378.27,22523.34,14362.71,US OPEN - 2007
8,2008,2008298.41,1204979.05,518810.42,304591.93,190118.92,127861.67,82340.23,54558.77,30124.48,23095.43,14727.52,US OPEN - 2008
9,2009,2059309.19,1235585.52,531988.21,312328.56,194947.94,131109.35,84431.68,55944.57,30889.64,23682.06,15101.60,US OPEN - 2009
10,2010,2111615.65,1266969.39,545500.71,320261.71,199899.61,134439.53,86576.24,57365.56,31674.23,24283.58,15485.18,US OPEN - 2010
11,2011,2165250.68,1299150.41,559356.43,328396.35,204977.06,137854.29,88775.28,58822.64,32478.76,24900.38,15878.51,US OPEN - 2011
12,2012,2220248.05,1332148.83,573564.08,336737.62,210183.48,141355.79,91030.17,60316.74,33303.72,25532.85,16281.82,US OPEN - 2012
13,2013,2276642.35,1365985.41,588132.61,345290.76,215522.14,144946.23,93342.34,61848.78,34149.64,26181.39,16695.38,US OPEN - 2013
14,2014,2334469.07,1400681.44,603071.18,354061.14,220996.41,148627.86,95713.23,63419.74,35017.04,26846.39,17119.44,US OPEN - 2014
15,2015,2393764.58,1436258.75,618389.18,363054.29,226609.71,152403.01,98144.35,65030.60,35906.47,27528.29,17554.27,US OPEN - 2015
16,2016,2454566.20,1472739.72,634096.27,372275.87,232365.60,156274.05,100637.21,66682.38,36818.49,28227.51,18000.15,US OPEN - 2016
17,2017,2516912.18,1510147.31,650202.31,381731.68,238267.69,160243.41,103193.40,68376.11,37753.68,28944.49,18457.36,US OPEN - 2017
18,2018,2580841.75,1548505.05,666717.45,391427.67,244319.69,164313.59,105814.51,70112.87,38712.63,29679.68,18926.17,US OPEN - 2018
19,2019,2646395.13,1587837.08,683652.08,401369.93,250525.41,168487.16,108502.20,71893.73,39695.93,30433.54,19406.90,US OPEN - 2019
20,2020,2713613.57,1628168.14,701016.84,411564.72,256888.75,172766.73,111258.16,73719.84,40704.20,31206.56,19899.83,US OPEN - 2020
21,2021,2782539.35,1669523.61,718822.67,422018.47,263413.73,177155.01,114084.11,75592.32,41738.09,31999.20,20405.29,US OPEN - 2021
22,2022,2853215.85,1711929.51,737080.76,432737.74,270104.43,181654.74,116981.85,77512.36,42798.24,32811.98,20923.58,US OPEN - 2022
23,2023,2925687.54,1755412.52,755802.61,443729.28,276965.09,186268.77,119953.19,79481.18,43885.31,33645.41,21455.04,US OPEN - 2023
24,2024,3000000.00,1800000.00,775000.00,455000.00,284000.00,191000.00,123000.00,81500.00,45000.00,34500.00,22000.00,US OPEN - 2024

In [39]:
df_concat = pd.concat([us_prize_rename_new,df_RG_prize_rename_new,df_Wimbledon_rename,df_aus_prize_rename],ignore_index=True)
df_concat

,year,W,F,SF,QF,R16,R32,R64,R128,Q3,Q2,Q1,tourney key
0,2000,1643167.14,985900.28,424484.84,249213.68,155553.16,104614.97,67369.85,44639.37,24647.51,18896.42,12049.89,US OPEN - 2000
1,2001,1684903.58,1010942.15,435266.76,255543.71,159504.21,107272.19,69081.05,45773.21,25273.55,19376.39,12355.96,US OPEN - 2001
2,2002,1727700.13,1036620.08,446322.53,262034.52,163555.61,109996.91,70835.71,46935.85,25915.50,19868.55,12669.80,US OPEN - 2002
3,2003,1771583.72,1062950.23,457659.13,268690.20,167709.93,112790.83,72634.93,48128.02,26573.76,20373.21,12991.61,US OPEN - 2003
4,2004,1816581.94,1089949.17,469283.67,275514.93,171969.76,115655.72,74479.86,49350.48,27248.73,20890.69,13321.60,US OPEN - 2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2020,3165882.50,1718621.93,994991.64,601517.67,379905.90,262315.98,180907.57,119399.00,65126.73,44322.35,31658.82,AUSTRALIAN OPEN - 2020
96,2021,3246295.91,1762274.92,1020264.43,616796.22,389555.51,268978.80,185502.62,122431.73,66780.94,45448.14,32462.96,AUSTRALIAN OPEN - 2021
97,2022,3328751.83,1807036.71,1046179.15,632462.85,399450.22,275810.87,190214.39,125541.50,68477.18,46602.53,33287.52,AUSTRALIAN OPEN - 2022
98,2023,3413302.13,1852935.44,1072752.10,648527.40,409596.26,282816.46,195045.84,128730.25,70216.50,47786.23,34133.02,AUSTRALIAN OPEN - 2023
99,2024,3500000.00,1900000.00,1100000.00,665000.00,420000.00,290000.00,200000.00,132000.00,72000.00,49000.00,35000.00,AUSTRALIAN OPEN - 2024

In [40]:
df_melt = df_concat.melt(
    id_vars=['year','tourney key'],
    value_vars=['W','F','SF','QF','R16','R32','R64','R128','Q3','Q2','Q1']
)

In [ ]:
df_melt = df_melt.rename(columns={'variable':'round','value':'premio €'})
df_melt

      year             tourney key round   premio €
0     2000          US OPEN - 2000     W 1643167.14
1     2001          US OPEN - 2001     W 1684903.58
2     2002          US OPEN - 2002     W 1727700.13
3     2003          US OPEN - 2003     W 1771583.72
4     2004          US OPEN - 2004     W 1816581.94
...    ...                     ...   ...        ...
1095  2020  AUSTRALIAN OPEN - 2020    Q1   31658.82
1096  2021  AUSTRALIAN OPEN - 2021    Q1   32462.96
1097  2022  AUSTRALIAN OPEN - 2022    Q1   33287.52
1098  2023  AUSTRALIAN OPEN - 2023    Q1   34133.02
1099  2024  AUSTRALIAN OPEN - 2024    Q1   35000.00

[1100 rows x 4 columns]

In [46]:
df_melt['tourney key'] = df_melt['tourney key'].str.lower()

In [47]:
df_melt

      year             tourney key round   premio €
0     2000          us open - 2000     W 1643167.14
1     2001          us open - 2001     W 1684903.58
2     2002          us open - 2002     W 1727700.13
3     2003          us open - 2003     W 1771583.72
4     2004          us open - 2004     W 1816581.94
...    ...                     ...   ...        ...
1095  2020  australian open - 2020    Q1   31658.82
1096  2021  australian open - 2021    Q1   32462.96
1097  2022  australian open - 2022    Q1   33287.52
1098  2023  australian open - 2023    Q1   34133.02
1099  2024  australian open - 2024    Q1   35000.00

[1100 rows x 4 columns]

In [49]:
df_melt.to_csv('melt premios tennis.csv')