In [28]:
import pandas as pd

In [29]:
partidos = pd.read_csv('partidos_atp_2000_2024.csv')
partidos

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
0,2000-301,Auckland,Hard,32,A,20000110,1,103163,1.0,NaN,...,39.0,29.0,17.0,4.0,7.0,11.0,1612.0,63.0,595.0,2000
1,2000-301,Auckland,Hard,32,A,20000110,2,102607,NaN,Q,...,25.0,18.0,12.0,3.0,6.0,211.0,157.0,49.0,723.0,2000
2,2000-301,Auckland,Hard,32,A,20000110,3,103252,NaN,NaN,...,20.0,7.0,8.0,7.0,11.0,48.0,726.0,59.0,649.0,2000
3,2000-301,Auckland,Hard,32,A,20000110,4,103507,7.0,NaN,...,29.0,14.0,10.0,6.0,8.0,45.0,768.0,61.0,616.0,2000
4,2000-301,Auckland,Hard,32,A,20000110,5,102103,NaN,Q,...,34.0,18.0,12.0,5.0,9.0,167.0,219.0,34.0,873.0,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74901,2024-M-DC-2024-WG2-PO-URU-MDA-01,Davis Cup WG2 PO: URU vs MDA,Clay,4,D,20240203,5,212051,NaN,NaN,...,17.0,7.0,6.0,8.0,14.0,1109.0,8.0,740.0,34.0,2024
74902,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,1,122533,NaN,NaN,...,25.0,6.0,9.0,1.0,4.0,554.0,67.0,748.0,32.0,2024
74903,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,2,144748,NaN,NaN,...,25.0,7.0,11.0,5.0,12.0,416.0,109.0,NaN,NaN,2024
74904,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,4,122533,NaN,NaN,...,32.0,17.0,14.0,5.0,9.0,554.0,67.0,416.0,109.0,2024
74905,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,5,202475,NaN,NaN,...,25.0,8.0,8.0,9.0,14.0,748.0,32.0,NaN,NaN,2024

In [30]:
us_open = partidos[partidos['tourney_name'] == 'us open']

In [31]:
us_open2 = partidos[partidos['tourney_name'] == 'Us open']
us_open2

Empty DataFrame
Columns: [tourney_id, tourney_name, surface, draw_size, tourney_level, tourney_date, match_num, winner_id, winner_seed, winner_entry, winner_name, winner_hand, winner_ht, winner_ioc, winner_age, loser_id, loser_seed, loser_entry, loser_name, loser_hand, loser_ht, loser_ioc, loser_age, score, best_of, round, minutes, w_ace, w_df, w_svpt, w_1stIn, w_1stWon, w_2ndWon, w_SvGms, w_bpSaved, w_bpFaced, l_ace, l_df, l_svpt, l_1stIn, l_1stWon, l_2ndWon, l_SvGms, l_bpSaved, l_bpFaced, winner_rank, winner_rank_points, loser_rank, loser_rank_points, year]
Index: []

[0 rows x 50 columns]

In [32]:
us_open.tail(20)

Empty DataFrame
Columns: [tourney_id, tourney_name, surface, draw_size, tourney_level, tourney_date, match_num, winner_id, winner_seed, winner_entry, winner_name, winner_hand, winner_ht, winner_ioc, winner_age, loser_id, loser_seed, loser_entry, loser_name, loser_hand, loser_ht, loser_ioc, loser_age, score, best_of, round, minutes, w_ace, w_df, w_svpt, w_1stIn, w_1stWon, w_2ndWon, w_SvGms, w_bpSaved, w_bpFaced, l_ace, l_df, l_svpt, l_1stIn, l_1stWon, l_2ndWon, l_SvGms, l_bpSaved, l_bpFaced, winner_rank, winner_rank_points, loser_rank, loser_rank_points, year]
Index: []

[0 rows x 50 columns]

In [33]:
partidos.isnull().sum()

tourney_id                0
tourney_name              0
surface                  53
draw_size                 0
tourney_level             0
tourney_date              0
match_num                 0
winner_id                 0
winner_seed           43786
winner_entry          65400
winner_name               0
winner_hand               0
winner_ht              1425
winner_ioc                0
winner_age                5
loser_id                  0
loser_seed            57668
loser_entry           59484
loser_name                0
loser_hand                4
loser_ht               2909
loser_ioc                 0
loser_age                 3
score                     0
best_of                   0
round                     0
minutes                8174
w_ace                  6520
w_df                   6520
w_svpt                 6520
w_1stIn                6520
w_1stWon               6520
w_2ndWon               6520
w_SvGms                6520
w_bpSaved              6520
w_bpFaced              6520
l_ace                  6520
l_df                   6520
l_svpt                 6520
l_1stIn                6520
l_1stWon               6520
l_2ndWon               6520
l_SvGms                6520
l_bpSaved              6520
l_bpFaced              6520
winner_rank             573
winner_rank_points      573
loser_rank             1468
loser_rank_points      1468
year                      0
dtype: int64

In [34]:
partidos['tourney_name'] = partidos['tourney_name'].str.strip().str.lower()

In [35]:
grand_slams_2000_2024 = partidos[(partidos['tourney_name'] == 'us open') | (partidos['tourney_name'] == 'australian open') | (partidos['tourney_name'] == 'roland garros') | (partidos['tourney_name'] == 'wimbledon')]
grand_slams_2000_2024

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
2130,2000-520,roland garros,Clay,128,G,20000529,1,101736,1.0,NaN,...,38.0,22.0,16.0,9.0,13.0,1.0,5085.0,116.0,355.0,2000
2131,2000-520,roland garros,Clay,128,G,20000529,2,102344,NaN,NaN,...,13.0,9.0,11.0,14.0,23.0,40.0,845.0,219.0,158.0,2000
2132,2000-520,roland garros,Clay,128,G,20000529,3,103181,NaN,NaN,...,65.0,15.0,23.0,12.0,25.0,88.0,463.0,83.0,494.0,2000
2133,2000-520,roland garros,Clay,128,G,20000529,4,102644,NaN,NaN,...,27.0,17.0,16.0,9.0,17.0,45.0,802.0,110.0,376.0,2000
2134,2000-520,roland garros,Clay,128,G,20000529,5,103454,NaN,NaN,...,36.0,10.0,14.0,5.0,12.0,75.0,579.0,130.0,310.0,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74139,2024-560,us open,Hard,128,G,20240826,222,126203,12.0,NaN,...,77.0,20.0,22.0,11.0,13.0,12.0,3120.0,4.0,7035.0,2024
74140,2024-560,us open,Hard,128,G,20240826,223,126207,20.0,NaN,...,53.0,22.0,18.0,8.0,14.0,20.0,2120.0,9.0,3655.0,2024
74141,2024-560,us open,Hard,128,G,20240826,224,206173,1.0,NaN,...,43.0,32.0,16.0,7.0,11.0,1.0,9360.0,25.0,1695.0,2024
74142,2024-560,us open,Hard,128,G,20240826,225,126203,12.0,NaN,...,57.0,27.0,24.0,5.0,11.0,12.0,3120.0,20.0,2120.0,2024
74143,2024-560,us open,Hard,128,G,20240826,226,206173,1.0,NaN,...,36.0,16.0,16.0,6.0,12.0,1.0,9360.0,12.0,3120.0,2024

In [36]:
grand_slams_2000_2024

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
2130,2000-520,roland garros,Clay,128,G,20000529,1,101736,1.0,NaN,...,38.0,22.0,16.0,9.0,13.0,1.0,5085.0,116.0,355.0,2000
2131,2000-520,roland garros,Clay,128,G,20000529,2,102344,NaN,NaN,...,13.0,9.0,11.0,14.0,23.0,40.0,845.0,219.0,158.0,2000
2132,2000-520,roland garros,Clay,128,G,20000529,3,103181,NaN,NaN,...,65.0,15.0,23.0,12.0,25.0,88.0,463.0,83.0,494.0,2000
2133,2000-520,roland garros,Clay,128,G,20000529,4,102644,NaN,NaN,...,27.0,17.0,16.0,9.0,17.0,45.0,802.0,110.0,376.0,2000
2134,2000-520,roland garros,Clay,128,G,20000529,5,103454,NaN,NaN,...,36.0,10.0,14.0,5.0,12.0,75.0,579.0,130.0,310.0,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74139,2024-560,us open,Hard,128,G,20240826,222,126203,12.0,NaN,...,77.0,20.0,22.0,11.0,13.0,12.0,3120.0,4.0,7035.0,2024
74140,2024-560,us open,Hard,128,G,20240826,223,126207,20.0,NaN,...,53.0,22.0,18.0,8.0,14.0,20.0,2120.0,9.0,3655.0,2024
74141,2024-560,us open,Hard,128,G,20240826,224,206173,1.0,NaN,...,43.0,32.0,16.0,7.0,11.0,1.0,9360.0,25.0,1695.0,2024
74142,2024-560,us open,Hard,128,G,20240826,225,126203,12.0,NaN,...,57.0,27.0,24.0,5.0,11.0,12.0,3120.0,20.0,2120.0,2024
74143,2024-560,us open,Hard,128,G,20240826,226,206173,1.0,NaN,...,36.0,16.0,16.0,6.0,12.0,1.0,9360.0,12.0,3120.0,2024

In [38]:
grand_slams_2000_2024.to_csv('grand_slams_2000_2024.csv', index=False)