In [1]:
import pandas as pd

In [2]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [3]:
torneos_unidos = pd.read_csv('partidos_atp_2000_2024.csv')
torneos_unidos

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
0,2000-301,Auckland,Hard,32,A,20000110,1,103163,1.00,NaN,...,39.00,29.00,17.00,4.00,7.00,11.00,1612.00,63.00,595.00,2000
1,2000-301,Auckland,Hard,32,A,20000110,2,102607,NaN,Q,...,25.00,18.00,12.00,3.00,6.00,211.00,157.00,49.00,723.00,2000
2,2000-301,Auckland,Hard,32,A,20000110,3,103252,NaN,NaN,...,20.00,7.00,8.00,7.00,11.00,48.00,726.00,59.00,649.00,2000
3,2000-301,Auckland,Hard,32,A,20000110,4,103507,7.00,NaN,...,29.00,14.00,10.00,6.00,8.00,45.00,768.00,61.00,616.00,2000
4,2000-301,Auckland,Hard,32,A,20000110,5,102103,NaN,Q,...,34.00,18.00,12.00,5.00,9.00,167.00,219.00,34.00,873.00,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74901,2024-M-DC-2024-WG2-PO-URU-MDA-01,Davis Cup WG2 PO: URU vs MDA,Clay,4,D,20240203,5,212051,NaN,NaN,...,17.00,7.00,6.00,8.00,14.00,1109.00,8.00,740.00,34.00,2024
74902,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,1,122533,NaN,NaN,...,25.00,6.00,9.00,1.00,4.00,554.00,67.00,748.00,32.00,2024
74903,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,2,144748,NaN,NaN,...,25.00,7.00,11.00,5.00,12.00,416.00,109.00,NaN,NaN,2024
74904,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,4,122533,NaN,NaN,...,32.00,17.00,14.00,5.00,9.00,554.00,67.00,416.00,109.00,2024
74905,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,5,202475,NaN,NaN,...,25.00,8.00,8.00,9.00,14.00,748.00,32.00,NaN,NaN,2024

In [4]:
torneos_unidos['tourney_name'] = torneos_unidos['tourney_name'].str.strip().str.lower()

In [5]:
grand_slams = torneos_unidos[torneos_unidos['tourney_name'].isin(['us open','wimbledon','roland garros','australian open'])]
grand_slams

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
2130,2000-520,roland garros,Clay,128,G,20000529,1,101736,1.00,NaN,...,38.00,22.00,16.00,9.00,13.00,1.00,5085.00,116.00,355.00,2000
2131,2000-520,roland garros,Clay,128,G,20000529,2,102344,NaN,NaN,...,13.00,9.00,11.00,14.00,23.00,40.00,845.00,219.00,158.00,2000
2132,2000-520,roland garros,Clay,128,G,20000529,3,103181,NaN,NaN,...,65.00,15.00,23.00,12.00,25.00,88.00,463.00,83.00,494.00,2000
2133,2000-520,roland garros,Clay,128,G,20000529,4,102644,NaN,NaN,...,27.00,17.00,16.00,9.00,17.00,45.00,802.00,110.00,376.00,2000
2134,2000-520,roland garros,Clay,128,G,20000529,5,103454,NaN,NaN,...,36.00,10.00,14.00,5.00,12.00,75.00,579.00,130.00,310.00,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74139,2024-560,us open,Hard,128,G,20240826,222,126203,12.00,NaN,...,77.00,20.00,22.00,11.00,13.00,12.00,3120.00,4.00,7035.00,2024
74140,2024-560,us open,Hard,128,G,20240826,223,126207,20.00,NaN,...,53.00,22.00,18.00,8.00,14.00,20.00,2120.00,9.00,3655.00,2024
74141,2024-560,us open,Hard,128,G,20240826,224,206173,1.00,NaN,...,43.00,32.00,16.00,7.00,11.00,1.00,9360.00,25.00,1695.00,2024
74142,2024-560,us open,Hard,128,G,20240826,225,126203,12.00,NaN,...,57.00,27.00,24.00,5.00,11.00,12.00,3120.00,20.00,2120.00,2024
74143,2024-560,us open,Hard,128,G,20240826,226,206173,1.00,NaN,...,36.00,16.00,16.00,6.00,12.00,1.00,9360.00,12.00,3120.00,2024

In [6]:
grand_slams['tourney key'] = grand_slams['tourney_name'] + " - " + grand_slams['year'].astype(str)
grand_slams

C:\Users\Usuario\AppData\Local\Temp\ipykernel_16148\3722524323.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grand_slams['tourney key'] = grand_slams['tourney_name'] + " - " + grand_slams['year'].astype(str)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year,tourney key
2130,2000-520,roland garros,Clay,128,G,20000529,1,101736,1.00,NaN,...,22.00,16.00,9.00,13.00,1.00,5085.00,116.00,355.00,2000,roland garros - 2000
2131,2000-520,roland garros,Clay,128,G,20000529,2,102344,NaN,NaN,...,9.00,11.00,14.00,23.00,40.00,845.00,219.00,158.00,2000,roland garros - 2000
2132,2000-520,roland garros,Clay,128,G,20000529,3,103181,NaN,NaN,...,15.00,23.00,12.00,25.00,88.00,463.00,83.00,494.00,2000,roland garros - 2000
2133,2000-520,roland garros,Clay,128,G,20000529,4,102644,NaN,NaN,...,17.00,16.00,9.00,17.00,45.00,802.00,110.00,376.00,2000,roland garros - 2000
2134,2000-520,roland garros,Clay,128,G,20000529,5,103454,NaN,NaN,...,10.00,14.00,5.00,12.00,75.00,579.00,130.00,310.00,2000,roland garros - 2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74139,2024-560,us open,Hard,128,G,20240826,222,126203,12.00,NaN,...,20.00,22.00,11.00,13.00,12.00,3120.00,4.00,7035.00,2024,us open - 2024
74140,2024-560,us open,Hard,128,G,20240826,223,126207,20.00,NaN,...,22.00,18.00,8.00,14.00,20.00,2120.00,9.00,3655.00,2024,us open - 2024
74141,2024-560,us open,Hard,128,G,20240826,224,206173,1.00,NaN,...,32.00,16.00,7.00,11.00,1.00,9360.00,25.00,1695.00,2024,us open - 2024
74142,2024-560,us open,Hard,128,G,20240826,225,126203,12.00,NaN,...,27.00,24.00,5.00,11.00,12.00,3120.00,20.00,2120.00,2024,us open - 2024
74143,2024-560,us open,Hard,128,G,20240826,226,206173,1.00,NaN,...,16.00,16.00,6.00,12.00,1.00,9360.00,12.00,3120.00,2024,us open - 2024

------------------------ players

In [8]:
df_players = pd.read_csv('df_players_ATP_cleaned_Fix.csv')
df_players

,player_id,full_name,ioc,hand,height,tourney_name,tourney_date,winner_age,year,round,tourney key,torneo_id
0,100644,Alexander Zverev,GER,R,198.00,wimbledon,20150629,18.10,2015,R128,wimbledon - 2015,3
1,100644,Alexander Zverev,GER,R,198.00,roland garros,20160523,19.00,2016,R128,roland garros - 2016,2
2,100644,Alexander Zverev,GER,R,198.00,roland garros,20160523,19.00,2016,R64,roland garros - 2016,2
3,100644,Alexander Zverev,GER,R,198.00,wimbledon,20160627,19.10,2016,R128,wimbledon - 2016,3
4,100644,Alexander Zverev,GER,R,198.00,wimbledon,20160627,19.10,2016,R64,wimbledon - 2016,3
...,...,...,...,...,...,...,...,...,...,...,...,...
12568,210150,Jakub Mensik,CZE,R,193.00,us open,20240826,18.90,2024,R64,us open - 2024,4
12569,210506,Alex Michelsen,USA,R,193.00,us open,20230828,19.00,2023,R128,us open - 2023,4
12570,210506,Alex Michelsen,USA,R,193.00,australian open,20240115,19.30,2024,R128,australian open - 2024,1
12571,210506,Alex Michelsen,USA,R,193.00,australian open,20240115,19.30,2024,R64,australian open - 2024,1
12572,210506,Alex Michelsen,USA,R,193.00,us open,20240826,20.00,2024,R128,us open - 2024,4

In [10]:
df_top10 = df_players[df_players['full_name'].isin(['Carlos Alcaraz','Jannik Sinner','Alexander Zverev','Taylor Fritz','Jack Draper','Ben Shelton','Novak Djokovic','Alex de Minaur','Holger Rune','Lorenzo Musetti'])]
df_top10

,player_id,full_name,ioc,hand,height,tourney_name,tourney_date,winner_age,year,round,tourney key,torneo_id
0,100644,Alexander Zverev,GER,R,198.00,wimbledon,20150629,18.10,2015,R128,wimbledon - 2015,3
1,100644,Alexander Zverev,GER,R,198.00,roland garros,20160523,19.00,2016,R128,roland garros - 2016,2
2,100644,Alexander Zverev,GER,R,198.00,roland garros,20160523,19.00,2016,R64,roland garros - 2016,2
3,100644,Alexander Zverev,GER,R,198.00,wimbledon,20160627,19.10,2016,R128,wimbledon - 2016,3
4,100644,Alexander Zverev,GER,R,198.00,wimbledon,20160627,19.10,2016,R64,wimbledon - 2016,3
...,...,...,...,...,...,...,...,...,...,...,...,...
12559,210097,Ben Shelton,USA,L,193.00,wimbledon,20240701,21.70,2024,R128,wimbledon - 2024,3
12560,210097,Ben Shelton,USA,L,193.00,wimbledon,20240701,21.70,2024,R64,wimbledon - 2024,3
12561,210097,Ben Shelton,USA,L,193.00,wimbledon,20240701,21.70,2024,R32,wimbledon - 2024,3
12562,210097,Ben Shelton,USA,L,193.00,us open,20240826,21.80,2024,R128,us open - 2024,4
12563,210097,Ben Shelton,USA,L,193.00,us open,20240826,21.80,2024,R64,us open - 2024,4

In [11]:
players = pd.read_csv('atp_players.csv')
players

C:\Users\Usuario\AppData\Local\Temp\ipykernel_16148\4038618507.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  players = pd.read_csv('atp_players.csv')

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id
0,100001,Gardnar,Mulloy,R,19131122.00,USA,185.00,Q54544
1,100002,Pancho,Segura,R,19210620.00,ECU,168.00,Q54581
2,100003,Frank,Sedgman,R,19271002.00,AUS,180.00,Q962049
3,100004,Giuseppe,Merlo,R,19271011.00,ITA,NaN,Q1258752
4,100005,Richard,Gonzalez,R,19280509.00,USA,188.00,Q53554
...,...,...,...,...,...,...,...,...
65984,213700,Matvei,Kobiakov,U,NaN,RUS,NaN,NaN
65985,213701,Tobia Costanzo,Baragiola Mordini,U,NaN,ITA,NaN,NaN
65986,213702,Dominik,Wijntjes,U,NaN,NZL,NaN,NaN
65987,213703,Sam,Wensley,U,NaN,AUS,NaN,NaN
65988,213704,Harry,Roberts,U,NaN,AUS,NaN,NaN

In [12]:
players['full_name'] = players['name_first'] + " " + players['name_last']
players

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
0,100001,Gardnar,Mulloy,R,19131122.00,USA,185.00,Q54544,Gardnar Mulloy
1,100002,Pancho,Segura,R,19210620.00,ECU,168.00,Q54581,Pancho Segura
2,100003,Frank,Sedgman,R,19271002.00,AUS,180.00,Q962049,Frank Sedgman
3,100004,Giuseppe,Merlo,R,19271011.00,ITA,NaN,Q1258752,Giuseppe Merlo
4,100005,Richard,Gonzalez,R,19280509.00,USA,188.00,Q53554,Richard Gonzalez
...,...,...,...,...,...,...,...,...,...
65984,213700,Matvei,Kobiakov,U,NaN,RUS,NaN,NaN,Matvei Kobiakov
65985,213701,Tobia Costanzo,Baragiola Mordini,U,NaN,ITA,NaN,NaN,Tobia Costanzo Baragiola Mordini
65986,213702,Dominik,Wijntjes,U,NaN,NZL,NaN,NaN,Dominik Wijntjes
65987,213703,Sam,Wensley,U,NaN,AUS,NaN,NaN,Sam Wensley
65988,213704,Harry,Roberts,U,NaN,AUS,NaN,NaN,Harry Roberts

In [13]:
players_top10 = players[players['full_name'].isin(['Carlos Alcaraz','Jannik Sinner','Alexander Zverev','Taylor Fritz','Jack Draper','Ben Shelton','Novak Djokovic','Alex De Minaur','Holger Rune','Lorenzo Musetti'])]
players_top10

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
643,100644,Alexander,Zverev,R,19970420.00,GER,198.00,Q13990552,Alexander Zverev
4919,104925,Novak,Djokovic,R,19870522.00,SRB,188.00,Q5812,Novak Djokovic
26187,126203,Taylor,Fritz,R,19971028.00,USA,196.00,Q17660516,Taylor Fritz
52568,200282,Alex,De Minaur,R,19990217.00,AUS,183.00,Q22958938,Alex De Minaur
58459,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner
59804,207518,Lorenzo,Musetti,R,20020303.00,ITA,185.00,Q54813043,Lorenzo Musetti
60019,207733,Jack,Draper,L,20011222.00,GBR,193.00,Q65030599,Jack Draper
60275,207989,Carlos,Alcaraz,R,20030505.00,ESP,183.00,Q85518537,Carlos Alcaraz
60315,208029,Holger,Rune,R,20030429.00,DEN,188.00,NaN,Holger Rune
62383,210097,Ben,Shelton,L,20021009.00,USA,193.00,Q108532383,Ben Shelton

In [14]:
df_players_top10 = pd.merge(players_top10,grand_slams,how='inner',left_on='player_id',right_on='winner_id')
df_players_top10

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name,tourney_id,...,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year,tourney key
0,100644,Alexander,Zverev,R,19970420.00,GER,198.00,Q13990552,Alexander Zverev,2015-540,...,34.00,25.00,8.00,13.00,74.00,689.00,53.00,882.00,2015,wimbledon - 2015
1,100644,Alexander,Zverev,R,19970420.00,GER,198.00,Q13990552,Alexander Zverev,2016-520,...,35.00,22.00,8.00,12.00,41.00,1060.00,84.00,695.00,2016,roland garros - 2016
2,100644,Alexander,Zverev,R,19970420.00,GER,198.00,Q13990552,Alexander Zverev,2016-520,...,20.00,16.00,5.00,12.00,41.00,1060.00,90.00,628.00,2016,roland garros - 2016
3,100644,Alexander,Zverev,R,19970420.00,GER,198.00,Q13990552,Alexander Zverev,2016-540,...,19.00,13.00,3.00,9.00,28.00,1385.00,59.00,845.00,2016,wimbledon - 2016
4,100644,Alexander,Zverev,R,19970420.00,GER,198.00,Q13990552,Alexander Zverev,2016-540,...,22.00,21.00,4.00,12.00,28.00,1385.00,70.00,753.00,2016,wimbledon - 2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,210097,Ben,Shelton,L,20021009.00,USA,193.00,Q108532383,Ben Shelton,2024-540,...,40.00,23.00,9.00,12.00,14.00,2595.00,148.00,401.00,2024,wimbledon - 2024
778,210097,Ben,Shelton,L,20021009.00,USA,193.00,Q108532383,Ben Shelton,2024-540,...,26.00,27.00,4.00,5.00,14.00,2595.00,118.00,541.00,2024,wimbledon - 2024
779,210097,Ben,Shelton,L,20021009.00,USA,193.00,Q108532383,Ben Shelton,2024-540,...,31.00,24.00,11.00,16.00,14.00,2595.00,121.00,530.00,2024,wimbledon - 2024
780,210097,Ben,Shelton,L,20021009.00,USA,193.00,Q108532383,Ben Shelton,2024-560,...,22.00,13.00,6.00,11.00,13.00,3110.00,210.00,283.00,2024,us open - 2024
781,210097,Ben,Shelton,L,20021009.00,USA,193.00,Q108532383,Ben Shelton,2024-560,...,22.00,14.00,7.00,10.00,13.00,3110.00,67.00,791.00,2024,us open - 2024

In [15]:
df_players_top10_clean = df_players_top10.iloc[:,[5,8,14,16,23,32,34,35,-1,-2]]
df_players_top10_clean

,ioc,full_name,tourney_date,winner_id,winner_age,score,round,minutes,tourney key,year
0,GER,Alexander Zverev,20150629,100644,18.10,6-3 1-6 6-3 3-6 9-7,R128,NaN,wimbledon - 2015,2015
1,GER,Alexander Zverev,20160523,100644,19.00,5-7 6-2 7-6(6) 7-5,R128,188.00,roland garros - 2016,2016
2,GER,Alexander Zverev,20160523,100644,19.00,6-1 3-6 6-1 6-4,R64,129.00,roland garros - 2016,2016
3,GER,Alexander Zverev,20160627,100644,19.10,6-3 6-4 6-2,R128,96.00,wimbledon - 2016,2016
4,GER,Alexander Zverev,20160627,100644,19.10,6-4 3-6 6-0 4-6 6-2,R64,198.00,wimbledon - 2016,2016
...,...,...,...,...,...,...,...,...,...,...
777,USA,Ben Shelton,20240701,210097,21.70,4-6 6-3 3-6 6-3 6-4,R128,209.00,wimbledon - 2024,2024
778,USA,Ben Shelton,20240701,210097,21.70,4-6 7-6(5) 6-7(5) 6-3 7-6(7),R64,229.00,wimbledon - 2024,2024
779,USA,Ben Shelton,20240701,210097,21.70,6-7(4) 6-2 6-4 4-6 6-2,R32,185.00,wimbledon - 2024,2024
780,USA,Ben Shelton,20240826,210097,21.80,6-4 6-2 6-2,R128,110.00,us open - 2024,2024
781,USA,Ben Shelton,20240826,210097,21.80,6-3 6-4 6-4,R64,128.00,us open - 2024,2024

In [16]:
premios = pd.read_csv('melt premios tennis.csv')
premios

      year             tourney key round   premio €  torneo_id
0     2000          us open - 2000     W 2738611.89        NaN
1     2001          us open - 2001     W 2808172.64        NaN
2     2002          us open - 2002     W 2879500.22        NaN
3     2003          us open - 2003     W 2952639.53        NaN
4     2004          us open - 2004     W 3027636.57        NaN
...    ...                     ...   ...        ...        ...
1095  2020  australian open - 2020    Q1   31658.82        NaN
1096  2021  australian open - 2021    Q1   32462.96        NaN
1097  2022  australian open - 2022    Q1   33287.52        NaN
1098  2023  australian open - 2023    Q1   34133.02        NaN
1099  2024  australian open - 2024    Q1   35000.00        NaN

[1100 rows x 5 columns]

In [17]:
premios = premios.drop('torneo_id', axis='columns')

In [18]:
premios

      year             tourney key round   premio €
0     2000          us open - 2000     W 2738611.89
1     2001          us open - 2001     W 2808172.64
2     2002          us open - 2002     W 2879500.22
3     2003          us open - 2003     W 2952639.53
4     2004          us open - 2004     W 3027636.57
...    ...                     ...   ...        ...
1095  2020  australian open - 2020    Q1   31658.82
1096  2021  australian open - 2021    Q1   32462.96
1097  2022  australian open - 2022    Q1   33287.52
1098  2023  australian open - 2023    Q1   34133.02
1099  2024  australian open - 2024    Q1   35000.00

[1100 rows x 4 columns]

merge

In [159]:
df_players_top10_clean

,ioc,full_name,tourney_date,winner_id,winner_age,score,round,minutes,tourney key,year
0,GER,Alexander Zverev,20150629,100644,18.10,6-3 1-6 6-3 3-6 9-7,R128,NaN,wimbledon - 2015,2015
1,GER,Alexander Zverev,20160523,100644,19.00,5-7 6-2 7-6(6) 7-5,R128,188.00,roland garros - 2016,2016
2,GER,Alexander Zverev,20160523,100644,19.00,6-1 3-6 6-1 6-4,R64,129.00,roland garros - 2016,2016
3,GER,Alexander Zverev,20160627,100644,19.10,6-3 6-4 6-2,R128,96.00,wimbledon - 2016,2016
4,GER,Alexander Zverev,20160627,100644,19.10,6-4 3-6 6-0 4-6 6-2,R64,198.00,wimbledon - 2016,2016
...,...,...,...,...,...,...,...,...,...,...
777,USA,Ben Shelton,20240701,210097,21.70,4-6 6-3 3-6 6-3 6-4,R128,209.00,wimbledon - 2024,2024
778,USA,Ben Shelton,20240701,210097,21.70,4-6 7-6(5) 6-7(5) 6-3 7-6(7),R64,229.00,wimbledon - 2024,2024
779,USA,Ben Shelton,20240701,210097,21.70,6-7(4) 6-2 6-4 4-6 6-2,R32,185.00,wimbledon - 2024,2024
780,USA,Ben Shelton,20240826,210097,21.80,6-4 6-2 6-2,R128,110.00,us open - 2024,2024
781,USA,Ben Shelton,20240826,210097,21.80,6-3 6-4 6-4,R64,128.00,us open - 2024,2024

In [19]:
df_merge = pd.merge(df_players_top10_clean,premios,how='right',on='tourney key')
df_merge

,ioc,full_name,tourney_date,winner_id,winner_age,score,round_x,minutes,tourney key,year_x,year_y,round_y,premio €
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,us open - 2000,NaN,2000,W,2738611.89
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,us open - 2001,NaN,2001,W,2808172.64
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,us open - 2002,NaN,2002,W,2879500.22
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,us open - 2003,NaN,2003,W,2952639.53
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,us open - 2004,NaN,2004,W,3027636.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8850,ESP,Carlos Alcaraz,20240115.00,207989.00,20.60,6-1 6-1 1-0 RET,R32,66.00,australian open - 2024,2024.00,2024,Q1,35000.00
8851,ESP,Carlos Alcaraz,20240115.00,207989.00,20.60,6-4 6-4 6-0,R16,109.00,australian open - 2024,2024.00,2024,Q1,35000.00
8852,DEN,Holger Rune,20240115.00,208029.00,20.70,6-2 4-6 7-6(3) 6-4,R128,205.00,australian open - 2024,2024.00,2024,Q1,35000.00
8853,USA,Ben Shelton,20240115.00,210097.00,21.20,6-2 7-6(2) 7-5,R128,166.00,australian open - 2024,2024.00,2024,Q1,35000.00
8854,USA,Ben Shelton,20240115.00,210097.00,21.20,6-4 6-1 3-6 7-6(5),R64,171.00,australian open - 2024,2024.00,2024,Q1,35000.00

In [20]:
matches_ganadores = grand_slams[['tourney key','round','winner_id']]
matches_ganadores

                tourney key round  winner_id
2130   roland garros - 2000  R128     101736
2131   roland garros - 2000  R128     102344
2132   roland garros - 2000  R128     103181
2133   roland garros - 2000  R128     102644
2134   roland garros - 2000  R128     103454
...                     ...   ...        ...
74139        us open - 2024    QF     126203
74140        us open - 2024    QF     126207
74141        us open - 2024    SF     206173
74142        us open - 2024    SF     126203
74143        us open - 2024     F     206173

[12573 rows x 3 columns]

## <span style="color: rgb(230, 0, 126);">__________________________________________________________________________________________________________________</span>
## <span style="color: rgb(230, 0, 126);">__________________________________________________________________________________________________________________</span>

In [21]:
df_ganadores = grand_slams.merge(
    df_merge,
    left_on=['tourney key', 'winner_id', 'round'],
    right_on=['tourney key', 'winner_id', 'round_y'],
    how='inner'
)
df_ganadores= df_ganadores.drop_duplicates(subset=['full_name', 'tourney_name', 'year_y', 'round_y'])

In [22]:
premios_por_ronda = (df_ganadores.groupby(['full_name','tourney_name','year_y', 'round_y'])['premio €'].sum()).reset_index(name='total_premio').sort_values(['full_name', 'total_premio'], ascending=[True, False])
premios_por_ronda

          full_name     tourney_name  year_y round_y  total_premio
36   Alex De Minaur          us open    2024     R16     400000.00
27   Alex De Minaur          us open    2020     R16     361815.14
12   Alex De Minaur  australian open    2024     R32     290000.00
9    Alex De Minaur  australian open    2023     R32     282816.46
6    Alex De Minaur  australian open    2022     R32     275810.87
..              ...              ...     ...     ...           ...
777    Taylor Fritz        wimbledon    2023    R128      64365.13
773    Taylor Fritz        wimbledon    2022    R128      62770.75
771    Taylor Fritz        wimbledon    2021    R128      61215.87
770    Taylor Fritz        wimbledon    2019    R128      58220.69
769    Taylor Fritz        wimbledon    2018    R128      56778.52

[782 rows x 5 columns]

In [23]:
premios_por_ronda.to_excel('premios_ronda.xlsx',index=False)

## <span style="color: rgb(230, 0, 126);">__________________________________________________________________________________________________________________</span>
## <span style="color: rgb(230, 0, 126);">__________________________________________________________________________________________________________________</span>

In [24]:
ganadores_finales = grand_slams[grand_slams['round'] == 'F'][['tourney_name', 'year', 'winner_id']]
ganadores_finales

          tourney_name  year  winner_id
2256     roland garros  2000     102856
2383         wimbledon  2000     101948
2510           us open  2000     103498
2699   australian open  2000     101736
5634     roland garros  2001     102856
...                ...   ...        ...
71116          us open  2023     104925
72093  australian open  2024     206173
73132    roland garros  2024     207989
73555        wimbledon  2024     207989
74143          us open  2024     206173

[99 rows x 3 columns]

In [25]:
premios_campeones = df_ganadores.merge(
    ganadores_finales,
    left_on=['tourney_name', 'year', 'winner_id'],  # tus columnas
    right_on=['tourney_name', 'year', 'winner_id'],
    how='inner'
)
premios_campeones

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date_x,match_num,winner_id,winner_seed,winner_entry,...,full_name,tourney_date_y,winner_age_y,score_y,round_x,minutes_y,year_x,year_y,round_y,premio €
0,2008-580,australian open,Hard,128,G,20080114,17,104925,3.00,NaN,...,Novak Djokovic,20080114.00,20.60,6-0 6-2 7-6(5),R128,120.00,2008.00,2008,R128,88365.13
1,2008-580,australian open,Hard,128,G,20080114,73,104925,3.00,NaN,...,Novak Djokovic,20080114.00,20.60,6-0 6-2 7-6(5),R128,120.00,2008.00,2008,R64,133886.56
2,2008-580,australian open,Hard,128,G,20080114,101,104925,3.00,NaN,...,Novak Djokovic,20080114.00,20.60,6-0 6-2 7-6(5),R128,120.00,2008.00,2008,R32,194135.51
3,2008-580,australian open,Hard,128,G,20080114,115,104925,3.00,NaN,...,Novak Djokovic,20080114.00,20.60,6-0 6-2 7-6(5),R128,120.00,2008.00,2008,R16,281161.78
4,2008-580,australian open,Hard,128,G,20080114,122,104925,3.00,NaN,...,Novak Djokovic,20080114.00,20.60,6-0 6-2 7-6(5),R128,120.00,2008.00,2008,QF,445172.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,2024-560,us open,Hard,128,G,20240826,196,206173,1.00,NaN,...,Jannik Sinner,20240826.00,23.00,2-6 6-2 6-1 6-2,R128,144.00,2024.00,2024,R32,237000.00
206,2024-560,us open,Hard,128,G,20240826,212,206173,1.00,NaN,...,Jannik Sinner,20240826.00,23.00,2-6 6-2 6-1 6-2,R128,144.00,2024.00,2024,R16,400000.00
207,2024-560,us open,Hard,128,G,20240826,220,206173,1.00,NaN,...,Jannik Sinner,20240826.00,23.00,2-6 6-2 6-1 6-2,R128,144.00,2024.00,2024,QF,660000.00
208,2024-560,us open,Hard,128,G,20240826,224,206173,1.00,NaN,...,Jannik Sinner,20240826.00,23.00,2-6 6-2 6-1 6-2,R128,144.00,2024.00,2024,SF,1260000.00
209,2024-560,us open,Hard,128,G,20240826,226,206173,1.00,NaN,...,Jannik Sinner,20240826.00,23.00,2-6 6-2 6-1 6-2,R128,144.00,2024.00,2024,F,2500000.00

In [26]:
premios_campeones_clean = premios_campeones.drop_duplicates(subset=['full_name', 'tourney_name', 'year_y', 'round_y'])
premios_campeones_clean

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date_x,match_num,winner_id,winner_seed,winner_entry,...,full_name,tourney_date_y,winner_age_y,score_y,round_x,minutes_y,year_x,year_y,round_y,premio €
0,2008-580,australian open,Hard,128,G,20080114,17,104925,3.00,NaN,...,Novak Djokovic,20080114.00,20.60,6-0 6-2 7-6(5),R128,120.00,2008.00,2008,R128,88365.13
1,2008-580,australian open,Hard,128,G,20080114,73,104925,3.00,NaN,...,Novak Djokovic,20080114.00,20.60,6-0 6-2 7-6(5),R128,120.00,2008.00,2008,R64,133886.56
2,2008-580,australian open,Hard,128,G,20080114,101,104925,3.00,NaN,...,Novak Djokovic,20080114.00,20.60,6-0 6-2 7-6(5),R128,120.00,2008.00,2008,R32,194135.51
3,2008-580,australian open,Hard,128,G,20080114,115,104925,3.00,NaN,...,Novak Djokovic,20080114.00,20.60,6-0 6-2 7-6(5),R128,120.00,2008.00,2008,R16,281161.78
4,2008-580,australian open,Hard,128,G,20080114,122,104925,3.00,NaN,...,Novak Djokovic,20080114.00,20.60,6-0 6-2 7-6(5),R128,120.00,2008.00,2008,QF,445172.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,2024-560,us open,Hard,128,G,20240826,196,206173,1.00,NaN,...,Jannik Sinner,20240826.00,23.00,2-6 6-2 6-1 6-2,R128,144.00,2024.00,2024,R32,237000.00
206,2024-560,us open,Hard,128,G,20240826,212,206173,1.00,NaN,...,Jannik Sinner,20240826.00,23.00,2-6 6-2 6-1 6-2,R128,144.00,2024.00,2024,R16,400000.00
207,2024-560,us open,Hard,128,G,20240826,220,206173,1.00,NaN,...,Jannik Sinner,20240826.00,23.00,2-6 6-2 6-1 6-2,R128,144.00,2024.00,2024,QF,660000.00
208,2024-560,us open,Hard,128,G,20240826,224,206173,1.00,NaN,...,Jannik Sinner,20240826.00,23.00,2-6 6-2 6-1 6-2,R128,144.00,2024.00,2024,SF,1260000.00
209,2024-560,us open,Hard,128,G,20240826,226,206173,1.00,NaN,...,Jannik Sinner,20240826.00,23.00,2-6 6-2 6-1 6-2,R128,144.00,2024.00,2024,F,2500000.00

In [27]:
premios_campeones_clean = (
    premios_campeones_clean
    .groupby(['full_name', 'tourney_name', 'year_y'])['premio €']
    .sum()
    .reset_index(name='total_premio')
    .sort_values(['full_name', 'total_premio'], ascending=[True, False])
)

premios_campeones_clean

         full_name     tourney_name  year_y  total_premio
1   Carlos Alcaraz          us open    2022    5060653.85
3   Carlos Alcaraz        wimbledon    2024    3252000.00
2   Carlos Alcaraz        wimbledon    2023    3171445.29
0   Carlos Alcaraz    roland garros    2024    3033000.00
5    Jannik Sinner          us open    2024    5321000.00
4    Jannik Sinner  australian open    2024    4707000.00
22  Novak Djokovic          us open    2023    5189194.46
15  Novak Djokovic  australian open    2023    4590403.74
21  Novak Djokovic          us open    2018    4577552.99
14  Novak Djokovic  australian open    2021    4365804.25
13  Novak Djokovic  australian open    2020    4257659.69
20  Novak Djokovic          us open    2015    4245740.45
12  Novak Djokovic  australian open    2019    4152193.96
11  Novak Djokovic  australian open    2016    3851214.37
19  Novak Djokovic          us open    2011    3840432.96
10  Novak Djokovic  australian open    2015    3755816.63
9   Novak Djokovic  australian open    2013    3572051.85
8   Novak Djokovic  australian open    2012    3483569.19
7   Novak Djokovic  australian open    2011    3397278.32
6   Novak Djokovic  australian open    2008    3151020.21
29  Novak Djokovic        wimbledon    2022    3092885.99
28  Novak Djokovic        wimbledon    2021    3016272.66
18  Novak Djokovic    roland garros    2023    2957870.10
27  Novak Djokovic        wimbledon    2019    2868692.32
17  Novak Djokovic    roland garros    2021    2813147.29
26  Novak Djokovic        wimbledon    2018    2797632.46
25  Novak Djokovic        wimbledon    2015    2594840.81
24  Novak Djokovic        wimbledon    2014    2530564.47
16  Novak Djokovic    roland garros    2016    2481566.43
23  Novak Djokovic        wimbledon    2011    2347131.74

In [28]:
alcaraz_torneo = premios_campeones_clean[premios_campeones_clean['full_name'] == 'Carlos Alcaraz']
alcaraz_torneo

        full_name   tourney_name  year_y  total_premio
1  Carlos Alcaraz        us open    2022    5060653.85
3  Carlos Alcaraz      wimbledon    2024    3252000.00
2  Carlos Alcaraz      wimbledon    2023    3171445.29
0  Carlos Alcaraz  roland garros    2024    3033000.00

In [29]:
alcaraz_torneo.to_excel('alcaraz_torneo.xlsx',index=False)

In [30]:
sinner_torneo = premios_campeones_clean[premios_campeones_clean['full_name'] == 'Jannik Sinner']
sinner_torneo.to_csv('sinner_premio_torneos_ganados.csv')

In [31]:
novak = premios_campeones_clean[premios_campeones_clean['full_name'] == 'Novak Djokovic']
novak.to_excel('novak_torneos.xlsx',index=False)

In [32]:
novak.to_csv('novak_premio_torneos_ganados.csv',index=False)

## <span style="color: rgb(230, 0, 126);">__________________________________________________________________________________________________________________</span>
## <span style="color: rgb(230, 0, 126);">__________________________________________________________________________________________________________________</span>

torneos

In [33]:
import pandas as pd

In [34]:
tourneys = pd.merge(grand_slams,players,how='inner',left_on='winner_id',right_on='player_id')
tourneys

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,tourney key,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
0,2000-520,roland garros,Clay,128,G,20000529,1,101736,1.00,NaN,...,roland garros - 2000,101736,Andre,Agassi,R,19700429.00,USA,180.00,Q7407,Andre Agassi
1,2000-520,roland garros,Clay,128,G,20000529,2,102344,NaN,NaN,...,roland garros - 2000,102344,Karol,Kucera,R,19740304.00,SVK,188.00,Q460621,Karol Kucera
2,2000-520,roland garros,Clay,128,G,20000529,3,103181,NaN,NaN,...,roland garros - 2000,103181,Jiri,Vanek,R,19780424.00,CZE,185.00,Q246293,Jiri Vanek
3,2000-520,roland garros,Clay,128,G,20000529,4,102644,NaN,NaN,...,roland garros - 2000,102644,Franco,Squillari,L,19750822.00,ARG,183.00,Q730200,Franco Squillari
4,2000-520,roland garros,Clay,128,G,20000529,5,103454,NaN,NaN,...,roland garros - 2000,103454,Nicolas,Massu,R,19791010.00,CHI,183.00,Q295858,Nicolas Massu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12568,2024-560,us open,Hard,128,G,20240826,222,126203,12.00,NaN,...,us open - 2024,126203,Taylor,Fritz,R,19971028.00,USA,196.00,Q17660516,Taylor Fritz
12569,2024-560,us open,Hard,128,G,20240826,223,126207,20.00,NaN,...,us open - 2024,126207,Frances,Tiafoe,R,19980120.00,USA,188.00,Q17305299,Frances Tiafoe
12570,2024-560,us open,Hard,128,G,20240826,224,206173,1.00,NaN,...,us open - 2024,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner
12571,2024-560,us open,Hard,128,G,20240826,225,126203,12.00,NaN,...,us open - 2024,126203,Taylor,Fritz,R,19971028.00,USA,196.00,Q17660516,Taylor Fritz
12572,2024-560,us open,Hard,128,G,20240826,226,206173,1.00,NaN,...,us open - 2024,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner

RG

In [35]:
roland_garros = tourneys[tourneys['tourney_name'] == 'roland garros']
roland_garros

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,tourney key,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
0,2000-520,roland garros,Clay,128,G,20000529,1,101736,1.00,NaN,...,roland garros - 2000,101736,Andre,Agassi,R,19700429.00,USA,180.00,Q7407,Andre Agassi
1,2000-520,roland garros,Clay,128,G,20000529,2,102344,NaN,NaN,...,roland garros - 2000,102344,Karol,Kucera,R,19740304.00,SVK,188.00,Q460621,Karol Kucera
2,2000-520,roland garros,Clay,128,G,20000529,3,103181,NaN,NaN,...,roland garros - 2000,103181,Jiri,Vanek,R,19780424.00,CZE,185.00,Q246293,Jiri Vanek
3,2000-520,roland garros,Clay,128,G,20000529,4,102644,NaN,NaN,...,roland garros - 2000,102644,Franco,Squillari,L,19750822.00,ARG,183.00,Q730200,Franco Squillari
4,2000-520,roland garros,Clay,128,G,20000529,5,103454,NaN,NaN,...,roland garros - 2000,103454,Nicolas,Massu,R,19791010.00,CHI,183.00,Q295858,Nicolas Massu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12314,2024-520,roland garros,Clay,128,G,20240527,279,207686,NaN,NaN,...,roland garros - 2024,207686,Alexander,Shevchenko,R,20001129.00,KAZ,185.00,NaN,Alexander Shevchenko
12315,2024-520,roland garros,Clay,128,G,20240527,278,202260,NaN,Q,...,roland garros - 2024,202260,Henri,Squire,R,20000927.00,GER,196.00,NaN,Henri Squire
12316,2024-520,roland garros,Clay,128,G,20240527,277,105526,NaN,NaN,...,roland garros - 2024,105526,Jan Lennard,Struff,R,19900425.00,GER,193.00,Q1681537,Jan Lennard Struff
12317,2024-520,roland garros,Clay,128,G,20240527,276,104527,NaN,NaN,...,roland garros - 2024,104527,Stan,Wawrinka,R,19850328.00,SUI,183.00,Q193661,Stan Wawrinka
12318,2024-520,roland garros,Clay,128,G,20240527,275,111190,NaN,NaN,...,roland garros - 2024,111190,Zhizhen,Zhang,R,19961016.00,CHN,193.00,Q21623382,Zhizhen Zhang

In [36]:
winners_RG = roland_garros[roland_garros['round'] == 'F']
winners_RG

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,tourney key,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
126,2000-520,roland garros,Clay,128,G,20000529,127,102856,5.00,NaN,...,roland garros - 2000,102856,Gustavo,Kuerten,R,19760910.00,BRA,190.00,Q190723,Gustavo Kuerten
634,2001-520,roland garros,Clay,128,G,20010528,127,102856,1.00,NaN,...,roland garros - 2001,102856,Gustavo,Kuerten,R,19760910.00,BRA,190.00,Q190723,Gustavo Kuerten
1142,2002-520,roland garros,Clay,128,G,20020527,127,102610,20.00,NaN,...,roland garros - 2002,102610,Albert,Costa,R,19750625.00,ESP,180.00,Q317828,Albert Costa
1650,2003-520,roland garros,Clay,128,G,20030526,127,103507,3.00,NaN,...,roland garros - 2003,103507,Juan Carlos,Ferrero,R,19800212.00,ESP,183.00,Q185722,Juan Carlos Ferrero
2158,2004-520,roland garros,Clay,128,G,20040524,127,103292,NaN,NaN,...,roland garros - 2004,103292,Gaston,Gaudio,R,19781209.00,ARG,175.00,Q299960,Gaston Gaudio
2666,2005-520,roland garros,Clay,128,G,20050523,127,104745,4.00,NaN,...,roland garros - 2005,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
3174,2006-520,roland garros,Clay,128,G,20060529,127,104745,2.00,NaN,...,roland garros - 2006,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
3682,2007-520,roland garros,Clay,128,G,20070528,127,104745,2.00,NaN,...,roland garros - 2007,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
4190,2008-520,roland garros,Clay,128,G,20080525,127,104745,2.00,NaN,...,roland garros - 2008,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
4698,2009-520,roland garros,Clay,128,G,20090525,127,103819,2.00,NaN,...,roland garros - 2009,103819,Roger,Federer,R,19810808.00,SUI,185.00,Q1426,Roger Federer
5333,2010-520,roland garros,Clay,128,G,20100524,127,104745,2.00,NaN,...,roland garros - 2010,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
5841,2011-520,roland garros,Clay,128,G,20110522,127,104745,1.00,NaN,...,roland garros - 2011,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
6349,2012-520,roland garros,Clay,128,G,20120527,127,104745,2.00,NaN,...,roland garros - 2012,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
6857,2013-520,roland garros,Clay,128,G,20130527,127,104745,3.00,NaN,...,roland garros - 2013,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
7365,2014-520,roland garros,Clay,128,G,20140526,127,104745,1.00,NaN,...,roland garros - 2014,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
7873,2015-520,roland garros,Clay,128,G,20150524,127,104527,8.00,NaN,...,roland garros - 2015,104527,Stan,Wawrinka,R,19850328.00,SUI,183.00,Q193661,Stan Wawrinka
8381,2016-520,roland garros,Clay,128,G,20160523,226,104925,1.00,NaN,...,roland garros - 2016,104925,Novak,Djokovic,R,19870522.00,SRB,188.00,Q5812,Novak Djokovic
8889,2017-520,roland garros,Clay,128,G,20170529,226,104745,4.00,NaN,...,roland garros - 2017,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
9397,2018-520,roland garros,Clay,128,G,20180528,226,104745,1.00,NaN,...,roland garros - 2018,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
9905,2019-520,roland garros,Clay,128,G,20190527,1701,104745,2.00,NaN,...,roland garros - 2019,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
10540,2020-520,roland garros,Clay,128,G,20200928,1701,104745,1.00,NaN,...,roland garros - 2020,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
10667,2021-520,roland garros,Clay,128,G,20210531,226,104925,1.00,NaN,...,roland garros - 2021,104925,Novak,Djokovic,R,19870522.00,SRB,188.00,Q5812,Novak Djokovic
11302,2022-520,roland garros,Clay,128,G,20220523,226,104745,5.00,NaN,...,roland garros - 2022,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
11810,2023-520,roland garros,Clay,128,G,20230529,226,104925,3.00,NaN,...,roland garros - 2023,104925,Novak,Djokovic,R,19870522.00,SRB,188.00,Q5812,Novak Djokovic
12192,2024-520,roland garros,Clay,128,G,20240527,401,207989,3.00,NaN,...,roland garros - 2024,207989,Carlos,Alcaraz,R,20030505.00,ESP,183.00,Q85518537,Carlos Alcaraz

In [37]:
winners_RGww2 = winners_RG.groupby(['winner_id','full_name'])[['player_id']].count()
winners_RGww2

                               player_id
winner_id full_name
102610    Albert Costa                 1
102856    Gustavo Kuerten              2
103292    Gaston Gaudio                1
103507    Juan Carlos Ferrero          1
103819    Roger Federer                1
104527    Stan Wawrinka                1
104745    Rafael Nadal                14
104925    Novak Djokovic               3
207989    Carlos Alcaraz               1

In [38]:
winners_RGww = winners_RG.groupby(['player_id', 'full_name'])['tourney_id'].count().reset_index(name='total_ganados').sort_values(by= 'total_ganados',ascending=False)
winners_RGww.to_csv('winners_RG.csv',index=False)

WIMBL

In [39]:
wimbledon = tourneys[tourneys['tourney_name'] == 'wimbledon']
wimbledon

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,tourney key,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
127,2000-540,wimbledon,Grass,128,G,20000626,1,101948,1.00,NaN,...,wimbledon - 2000,101948,Pete,Sampras,R,19710812.00,USA,185.00,Q9446,Pete Sampras
128,2000-540,wimbledon,Grass,128,G,20000626,2,102344,NaN,NaN,...,wimbledon - 2000,102344,Karol,Kucera,R,19740304.00,SVK,188.00,Q460621,Karol Kucera
129,2000-540,wimbledon,Grass,128,G,20000626,3,103566,NaN,Q,...,wimbledon - 2000,103566,Michael,Llodra,L,19800518.00,FRA,190.00,Q295488,Michael Llodra
130,2000-540,wimbledon,Grass,128,G,20000626,4,102925,NaN,NaN,...,wimbledon - 2000,102925,Justin,Gimelstob,R,19770126.00,USA,196.00,Q282698,Justin Gimelstob
131,2000-540,wimbledon,Grass,128,G,20000626,5,103252,NaN,NaN,...,wimbledon - 2000,103252,Alberto,Martin,R,19780820.00,ESP,175.00,Q457047,Alberto Martin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12441,2024-540,wimbledon,Grass,128,G,20240701,222,207518,25.00,NaN,...,wimbledon - 2024,207518,Lorenzo,Musetti,R,20020303.00,ITA,185.00,Q54813043,Lorenzo Musetti
12442,2024-540,wimbledon,Grass,128,G,20240701,223,104925,2.00,NaN,...,wimbledon - 2024,104925,Novak,Djokovic,R,19870522.00,SRB,188.00,Q5812,Novak Djokovic
12443,2024-540,wimbledon,Grass,128,G,20240701,224,207989,3.00,NaN,...,wimbledon - 2024,207989,Carlos,Alcaraz,R,20030505.00,ESP,183.00,Q85518537,Carlos Alcaraz
12444,2024-540,wimbledon,Grass,128,G,20240701,225,104925,2.00,NaN,...,wimbledon - 2024,104925,Novak,Djokovic,R,19870522.00,SRB,188.00,Q5812,Novak Djokovic
12445,2024-540,wimbledon,Grass,128,G,20240701,226,207989,3.00,NaN,...,wimbledon - 2024,207989,Carlos,Alcaraz,R,20030505.00,ESP,183.00,Q85518537,Carlos Alcaraz

In [40]:
winners_WIMB = wimbledon[wimbledon['round'] == 'F']
winners_WIMB

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,tourney key,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
253,2000-540,wimbledon,Grass,128,G,20000626,127,101948,1.00,NaN,...,wimbledon - 2000,101948,Pete,Sampras,R,19710812.00,USA,185.00,Q9446,Pete Sampras
761,2001-540,wimbledon,Grass,128,G,20010625,127,101964,NaN,WC,...,wimbledon - 2001,101964,Goran,Ivanisevic,L,19710913.00,CRO,193.00,Q204279,Goran Ivanisevic
1269,2002-540,wimbledon,Grass,128,G,20020624,127,103720,1.00,NaN,...,wimbledon - 2002,103720,Lleyton,Hewitt,R,19810224.00,AUS,180.00,Q180104,Lleyton Hewitt
1777,2003-540,wimbledon,Grass,128,G,20030623,127,103819,4.00,NaN,...,wimbledon - 2003,103819,Roger,Federer,R,19810808.00,SUI,185.00,Q1426,Roger Federer
2285,2004-540,wimbledon,Grass,128,G,20040621,127,103819,1.00,NaN,...,wimbledon - 2004,103819,Roger,Federer,R,19810808.00,SUI,185.00,Q1426,Roger Federer
2793,2005-540,wimbledon,Grass,128,G,20050620,127,103819,1.00,NaN,...,wimbledon - 2005,103819,Roger,Federer,R,19810808.00,SUI,185.00,Q1426,Roger Federer
3301,2006-540,wimbledon,Grass,128,G,20060626,127,103819,1.00,NaN,...,wimbledon - 2006,103819,Roger,Federer,R,19810808.00,SUI,185.00,Q1426,Roger Federer
3809,2007-540,wimbledon,Grass,128,G,20070625,127,103819,1.00,NaN,...,wimbledon - 2007,103819,Roger,Federer,R,19810808.00,SUI,185.00,Q1426,Roger Federer
4317,2008-540,wimbledon,Grass,128,G,20080623,127,104745,2.00,NaN,...,wimbledon - 2008,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
4825,2009-540,wimbledon,Grass,128,G,20090622,127,103819,2.00,NaN,...,wimbledon - 2009,103819,Roger,Federer,R,19810808.00,SUI,185.00,Q1426,Roger Federer
5460,2010-540,wimbledon,Grass,128,G,20100621,127,104745,2.00,NaN,...,wimbledon - 2010,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
5968,2011-540,wimbledon,Grass,128,G,20110620,127,104925,2.00,NaN,...,wimbledon - 2011,104925,Novak,Djokovic,R,19870522.00,SRB,188.00,Q5812,Novak Djokovic
6476,2012-540,wimbledon,Grass,128,G,20120625,127,103819,3.00,NaN,...,wimbledon - 2012,103819,Roger,Federer,R,19810808.00,SUI,185.00,Q1426,Roger Federer
6984,2013-540,wimbledon,Grass,128,G,20130624,127,104918,2.00,NaN,...,wimbledon - 2013,104918,Andy,Murray,R,19870515.00,GBR,191.00,Q10125,Andy Murray
7492,2014-540,wimbledon,Grass,128,G,20140623,127,104925,1.00,NaN,...,wimbledon - 2014,104925,Novak,Djokovic,R,19870522.00,SRB,188.00,Q5812,Novak Djokovic
8000,2015-540,wimbledon,Grass,128,G,20150629,127,104925,1.00,NaN,...,wimbledon - 2015,104925,Novak,Djokovic,R,19870522.00,SRB,188.00,Q5812,Novak Djokovic
8508,2016-540,wimbledon,Grass,128,G,20160627,226,104918,2.00,NaN,...,wimbledon - 2016,104918,Andy,Murray,R,19870515.00,GBR,191.00,Q10125,Andy Murray
9016,2017-540,wimbledon,Grass,128,G,20170703,226,103819,3.00,NaN,...,wimbledon - 2017,103819,Roger,Federer,R,19810808.00,SUI,185.00,Q1426,Roger Federer
9524,2018-540,wimbledon,Grass,128,G,20180702,226,104925,12.00,NaN,...,wimbledon - 2018,104925,Novak,Djokovic,R,19870522.00,SRB,188.00,Q5812,Novak Djokovic
10032,2019-540,wimbledon,Grass,128,G,20190701,226,104925,1.00,NaN,...,wimbledon - 2019,104925,Novak,Djokovic,R,19870522.00,SRB,188.00,Q5812,Novak Djokovic
10794,2021-540,wimbledon,Grass,128,G,20210628,226,104925,1.00,NaN,...,wimbledon - 2021,104925,Novak,Djokovic,R,19870522.00,SRB,188.00,Q5812,Novak Djokovic
11429,2022-540,wimbledon,Grass,128,G,20220627,226,104925,1.00,NaN,...,wimbledon - 2022,104925,Novak,Djokovic,R,19870522.00,SRB,188.00,Q5812,Novak Djokovic
11937,2023-540,wimbledon,Grass,128,G,20230703,226,207989,1.00,NaN,...,wimbledon - 2023,207989,Carlos,Alcaraz,R,20030505.00,ESP,183.00,Q85518537,Carlos Alcaraz
12445,2024-540,wimbledon,Grass,128,G,20240701,226,207989,3.00,NaN,...,wimbledon - 2024,207989,Carlos,Alcaraz,R,20030505.00,ESP,183.00,Q85518537,Carlos Alcaraz

In [41]:
winnTourney_WIMB = winners_WIMB.groupby(['winner_id','full_name'])['tourney_id'].count().reset_index(name='total_ganados')
winnTourney_WIMB

   winner_id         full_name  total_ganados
0     101948      Pete Sampras              1
1     101964  Goran Ivanisevic              1
2     103720    Lleyton Hewitt              1
3     103819     Roger Federer              8
4     104745      Rafael Nadal              2
5     104918       Andy Murray              2
6     104925    Novak Djokovic              7
7     207989    Carlos Alcaraz              2

In [42]:
winnTourney_WIMB.to_csv('winners_Wimbl.csv',index=False)

US OPEN

In [43]:
us_open = tourneys[tourneys['tourney_name'] == 'us open']
us_open

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,tourney key,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
254,2000-560,us open,Hard,128,G,20000828,1,101736,1.00,NaN,...,us open - 2000,101736,Andre,Agassi,R,19700429.00,USA,180.00,Q7407,Andre Agassi
255,2000-560,us open,Hard,128,G,20000828,2,103096,NaN,NaN,...,us open - 2000,103096,Arnaud,Clement,R,19771217.00,FRA,173.00,Q299944,Arnaud Clement
256,2000-560,us open,Hard,128,G,20000828,3,102271,NaN,NaN,...,us open - 2000,102271,Hicham,Arazi,L,19731019.00,MAR,175.00,Q383612,Hicham Arazi
257,2000-560,us open,Hard,128,G,20000828,4,101965,NaN,NaN,...,us open - 2000,101965,Wayne,Ferreira,R,19710915.00,RSA,185.00,Q369228,Wayne Ferreira
258,2000-560,us open,Hard,128,G,20000828,5,103324,NaN,NaN,...,us open - 2000,103324,Arnaud,Di Pasquale,R,19790211.00,FRA,185.00,Q552507,Arnaud Di Pasquale
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12568,2024-560,us open,Hard,128,G,20240826,222,126203,12.00,NaN,...,us open - 2024,126203,Taylor,Fritz,R,19971028.00,USA,196.00,Q17660516,Taylor Fritz
12569,2024-560,us open,Hard,128,G,20240826,223,126207,20.00,NaN,...,us open - 2024,126207,Frances,Tiafoe,R,19980120.00,USA,188.00,Q17305299,Frances Tiafoe
12570,2024-560,us open,Hard,128,G,20240826,224,206173,1.00,NaN,...,us open - 2024,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner
12571,2024-560,us open,Hard,128,G,20240826,225,126203,12.00,NaN,...,us open - 2024,126203,Taylor,Fritz,R,19971028.00,USA,196.00,Q17660516,Taylor Fritz
12572,2024-560,us open,Hard,128,G,20240826,226,206173,1.00,NaN,...,us open - 2024,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner

In [44]:
winners_US = us_open[us_open['round'] == 'F']
winners_US

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,tourney key,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
380,2000-560,us open,Hard,128,G,20000828,127,103498,6.00,NaN,...,us open - 2000,103498,Marat,Safin,R,19800127.00,RUS,193.00,Q133318,Marat Safin
888,2001-560,us open,Hard,128,G,20010827,127,103720,4.00,NaN,...,us open - 2001,103720,Lleyton,Hewitt,R,19810224.00,AUS,180.00,Q180104,Lleyton Hewitt
1396,2002-560,us open,Hard,128,G,20020826,127,101948,17.00,NaN,...,us open - 2002,101948,Pete,Sampras,R,19710812.00,USA,185.00,Q9446,Pete Sampras
1904,2003-560,us open,Hard,128,G,20030825,127,104053,4.00,NaN,...,us open - 2003,104053,Andy,Roddick,R,19820830.00,USA,188.00,Q54584,Andy Roddick
2412,2004-560,us open,Hard,128,G,20040830,127,103819,1.00,NaN,...,us open - 2004,103819,Roger,Federer,R,19810808.00,SUI,185.00,Q1426,Roger Federer
2920,2005-560,us open,Hard,128,G,20050829,127,103819,1.00,NaN,...,us open - 2005,103819,Roger,Federer,R,19810808.00,SUI,185.00,Q1426,Roger Federer
3428,2006-560,us open,Hard,128,G,20060828,127,103819,1.00,NaN,...,us open - 2006,103819,Roger,Federer,R,19810808.00,SUI,185.00,Q1426,Roger Federer
3936,2007-560,us open,Hard,128,G,20070827,127,103819,1.00,NaN,...,us open - 2007,103819,Roger,Federer,R,19810808.00,SUI,185.00,Q1426,Roger Federer
4444,2008-560,us open,Hard,128,G,20080825,127,103819,2.00,NaN,...,us open - 2008,103819,Roger,Federer,R,19810808.00,SUI,185.00,Q1426,Roger Federer
4952,2009-560,us open,Hard,128,G,20090831,127,105223,6.00,NaN,...,us open - 2009,105223,Juan Martin,del Potro,R,19880923.00,ARG,198.00,Q180535,Juan Martin del Potro
5587,2010-560,us open,Hard,128,G,20100830,127,104745,1.00,NaN,...,us open - 2010,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
6095,2011-560,us open,Hard,128,G,20110829,127,104925,1.00,NaN,...,us open - 2011,104925,Novak,Djokovic,R,19870522.00,SRB,188.00,Q5812,Novak Djokovic
6603,2012-560,us open,Hard,128,G,20120827,127,104918,3.00,NaN,...,us open - 2012,104918,Andy,Murray,R,19870515.00,GBR,191.00,Q10125,Andy Murray
7111,2013-560,us open,Hard,128,G,20130826,127,104745,2.00,NaN,...,us open - 2013,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
7619,2014-560,us open,Hard,128,G,20140825,127,105227,14.00,NaN,...,us open - 2014,105227,Marin,Cilic,R,19880928.00,CRO,198.00,Q245241,Marin Cilic
8127,2015-560,us open,Hard,128,G,20150831,127,104925,1.00,NaN,...,us open - 2015,104925,Novak,Djokovic,R,19870522.00,SRB,188.00,Q5812,Novak Djokovic
8635,2016-560,us open,Hard,128,G,20160829,226,104527,3.00,NaN,...,us open - 2016,104527,Stan,Wawrinka,R,19850328.00,SUI,183.00,Q193661,Stan Wawrinka
9143,2017-560,us open,Hard,128,G,20170828,226,104745,1.00,NaN,...,us open - 2017,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
9651,2018-560,us open,Hard,128,G,20180827,226,104925,6.00,NaN,...,us open - 2018,104925,Novak,Djokovic,R,19870522.00,SRB,188.00,Q5812,Novak Djokovic
10159,2019-560,us open,Hard,128,G,20190826,226,104745,2.00,NaN,...,us open - 2019,104745,Rafael,Nadal,L,19860603.00,ESP,185.00,Q10132,Rafael Nadal
10413,2020-560,us open,Hard,128,G,20200831,226,106233,2.00,NaN,...,us open - 2020,106233,Dominic,Thiem,R,19930903.00,AUT,185.00,Q88762,Dominic Thiem
10921,2021-560,us open,Hard,128,G,20210830,226,106421,2.00,NaN,...,us open - 2021,106421,Daniil,Medvedev,R,19960211.00,RUS,198.00,Q21622022,Daniil Medvedev
11556,2022-560,us open,Hard,128,G,20220829,226,207989,3.00,NaN,...,us open - 2022,207989,Carlos,Alcaraz,R,20030505.00,ESP,183.00,Q85518537,Carlos Alcaraz
12064,2023-560,us open,Hard,128,G,20230828,226,104925,2.00,NaN,...,us open - 2023,104925,Novak,Djokovic,R,19870522.00,SRB,188.00,Q5812,Novak Djokovic
12572,2024-560,us open,Hard,128,G,20240826,226,206173,1.00,NaN,...,us open - 2024,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner

In [45]:
winTourney_USOPEN = winners_US.groupby(['winner_id','full_name'])['tourney_id'].count().reset_index(name='torneos_ganados')
winTourney_USOPEN

    winner_id              full_name  torneos_ganados
0      101948           Pete Sampras                1
1      103498            Marat Safin                1
2      103720         Lleyton Hewitt                1
3      103819          Roger Federer                5
4      104053           Andy Roddick                1
5      104527          Stan Wawrinka                1
6      104745           Rafael Nadal                4
7      104918            Andy Murray                1
8      104925         Novak Djokovic                4
9      105223  Juan Martin del Potro                1
10     105227            Marin Cilic                1
11     106233          Dominic Thiem                1
12     106421        Daniil Medvedev                1
13     206173          Jannik Sinner                1
14     207989         Carlos Alcaraz                1

In [46]:
winTourney_USOPEN.to_csv('winners_US.csv',index=False)

AUSTRALIAN OPEN

In [47]:
australian_open = tourneys[tourneys['tourney_name'] == 'australian open']
australian_open

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,tourney key,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
381,2000-580,australian open,Hard,128,G,20000117,1,101736,1.00,NaN,...,australian open - 2000,101736,Andre,Agassi,R,19700429.00,USA,180.00,Q7407,Andre Agassi
382,2000-580,australian open,Hard,128,G,20000117,2,102854,NaN,NaN,...,australian open - 2000,102854,Sjeng,Schalken,R,19760908.00,NED,193.00,Q469324,Sjeng Schalken
383,2000-580,australian open,Hard,128,G,20000117,3,103151,NaN,NaN,...,australian open - 2000,103151,Mariano,Zabaleta,R,19780228.00,ARG,183.00,Q448278,Mariano Zabaleta
384,2000-580,australian open,Hard,128,G,20000117,4,101889,NaN,WC,...,australian open - 2000,101889,Todd,Woodbridge,R,19710402.00,AUS,178.00,Q335312,Todd Woodbridge
385,2000-580,australian open,Hard,128,G,20000117,5,102776,NaN,NaN,...,australian open - 2000,102776,Andrew,Ilie,R,19760418.00,AUS,180.00,Q505283,Andrew Ilie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12187,2024-580,australian open,Hard,128,G,20240115,222,106421,3.00,NaN,...,australian open - 2024,106421,Daniil,Medvedev,R,19960211.00,RUS,198.00,Q21622022,Daniil Medvedev
12188,2024-580,australian open,Hard,128,G,20240115,223,100644,6.00,NaN,...,australian open - 2024,100644,Alexander,Zverev,R,19970420.00,GER,198.00,Q13990552,Alexander Zverev
12189,2024-580,australian open,Hard,128,G,20240115,224,206173,4.00,NaN,...,australian open - 2024,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner
12190,2024-580,australian open,Hard,128,G,20240115,225,106421,3.00,NaN,...,australian open - 2024,106421,Daniil,Medvedev,R,19960211.00,RUS,198.00,Q21622022,Daniil Medvedev
12191,2024-580,australian open,Hard,128,G,20240115,226,206173,4.00,NaN,...,australian open - 2024,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner

In [48]:
winners_AUS = australian_open[australian_open['round'] == 'F']

In [49]:
winTourney_AUS = winners_AUS.groupby(['winner_id','full_name'])['tourney_id'].count().reset_index(name='torneo_ganados')
winTourney_AUS

   winner_id         full_name  torneo_ganados
0     101736      Andre Agassi               3
1     102563  Thomas Johansson               1
2     103498       Marat Safin               1
3     103819     Roger Federer               6
4     104527     Stan Wawrinka               1
5     104745      Rafael Nadal               2
6     104925    Novak Djokovic              10
7     206173     Jannik Sinner               1

In [50]:
winTourney_AUS.to_csv('winners_AUS.csv',index=False)

STATS

In [51]:
players.head()

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
0,100001,Gardnar,Mulloy,R,19131122.00,USA,185.00,Q54544,Gardnar Mulloy
1,100002,Pancho,Segura,R,19210620.00,ECU,168.00,Q54581,Pancho Segura
2,100003,Frank,Sedgman,R,19271002.00,AUS,180.00,Q962049,Frank Sedgman
3,100004,Giuseppe,Merlo,R,19271011.00,ITA,NaN,Q1258752,Giuseppe Merlo
4,100005,Richard,Gonzalez,R,19280509.00,USA,188.00,Q53554,Richard Gonzalez

In [52]:
grand_slams.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year,tourney key
2130,2000-520,roland garros,Clay,128,G,20000529,1,101736,1.00,NaN,...,22.00,16.00,9.00,13.00,1.00,5085.00,116.00,355.00,2000,roland garros - 2000
2131,2000-520,roland garros,Clay,128,G,20000529,2,102344,NaN,NaN,...,9.00,11.00,14.00,23.00,40.00,845.00,219.00,158.00,2000,roland garros - 2000
2132,2000-520,roland garros,Clay,128,G,20000529,3,103181,NaN,NaN,...,15.00,23.00,12.00,25.00,88.00,463.00,83.00,494.00,2000,roland garros - 2000
2133,2000-520,roland garros,Clay,128,G,20000529,4,102644,NaN,NaN,...,17.00,16.00,9.00,17.00,45.00,802.00,110.00,376.00,2000,roland garros - 2000
2134,2000-520,roland garros,Clay,128,G,20000529,5,103454,NaN,NaN,...,10.00,14.00,5.00,12.00,75.00,579.00,130.00,310.00,2000,roland garros - 2000

In [53]:
stat = pd.merge(grand_slams,players,how='inner',left_on='winner_id',right_on='player_id')
stat.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,tourney key,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
0,2000-520,roland garros,Clay,128,G,20000529,1,101736,1.00,NaN,...,roland garros - 2000,101736,Andre,Agassi,R,19700429.00,USA,180.00,Q7407,Andre Agassi
1,2000-520,roland garros,Clay,128,G,20000529,2,102344,NaN,NaN,...,roland garros - 2000,102344,Karol,Kucera,R,19740304.00,SVK,188.00,Q460621,Karol Kucera
2,2000-520,roland garros,Clay,128,G,20000529,3,103181,NaN,NaN,...,roland garros - 2000,103181,Jiri,Vanek,R,19780424.00,CZE,185.00,Q246293,Jiri Vanek
3,2000-520,roland garros,Clay,128,G,20000529,4,102644,NaN,NaN,...,roland garros - 2000,102644,Franco,Squillari,L,19750822.00,ARG,183.00,Q730200,Franco Squillari
4,2000-520,roland garros,Clay,128,G,20000529,5,103454,NaN,NaN,...,roland garros - 2000,103454,Nicolas,Massu,R,19791010.00,CHI,183.00,Q295858,Nicolas Massu

In [54]:
sinner_stat = stat[stat['full_name'] == 'Jannik Sinner']
sinner_stat

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,tourney key,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
10201,2020-580,australian open,Hard,128,G,20200120,141,206173,NaN,NaN,...,australian open - 2020,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner
10469,2020-520,roland garros,Clay,128,G,20200928,1156,206173,NaN,NaN,...,roland garros - 2020,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner
10505,2020-520,roland garros,Clay,128,G,20200928,1228,206173,NaN,NaN,...,roland garros - 2020,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner
10523,2020-520,roland garros,Clay,128,G,20200928,1314,206173,NaN,NaN,...,roland garros - 2020,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner
10532,2020-520,roland garros,Clay,128,G,20200928,1407,206173,NaN,NaN,...,roland garros - 2020,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12542,2024-560,us open,Hard,128,G,20240826,196,206173,1.00,NaN,...,us open - 2024,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner
12558,2024-560,us open,Hard,128,G,20240826,212,206173,1.00,NaN,...,us open - 2024,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner
12566,2024-560,us open,Hard,128,G,20240826,220,206173,1.00,NaN,...,us open - 2024,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner
12570,2024-560,us open,Hard,128,G,20240826,224,206173,1.00,NaN,...,us open - 2024,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner
12572,2024-560,us open,Hard,128,G,20240826,226,206173,1.00,NaN,...,us open - 2024,206173,Jannik,Sinner,R,20010816.00,ITA,191.00,Q54812588,Jannik Sinner

In [55]:
sinner_stat.columns

Index(['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level',
       'tourney_date', 'match_num', 'winner_id', 'winner_seed', 'winner_entry',
       'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age',
       'loser_id', 'loser_seed', 'loser_entry', 'loser_name', 'loser_hand',
       'loser_ht', 'loser_ioc', 'loser_age', 'score', 'best_of', 'round',
       'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon',
       'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt',
       'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced',
       'winner_rank', 'winner_rank_points', 'loser_rank', 'loser_rank_points',
       'year', 'tourney key', 'player_id', 'name_first', 'name_last', 'hand',
       'dob', 'ioc', 'height', 'wikidata_id', 'full_name'],
      dtype='object')

In [56]:
sinner_aces = sinner_stat.groupby(['tourney_name','round','year'])[['w_ace','l_ace','w_df','w_svpt','w_1stIn','w_1stWon','w_2ndWon','w_SvGms','w_bpSaved','w_bpFaced','l_df','l_svpt','l_1stIn','l_1stWon','l_2ndWon','l_SvGms','l_bpSaved','l_bpFaced',]].sum()
sinner_aces

                            w_ace  l_ace  w_df  w_svpt  w_1stIn  w_1stWon  \
tourney_name    round year
australian open F     2024  14.00  11.00  5.00  144.00    88.00     65.00
                QF    2024  10.00  10.00  3.00  117.00    75.00     57.00
                R128  2020   2.00   3.00  1.00   91.00    53.00     42.00
                      2022   3.00   1.00  2.00   88.00    57.00     42.00
                      2023   6.00   2.00  2.00   82.00    54.00     44.00
...                           ...    ...   ...     ...      ...       ...
wimbledon       R32   2023   9.00  14.00  8.00   98.00    48.00     40.00
                      2024  11.00   2.00  2.00   69.00    42.00     36.00
                R64   2022   4.00   2.00  5.00  106.00    63.00     50.00
                      2023  15.00   1.00  1.00   83.00    47.00     38.00
                      2024  10.00  28.00  2.00  135.00    88.00     72.00

                            w_2ndWon  w_SvGms  w_bpSaved  w_bpFaced  l_df  \
tourney_name    round year
australian open F     2024     30.00    24.00       8.00      12.00  3.00
                QF    2024     22.00    16.00       8.00       8.00  2.00
                R128  2020     20.00    15.00       4.00       6.00  3.00
                      2022     18.00    15.00       0.00       2.00  3.00
                      2023     12.00    12.00       5.00       6.00  2.00
...                              ...      ...        ...        ...   ...
wimbledon       R32   2023     31.00    18.00       2.00       4.00  9.00
                      2024     18.00    13.00       1.00       1.00  1.00
                R64   2022     24.00    20.00       3.00       6.00  3.00
                      2023     21.00    14.00       4.00       5.00  2.00
                      2024     25.00    22.00       3.00       7.00  3.00

                            l_svpt  l_1stIn  l_1stWon  l_2ndWon  l_SvGms  \
tourney_name    round year
australian open F     2024  139.00    95.00     72.00     20.00    23.00
                QF    2024  101.00    71.00     54.00     11.00    15.00
                R128  2020  106.00    71.00     42.00     17.00    15.00
                      2022   92.00    57.00     31.00     16.00    14.00
                      2023   81.00    45.00     24.00     13.00    12.00
...                            ...      ...       ...       ...      ...
wimbledon       R32   2023  115.00    61.00     46.00     25.00    18.00
                      2024   71.00    45.00     33.00      8.00    12.00
                R64   2022  140.00    90.00     51.00     27.00    19.00
                      2023   81.00    58.00     34.00      9.00    13.00
                      2024  162.00   116.00     82.00     21.00    22.00

                            l_bpSaved  l_bpFaced
tourney_name    round year
australian open F     2024       5.00       9.00
                QF    2024       5.00       7.00
                R128  2020       4.00       9.00
                      2022       5.00      11.00
                      2023       3.00      10.00
...                               ...        ...
wimbledon       R32   2023       6.00      11.00
                      2024       2.00       7.00
                R64   2022      13.00      19.00
                      2023       4.00      10.00
                      2024       8.00      10.00

[61 rows x 18 columns]

In [57]:
sinner_aces['total Ace'] = sinner_aces['w_ace'] + sinner_aces['l_ace']
sinner_aces

                            w_ace  l_ace  w_df  w_svpt  w_1stIn  w_1stWon  \
tourney_name    round year
australian open F     2024  14.00  11.00  5.00  144.00    88.00     65.00
                QF    2024  10.00  10.00  3.00  117.00    75.00     57.00
                R128  2020   2.00   3.00  1.00   91.00    53.00     42.00
                      2022   3.00   1.00  2.00   88.00    57.00     42.00
                      2023   6.00   2.00  2.00   82.00    54.00     44.00
...                           ...    ...   ...     ...      ...       ...
wimbledon       R32   2023   9.00  14.00  8.00   98.00    48.00     40.00
                      2024  11.00   2.00  2.00   69.00    42.00     36.00
                R64   2022   4.00   2.00  5.00  106.00    63.00     50.00
                      2023  15.00   1.00  1.00   83.00    47.00     38.00
                      2024  10.00  28.00  2.00  135.00    88.00     72.00

                            w_2ndWon  w_SvGms  w_bpSaved  w_bpFaced  l_df  \
tourney_name    round year
australian open F     2024     30.00    24.00       8.00      12.00  3.00
                QF    2024     22.00    16.00       8.00       8.00  2.00
                R128  2020     20.00    15.00       4.00       6.00  3.00
                      2022     18.00    15.00       0.00       2.00  3.00
                      2023     12.00    12.00       5.00       6.00  2.00
...                              ...      ...        ...        ...   ...
wimbledon       R32   2023     31.00    18.00       2.00       4.00  9.00
                      2024     18.00    13.00       1.00       1.00  1.00
                R64   2022     24.00    20.00       3.00       6.00  3.00
                      2023     21.00    14.00       4.00       5.00  2.00
                      2024     25.00    22.00       3.00       7.00  3.00

                            l_svpt  l_1stIn  l_1stWon  l_2ndWon  l_SvGms  \
tourney_name    round year
australian open F     2024  139.00    95.00     72.00     20.00    23.00
                QF    2024  101.00    71.00     54.00     11.00    15.00
                R128  2020  106.00    71.00     42.00     17.00    15.00
                      2022   92.00    57.00     31.00     16.00    14.00
                      2023   81.00    45.00     24.00     13.00    12.00
...                            ...      ...       ...       ...      ...
wimbledon       R32   2023  115.00    61.00     46.00     25.00    18.00
                      2024   71.00    45.00     33.00      8.00    12.00
                R64   2022  140.00    90.00     51.00     27.00    19.00
                      2023   81.00    58.00     34.00      9.00    13.00
                      2024  162.00   116.00     82.00     21.00    22.00

                            l_bpSaved  l_bpFaced  total Ace
tourney_name    round year
australian open F     2024       5.00       9.00      25.00
                QF    2024       5.00       7.00      20.00
                R128  2020       4.00       9.00       5.00
                      2022       5.00      11.00       4.00
                      2023       3.00      10.00       8.00
...                               ...        ...        ...
wimbledon       R32   2023       6.00      11.00      23.00
                      2024       2.00       7.00      13.00
                R64   2022      13.00      19.00       6.00
                      2023       4.00      10.00      16.00
                      2024       8.00      10.00      38.00

[61 rows x 19 columns]

In [58]:
sinner_aces.to_csv('sinner aces.csv')

## <span style="color: rgb(230, 0, 126);">__________________________________________________________________________________________________________________</span>

FUNCION PARA AUTOMATIZAR LA CREACION DE COLUMNAS PARA LOS STATS POR JUGADOR

In [59]:
def stats_totales_auto(df, group_cols=['tourney_name', 'round','year']):
    import pandas as pd
    
    # Agrupar y sumar numéricas
    grouped = df.groupby(group_cols).sum(numeric_only=True)
    
    # Detectar columnas w_ y l_
    w_cols = [c for c in grouped.columns if c.startswith('w_')]
    l_cols = [c for c in grouped.columns if c.startswith('l_')]
    
    w_metrics = {c[2:]: c for c in w_cols}
    l_metrics = {c[2:]: c for c in l_cols}
    
    # Crear totales
    for metric in w_metrics.keys() & l_metrics.keys():
        grouped[f'total_{metric}'] = grouped[w_metrics[metric]] + grouped[l_metrics[metric]]
    
    # Diccionario de porcentajes automáticos (métrica_base : métrica_referencia)
    ratios = {
        '%aces_por_punto': ('total_ace', 'total_svpt'),
        '%doble_falta': ('total_df', 'total_svpt'),
        '%primer_serve_in': ('total_1stIn', 'total_svpt'),
        '%primer_serve_won': ('total_1stWon', 'total_1stIn'),
        '%segundo_serve_won': ('total_2ndWon', 'total_svpt - total_1stIn'),
        '%bp_saved': ('total_bpSaved', 'total_bpFaced'),
        '%bp_convertidos': ('total_bpSaved', 'total_bpFaced'),  # puedes ajustarlo si quieres bp ganados
        '%juegos_de_saques_ganados': ('total_SvGms', 'total_SvGms')  # placeholder, se puede cambiar
    }
    
    # Calcular porcentajes
    for col_name, (num, den) in ratios.items():
        try:
            # Si el denominador es una resta, evaluamos
            if '-' in den:
                partes = den.split('-')
                den_val = grouped[partes[0].strip()] - grouped[partes[1].strip()]
            else:
                den_val = grouped[den]
            
            grouped[col_name] = (grouped[num] / den_val) * 100
        except KeyError:
            pass  # Si falta alguna métrica, la saltamos
    
    return grouped

In [60]:
sinn_stats = stats_totales_auto(sinner_aces)
sinn_stats.columns

Index(['w_ace', 'l_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon',
       'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_df', 'l_svpt', 'l_1stIn',
       'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced',
       'total Ace', 'total_df', 'total_bpSaved', 'total_1stWon', 'total_ace',
       'total_bpFaced', 'total_SvGms', 'total_svpt', 'total_2ndWon',
       'total_1stIn', '%aces_por_punto', '%doble_falta', '%primer_serve_in',
       '%primer_serve_won', '%segundo_serve_won', '%bp_saved',
       '%bp_convertidos', '%juegos_de_saques_ganados'],
      dtype='object')

In [61]:
sinn_stats_clean = sinn_stats.drop(['w_ace', 'l_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon',
       'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_df', 'l_svpt', 'l_1stIn',
       'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced'],axis='columns')
sinn_stats_clean

                            total Ace  total_df  total_bpSaved  total_1stWon  \
tourney_name    round year
australian open F     2024      25.00      8.00          13.00        137.00
                QF    2024      20.00      5.00          13.00        111.00
                R128  2020       5.00      4.00           8.00         84.00
                      2022       4.00      5.00           5.00         73.00
                      2023       8.00      4.00           8.00         68.00
...                               ...       ...            ...           ...
wimbledon       R32   2023      23.00     17.00           8.00         86.00
                      2024      13.00      3.00           3.00         69.00
                R64   2022       6.00      8.00          16.00        101.00
                      2023      16.00      3.00           8.00         72.00
                      2024      38.00      5.00          11.00        154.00

                            total_ace  total_bpFaced  total_SvGms  total_svpt  \
tourney_name    round year
australian open F     2024      25.00          21.00        47.00      283.00
                QF    2024      20.00          15.00        31.00      218.00
                R128  2020       5.00          15.00        30.00      197.00
                      2022       4.00          13.00        29.00      180.00
                      2023       8.00          16.00        24.00      163.00
...                               ...            ...          ...         ...
wimbledon       R32   2023      23.00          15.00        36.00      213.00
                      2024      13.00           8.00        25.00      140.00
                R64   2022       6.00          25.00        39.00      246.00
                      2023      16.00          15.00        27.00      164.00
                      2024      38.00          17.00        44.00      297.00

                            total_2ndWon  total_1stIn  %aces_por_punto  \
tourney_name    round year
australian open F     2024         50.00       183.00             8.83
                QF    2024         33.00       146.00             9.17
                R128  2020         37.00       124.00             2.54
                      2022         34.00       114.00             2.22
                      2023         25.00        99.00             4.91
...                                  ...          ...              ...
wimbledon       R32   2023         56.00       109.00            10.80
                      2024         26.00        87.00             9.29
                R64   2022         51.00       153.00             2.44
                      2023         30.00       105.00             9.76
                      2024         46.00       204.00            12.79

                            %doble_falta  %primer_serve_in  %primer_serve_won  \
tourney_name    round year
australian open F     2024          2.83             64.66              74.86
                QF    2024          2.29             66.97              76.03
                R128  2020          2.03             62.94              67.74
                      2022          2.78             63.33              64.04
                      2023          2.45             60.74              68.69
...                                  ...               ...                ...
wimbledon       R32   2023          7.98             51.17              78.90
                      2024          2.14             62.14              79.31
                R64   2022          3.25             62.20              66.01
                      2023          1.83             64.02              68.57
                      2024          1.68             68.69              75.49

                            %segundo_serve_won  %bp_saved  %bp_convertidos  \
tourney_name    round year
australian open F     2024               50.00      61.90            61.90
                QF    2024               45.83      86.67            86.67
                R128  2020               50.68      53.33            53.33
                      2022               51.52      38.46            38.46
                      2023               39.06      50.00            50.00
...                                        ...        ...              ...
wimbledon       R32   2023               53.85      53.33            53.33
                      2024               49.06      37.50            37.50
                R64   2022               54.84      64.00            64.00
                      2023               50.85      53.33            53.33
                      2024               49.46      64.71            64.71

                            %juegos_de_saques_ganados
tourney_name    round year
australian open F     2024                     100.00
                QF    2024                     100.00
                R128  2020                     100.00
                      2022                     100.00
                      2023                     100.00
...                                               ...
wimbledon       R32   2023                     100.00
                      2024                     100.00
                R64   2022                     100.00
                      2023                     100.00
                      2024                     100.00

[61 rows x 18 columns]

In [62]:
sinn_stats_clean.to_csv('sinner_stats.csv')

## <span style="color: rgb(230, 0, 126);">__________________________________________________________________________________________________________________</span>
## <span style="color: rgb(230, 215, 0);">__________________________________________________________________________________________________________________</span>
## <span style="color: rgb(230, 0, 126);">__________________________________________________________________________________________________________________</span>

## WTA

In [63]:
wta_matches = pd.read_csv('partidos_wta_2000_2024.csv')
wta_matches

C:\Users\Usuario\AppData\Local\Temp\ipykernel_16148\2846374329.py:1: DtypeWarning: Columns (8,16) have mixed types. Specify dtype option on import or set low_memory=False.
  wta_matches = pd.read_csv('partidos_wta_2000_2024.csv')

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
0,2000-D001,Fed Cup G1 PO: JPN vs CHN,Hard,4,D,20000430,1,201419,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,190.00,121.00,125.00,205.00,2000
1,2000-D001,Fed Cup G1 PO: JPN vs CHN,Hard,4,D,20000430,2,200085,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,22.00,1230.00,96.00,319.00,2000
2,2000-D002,Fed Cup WG SF: USA vs BEL,Carpet,4,D,20001122,1,200652,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.00,3255.00,48.00,661.00,2000
3,2000-D002,Fed Cup WG SF: USA vs BEL,Carpet,4,D,20001122,2,200128,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.00,5022.00,18.00,1398.00,2000
4,2000-D003,Fed Cup WG SF: CZE vs ESP,Carpet,4,D,20001121,1,200017,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,9.00,2132.00,54.00,610.00,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68619,2024-W-FC-2024-POS,BJK Cup Playoffs,NaN,16,D,20241115,226,201709,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,29.00,1844.00,418.00,141.00,2024
68620,2024-W-FC-2024-POS,BJK Cup Playoffs,NaN,16,D,20241115,227,215785,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,63.00,989.00,66.00,949.00,2024
68621,2024-W-FC-2024-POS,BJK Cup Playoffs,NaN,16,D,20241115,228,221257,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,222.00,327.00,118.00,648.00,2024
68622,2024-W-FC-2024-POS,BJK Cup Playoffs,NaN,16,D,20241115,229,216262,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,74.00,900.00,180.00,394.00,2024
68623,2024-W-FC-2024-POS,BJK Cup Playoffs,NaN,16,D,20241115,230,215290,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,229.00,315.00,523.00,93.00,2024

In [64]:
wta_players = pd.read_csv('wta_players.csv')
wta_players

C:\Users\Usuario\AppData\Local\Temp\ipykernel_16148\2554277501.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  wta_players = pd.read_csv('wta_players.csv')

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id
0,113190,Bobby,Riggs,U,NaN,USA,NaN,NaN
1,200000,X,X,U,19000000.00,UNK,NaN,NaN
2,200001,Martina,Hingis,R,19800930.00,SUI,170.00,Q134720
3,200002,Mirjana,Lucic,R,19820309.00,CRO,181.00,Q239686
4,200003,Justine,Henin,R,19820601.00,BEL,167.00,Q11682
...,...,...,...,...,...,...,...,...
70031,270041,Emily,Dunn,U,NaN,NZL,NaN,NaN
70032,270042,Serena,Rodricks,U,NaN,IND,NaN,NaN
70033,270043,Isha,Mohite,U,NaN,IND,NaN,NaN
70034,270044,Una,Misic,U,NaN,NZL,NaN,NaN
70035,270045,Dorea,Morina,U,NaN,NZL,NaN,NaN

In [65]:
wta_matches['tourney_name'] = wta_matches['tourney_name'].str.strip().str.lower()

In [66]:
wta_grand_slams = wta_matches[wta_matches['tourney_name'].isin(['us open','wimbledon','roland garros','australian open'])]
wta_grand_slams

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
599,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,1,200001,1.00,NaN,...,NaN,NaN,NaN,NaN,NaN,1.00,6003.00,49.00,640.00,2000
600,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,2,200003,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,63.00,510.00,133.00,199.00,2000
601,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,3,200006,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,53.00,574.00,118.00,243.00,2000
602,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,4,200008,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,116.00,245.00,23.00,1112.00,2000
603,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,5,200009,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,72.00,439.00,60.00,516.00,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68019,2024-560,us open,Hard,128,G,20240826,222,215613,13.00,NaN,...,22.00,5.00,10.00,3.00,8.00,12.00,3040.00,29.00,1895.00,2024
68020,2024-560,us open,Hard,128,G,20240826,223,214544,2.00,NaN,...,14.00,8.00,7.00,4.00,8.00,2.00,8016.00,7.00,3980.00,2024
68021,2024-560,us open,Hard,128,G,20240826,224,202468,6.00,NaN,...,34.00,14.00,13.00,8.00,13.00,6.00,5160.00,52.00,1126.00,2024
68022,2024-560,us open,Hard,128,G,20240826,225,214544,2.00,NaN,...,32.00,4.00,10.00,3.00,6.00,2.00,8016.00,12.00,3040.00,2024
68023,2024-560,us open,Hard,128,G,20240826,226,214544,2.00,NaN,...,37.00,6.00,12.00,9.00,15.00,2.00,8016.00,6.00,5160.00,2024

In [67]:
wta_grand_slams['tourney_key'] = wta_grand_slams['tourney_name'] + '-' + wta_grand_slams['year'].astype(str)
wta_grand_slams

C:\Users\Usuario\AppData\Local\Temp\ipykernel_16148\3478283747.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wta_grand_slams['tourney_key'] = wta_grand_slams['tourney_name'] + '-' + wta_grand_slams['year'].astype(str)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year,tourney_key
599,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,1,200001,1.00,NaN,...,NaN,NaN,NaN,NaN,1.00,6003.00,49.00,640.00,2000,australian open-2000
600,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,2,200003,NaN,NaN,...,NaN,NaN,NaN,NaN,63.00,510.00,133.00,199.00,2000,australian open-2000
601,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,3,200006,NaN,NaN,...,NaN,NaN,NaN,NaN,53.00,574.00,118.00,243.00,2000,australian open-2000
602,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,4,200008,NaN,NaN,...,NaN,NaN,NaN,NaN,116.00,245.00,23.00,1112.00,2000,australian open-2000
603,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,5,200009,NaN,NaN,...,NaN,NaN,NaN,NaN,72.00,439.00,60.00,516.00,2000,australian open-2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68019,2024-560,us open,Hard,128,G,20240826,222,215613,13.00,NaN,...,5.00,10.00,3.00,8.00,12.00,3040.00,29.00,1895.00,2024,us open-2024
68020,2024-560,us open,Hard,128,G,20240826,223,214544,2.00,NaN,...,8.00,7.00,4.00,8.00,2.00,8016.00,7.00,3980.00,2024,us open-2024
68021,2024-560,us open,Hard,128,G,20240826,224,202468,6.00,NaN,...,14.00,13.00,8.00,13.00,6.00,5160.00,52.00,1126.00,2024,us open-2024
68022,2024-560,us open,Hard,128,G,20240826,225,214544,2.00,NaN,...,4.00,10.00,3.00,6.00,2.00,8016.00,12.00,3040.00,2024,us open-2024
68023,2024-560,us open,Hard,128,G,20240826,226,214544,2.00,NaN,...,6.00,12.00,9.00,15.00,2.00,8016.00,6.00,5160.00,2024,us open-2024

In [68]:
wta_players['full_name'] = wta_players['name_first'] + ' ' + wta_players['name_last']
wta_players

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
0,113190,Bobby,Riggs,U,NaN,USA,NaN,NaN,Bobby Riggs
1,200000,X,X,U,19000000.00,UNK,NaN,NaN,X X
2,200001,Martina,Hingis,R,19800930.00,SUI,170.00,Q134720,Martina Hingis
3,200002,Mirjana,Lucic,R,19820309.00,CRO,181.00,Q239686,Mirjana Lucic
4,200003,Justine,Henin,R,19820601.00,BEL,167.00,Q11682,Justine Henin
...,...,...,...,...,...,...,...,...,...
70031,270041,Emily,Dunn,U,NaN,NZL,NaN,NaN,Emily Dunn
70032,270042,Serena,Rodricks,U,NaN,IND,NaN,NaN,Serena Rodricks
70033,270043,Isha,Mohite,U,NaN,IND,NaN,NaN,Isha Mohite
70034,270044,Una,Misic,U,NaN,NZL,NaN,NaN,Una Misic
70035,270045,Dorea,Morina,U,NaN,NZL,NaN,NaN,Dorea Morina

In [69]:
df_wta_players_top10 = wta_players[wta_players['full_name'].isin(['Aryna Sabalenka','Coco Gauff','Iga Swiatek','Jessica Pegula','Mirra Andreeva','Qinwen Zheng','Amanda Anisimova','Madison Keys','Jasmine Paolini','Paula Badosa'])]
df_wta_players_top10

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
1620,201619,Madison,Keys,R,19950217.00,USA,178.00,Q34403,Madison Keys
2469,202468,Jessica,Pegula,R,19940224.00,USA,170.00,Q24159,Jessica Pegula
11149,211148,Jasmine,Paolini,R,19960104.00,ITA,160.00,Q19973674,Jasmine Paolini
11652,211651,Paula,Badosa,R,19971115.00,ESP,180.00,Q19560013,Paula Badosa
14545,214544,Aryna,Sabalenka,R,19980505.00,BLR,182.00,Q23448791,Aryna Sabalenka
16154,216153,Amanda,Anisimova,R,20010831.00,USA,180.00,NaN,Amanda Anisimova
16348,216347,Iga,Swiatek,R,20010531.00,POL,176.00,Q26840238,Iga Swiatek
21003,221012,Qinwen,Zheng,R,20021008.00,CHN,NaN,Q62096129,Qinwen Zheng
21094,221103,Coco,Gauff,R,20040313.00,USA,175.00,Q39263365,Coco Gauff
59789,259799,Mirra,Andreeva,R,20070429.00,RUS,NaN,NaN,Mirra Andreeva

In [70]:
df_wta_players_merge_matches = pd.merge(df_wta_players_top10,wta_grand_slams,how='inner',left_on='player_id',right_on='winner_id')
df_wta_players_merge_matches

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name,tourney_id,...,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year,tourney_key
0,201619,Madison,Keys,R,19950217.00,USA,178.00,Q34403,Madison Keys,2011-W-SL-USA-01A-2011,...,14.00,NaN,5.00,9.00,455.00,79.00,111.00,612.00,2011,us open-2011
1,201619,Madison,Keys,R,19950217.00,USA,178.00,Q34403,Madison Keys,2013-W-SL-AUS-01A-2013,...,11.00,NaN,4.00,8.00,105.00,656.00,102.00,662.00,2013,australian open-2013
2,201619,Madison,Keys,R,19950217.00,USA,178.00,Q34403,Madison Keys,2013-W-SL-AUS-01A-2013,...,5.00,NaN,3.00,7.00,105.00,656.00,30.00,1523.00,2013,australian open-2013
3,201619,Madison,Keys,R,19950217.00,USA,178.00,Q34403,Madison Keys,2013-W-SL-FRA-01A-2013,...,9.00,NaN,1.00,5.00,58.00,1028.00,82.00,799.00,2013,roland garros-2013
4,201619,Madison,Keys,R,19950217.00,USA,178.00,Q34403,Madison Keys,2013-W-SL-GBR-01A-2013,...,13.00,NaN,2.00,7.00,52.00,1160.00,56.00,1085.00,2013,wimbledon-2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,259799,Mirra,Andreeva,R,20070429.00,RUS,NaN,NaN,Mirra Andreeva,2024-520,...,6.00,15.00,3.00,13.00,38.00,1407.00,21.00,2174.00,2024,roland garros-2024
496,259799,Mirra,Andreeva,R,20070429.00,RUS,NaN,NaN,Mirra Andreeva,2024-520,...,9.00,8.00,5.00,11.00,38.00,1407.00,62.00,1040.00,2024,roland garros-2024
497,259799,Mirra,Andreeva,R,20070429.00,RUS,NaN,NaN,Mirra Andreeva,2024-520,...,11.00,10.00,4.00,9.00,38.00,1407.00,88.00,800.00,2024,roland garros-2024
498,259799,Mirra,Andreeva,R,20070429.00,RUS,NaN,NaN,Mirra Andreeva,2024-520,...,24.00,16.00,6.00,14.00,38.00,1407.00,2.00,8138.00,2024,roland garros-2024
499,259799,Mirra,Andreeva,R,20070429.00,RUS,NaN,NaN,Mirra Andreeva,2024-560,...,5.00,10.00,4.00,12.00,23.00,2153.00,82.00,861.00,2024,us open-2024

## <span style="color: rgb(230, 215, 0);">__________________________________________________________________________________________________________________</span>
## <span style="color: rgb(230, 0, 126);">__________________________________________________________________________________________________________________</span>

## <span style="color: rgb(230, 0, 126);">__________________________________________________________________________________________________________________</span>

WTA PLAYERS CLEAN

In [71]:
wta_players_clean = df_wta_players_merge_matches.iloc[:,[5,8,14,16,23,32,34,-1,-2]]
wta_players_clean

,ioc,full_name,tourney_date,winner_id,winner_age,score,round,tourney_key,year
0,USA,Madison Keys,20110829,201619,16.50,6-2 6-4,R128,us open-2011,2011
1,USA,Madison Keys,20130114,201619,17.90,6-4 7-6(0),R128,australian open-2013,2013
2,USA,Madison Keys,20130114,201619,17.90,6-2 6-1,R64,australian open-2013,2013
3,USA,Madison Keys,20130527,201619,18.20,6-3 6-2,R128,roland garros-2013,2013
4,USA,Madison Keys,20130624,201619,18.30,6-3 7-5,R128,wimbledon-2013,2013
...,...,...,...,...,...,...,...,...,...
495,RUS,Mirra Andreeva,20240527,259799,17.00,6-3 3-6 7-5,R64,roland garros-2024,2024
496,RUS,Mirra Andreeva,20240527,259799,17.00,6-2 6-1,R32,roland garros-2024,2024
497,RUS,Mirra Andreeva,20240527,259799,17.00,7-5 6-2,R16,roland garros-2024,2024
498,RUS,Mirra Andreeva,20240527,259799,17.00,6-7(5) 6-4 6-4,QF,roland garros-2024,2024
499,RUS,Mirra Andreeva,20240826,259799,17.30,6-2 7-6(4),R128,us open-2024,2024

## <span style="color: rgb(230, 0, 126);">__________________________________________________________________________________________________________________</span>

In [72]:
wta_tourneys = pd.merge(wta_grand_slams,wta_players,how='inner',left_on='winner_id',right_on='player_id')
wta_tourneys

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,tourney_key,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
0,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,1,200001,1.00,NaN,...,australian open-2000,200001,Martina,Hingis,R,19800930.00,SUI,170.00,Q134720,Martina Hingis
1,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,2,200003,NaN,NaN,...,australian open-2000,200003,Justine,Henin,R,19820601.00,BEL,167.00,Q11682,Justine Henin
2,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,3,200006,NaN,NaN,...,australian open-2000,200006,Karina,Habsudova,R,19730802.00,SVK,170.00,Q269278,Karina Habsudova
3,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,4,200008,NaN,NaN,...,australian open-2000,200008,Alicia,Molik,R,19810127.00,AUS,182.00,Q232922,Alicia Molik
4,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,5,200009,NaN,NaN,...,australian open-2000,200009,Tamarine,Tanasugarn,R,19770524.00,THA,165.00,Q144555,Tamarine Tanasugarn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12568,2024-560,us open,Hard,128,G,20240826,222,215613,13.00,NaN,...,us open-2024,215613,Emma,Navarro,R,20010518.00,USA,NaN,Q62675797,Emma Navarro
12569,2024-560,us open,Hard,128,G,20240826,223,214544,2.00,NaN,...,us open-2024,214544,Aryna,Sabalenka,R,19980505.00,BLR,182.00,Q23448791,Aryna Sabalenka
12570,2024-560,us open,Hard,128,G,20240826,224,202468,6.00,NaN,...,us open-2024,202468,Jessica,Pegula,R,19940224.00,USA,170.00,Q24159,Jessica Pegula
12571,2024-560,us open,Hard,128,G,20240826,225,214544,2.00,NaN,...,us open-2024,214544,Aryna,Sabalenka,R,19980505.00,BLR,182.00,Q23448791,Aryna Sabalenka
12572,2024-560,us open,Hard,128,G,20240826,226,214544,2.00,NaN,...,us open-2024,214544,Aryna,Sabalenka,R,19980505.00,BLR,182.00,Q23448791,Aryna Sabalenka

In [73]:
wta_aus_open = wta_tourneys[wta_tourneys['tourney_name'] == 'australian open']

In [74]:
winners_wta_aus_open = wta_aus_open[wta_aus_open['round'] == 'F']

In [75]:
winn_tourney_wta_aus = winners_wta_aus_open.groupby(['winner_id','full_name'])['tourney_id'].count().reset_index(name='torneo_ganados')
winn_tourney_wta_aus

    winner_id           full_name  torneo_ganados
0      200003       Justine Henin               1
1      200033     Serena Williams               7
2      200065     Amelie Mauresmo               1
3      200077   Jennifer Capriati               2
4      200079       Kim Clijsters               1
5      200128   Lindsay Davenport               1
6      201345     Maria Sharapova               1
7      201419               Na Li               1
8      201458   Victoria Azarenka               2
9      201493    Angelique Kerber               1
10     201496  Caroline Wozniacki               1
11     202458      Ashleigh Barty               1
12     211768         Naomi Osaka               2
13     213550         Sofia Kenin               1
14     214544     Aryna Sabalenka               2

In [76]:
wta_RG = wta_tourneys[wta_tourneys['tourney_name'] == 'roland garros']

In [77]:
winners_wta_RG = wta_RG[wta_RG['round'] == 'F']

In [78]:
winn_tourney_wta_RG = winners_wta_RG.groupby(['winner_id','full_name'])['tourney_id'].count().reset_index(name='torneo_ganados')
winn_tourney_wta_RG

    winner_id            full_name  torneo_ganados
0      200003        Justine Henin               4
1      200033      Serena Williams               3
2      200077    Jennifer Capriati               1
3      200096          Mary Pierce               1
4      200772    Anastasia Myskina               1
5      201212  Francesca Schiavone               1
6      201320  Svetlana Kuznetsova               1
7      201345      Maria Sharapova               2
8      201419                Na Li               1
9      201421         Ana Ivanovic               1
10     201594         Simona Halep               1
11     202458       Ashleigh Barty               1
12     202469     Garbine Muguruza               1
13     206252   Barbora Krejcikova               1
14     211533     Jelena Ostapenko               1
15     216347          Iga Swiatek               4

In [79]:
wta_wimbl = wta_tourneys[wta_tourneys['tourney_name'] == 'wimbledon']

In [80]:
winners_wta_wimbl = wta_wimbl[wta_wimbl['round'] == 'F']

In [81]:
winn_tourney_wta_wimb = winners_wta_wimbl.groupby(['winner_id','full_name'])['tourney_id'].count().reset_index(name='torneo_ganados')
winn_tourney_wta_wimb

    winner_id            full_name  torneo_ganados
0      200033      Serena Williams               7
1      200065      Amelie Mauresmo               1
2      200748       Venus Williams               5
3      201294       Marion Bartoli               1
4      201345      Maria Sharapova               1
5      201493     Angelique Kerber               1
6      201520        Petra Kvitova               2
7      201594         Simona Halep               1
8      202458       Ashleigh Barty               1
9      202469     Garbine Muguruza               1
10     206252   Barbora Krejcikova               1
11     214954  Marketa Vondrousova               1
12     214981       Elena Rybakina               1

In [82]:
wta_us_open = wta_tourneys[wta_tourneys['tourney_name'] == 'us open']

In [83]:
winners_wta_us = wta_us_open[wta_us_open['round'] == 'F']

In [84]:
winn_tourney_wta_us_open = winners_wta_us.groupby(['winner_id','full_name'])['tourney_id'].count().reset_index(name='torneo_ganados')
winn_tourney_wta_us_open

    winner_id            full_name  torneo_ganados
0      200003        Justine Henin               2
1      200033      Serena Williams               5
2      200079        Kim Clijsters               3
3      200748       Venus Williams               2
4      201320  Svetlana Kuznetsova               1
5      201325      Samantha Stosur               1
6      201345      Maria Sharapova               1
7      201355      Flavia Pennetta               1
8      201493     Angelique Kerber               1
9      201585      Sloane Stephens               1
10     211768          Naomi Osaka               2
11     214544      Aryna Sabalenka               1
12     215370     Bianca Andreescu               1
13     216347          Iga Swiatek               1
14     221054        Emma Raducanu               1
15     221103           Coco Gauff               1

In [85]:
winn_tourney_wta_aus["tournament"] = "Australian Open"
winn_tourney_wta_RG["tournament"] = "Roland Garros"
winn_tourney_wta_wimb["tournament"] = "Wimbledon"
winn_tourney_wta_us_open["tournament"] = "US Open"

In [86]:
wta_all_tourneys = pd.concat([winn_tourney_wta_aus,winn_tourney_wta_RG,winn_tourney_wta_wimb,winn_tourney_wta_us_open])
wta_all_tourneys

    winner_id            full_name  torneo_ganados       tournament
0      200003        Justine Henin               1  Australian Open
1      200033      Serena Williams               7  Australian Open
2      200065      Amelie Mauresmo               1  Australian Open
3      200077    Jennifer Capriati               2  Australian Open
4      200079        Kim Clijsters               1  Australian Open
5      200128    Lindsay Davenport               1  Australian Open
6      201345      Maria Sharapova               1  Australian Open
7      201419                Na Li               1  Australian Open
8      201458    Victoria Azarenka               2  Australian Open
9      201493     Angelique Kerber               1  Australian Open
10     201496   Caroline Wozniacki               1  Australian Open
11     202458       Ashleigh Barty               1  Australian Open
12     211768          Naomi Osaka               2  Australian Open
13     213550          Sofia Kenin               1  Australian Open
14     214544      Aryna Sabalenka               2  Australian Open
0      200003        Justine Henin               4    Roland Garros
1      200033      Serena Williams               3    Roland Garros
2      200077    Jennifer Capriati               1    Roland Garros
3      200096          Mary Pierce               1    Roland Garros
4      200772    Anastasia Myskina               1    Roland Garros
5      201212  Francesca Schiavone               1    Roland Garros
6      201320  Svetlana Kuznetsova               1    Roland Garros
7      201345      Maria Sharapova               2    Roland Garros
8      201419                Na Li               1    Roland Garros
9      201421         Ana Ivanovic               1    Roland Garros
10     201594         Simona Halep               1    Roland Garros
11     202458       Ashleigh Barty               1    Roland Garros
12     202469     Garbine Muguruza               1    Roland Garros
13     206252   Barbora Krejcikova               1    Roland Garros
14     211533     Jelena Ostapenko               1    Roland Garros
15     216347          Iga Swiatek               4    Roland Garros
0      200033      Serena Williams               7        Wimbledon
1      200065      Amelie Mauresmo               1        Wimbledon
2      200748       Venus Williams               5        Wimbledon
3      201294       Marion Bartoli               1        Wimbledon
4      201345      Maria Sharapova               1        Wimbledon
5      201493     Angelique Kerber               1        Wimbledon
6      201520        Petra Kvitova               2        Wimbledon
7      201594         Simona Halep               1        Wimbledon
8      202458       Ashleigh Barty               1        Wimbledon
9      202469     Garbine Muguruza               1        Wimbledon
10     206252   Barbora Krejcikova               1        Wimbledon
11     214954  Marketa Vondrousova               1        Wimbledon
12     214981       Elena Rybakina               1        Wimbledon
0      200003        Justine Henin               2          US Open
1      200033      Serena Williams               5          US Open
2      200079        Kim Clijsters               3          US Open
3      200748       Venus Williams               2          US Open
4      201320  Svetlana Kuznetsova               1          US Open
5      201325      Samantha Stosur               1          US Open
6      201345      Maria Sharapova               1          US Open
7      201355      Flavia Pennetta               1          US Open
8      201493     Angelique Kerber               1          US Open
9      201585      Sloane Stephens               1          US Open
10     211768          Naomi Osaka               2          US Open
11     214544      Aryna Sabalenka               1          US Open
12     215370     Bianca Andreescu               1          US Open
13     216347          Iga Swiatek               1          US Open
14     221054        Emma Raducanu               1          US Open
15     221103           Coco Gauff               1          US Open

In [87]:
wta_all_tourneys.to_csv('wta all tourneys winners.csv',index=False)

In [96]:
wta_grand_slams

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year,tourney_key
599,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,1,200001,1.00,NaN,...,NaN,NaN,NaN,NaN,1.00,6003.00,49.00,640.00,2000,australian open-2000
600,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,2,200003,NaN,NaN,...,NaN,NaN,NaN,NaN,63.00,510.00,133.00,199.00,2000,australian open-2000
601,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,3,200006,NaN,NaN,...,NaN,NaN,NaN,NaN,53.00,574.00,118.00,243.00,2000,australian open-2000
602,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,4,200008,NaN,NaN,...,NaN,NaN,NaN,NaN,116.00,245.00,23.00,1112.00,2000,australian open-2000
603,2000-W-SL-AUS-01A-2000,australian open,Hard,128,G,20000117,5,200009,NaN,NaN,...,NaN,NaN,NaN,NaN,72.00,439.00,60.00,516.00,2000,australian open-2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68019,2024-560,us open,Hard,128,G,20240826,222,215613,13.00,NaN,...,5.00,10.00,3.00,8.00,12.00,3040.00,29.00,1895.00,2024,us open-2024
68020,2024-560,us open,Hard,128,G,20240826,223,214544,2.00,NaN,...,8.00,7.00,4.00,8.00,2.00,8016.00,7.00,3980.00,2024,us open-2024
68021,2024-560,us open,Hard,128,G,20240826,224,202468,6.00,NaN,...,14.00,13.00,8.00,13.00,6.00,5160.00,52.00,1126.00,2024,us open-2024
68022,2024-560,us open,Hard,128,G,20240826,225,214544,2.00,NaN,...,4.00,10.00,3.00,6.00,2.00,8016.00,12.00,3040.00,2024,us open-2024
68023,2024-560,us open,Hard,128,G,20240826,226,214544,2.00,NaN,...,6.00,12.00,9.00,15.00,2.00,8016.00,6.00,5160.00,2024,us open-2024

In [99]:
df_wta_players_top10

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
1620,201619,Madison,Keys,R,19950217.00,USA,178.00,Q34403,Madison Keys
2469,202468,Jessica,Pegula,R,19940224.00,USA,170.00,Q24159,Jessica Pegula
11149,211148,Jasmine,Paolini,R,19960104.00,ITA,160.00,Q19973674,Jasmine Paolini
11652,211651,Paula,Badosa,R,19971115.00,ESP,180.00,Q19560013,Paula Badosa
14545,214544,Aryna,Sabalenka,R,19980505.00,BLR,182.00,Q23448791,Aryna Sabalenka
16154,216153,Amanda,Anisimova,R,20010831.00,USA,180.00,NaN,Amanda Anisimova
16348,216347,Iga,Swiatek,R,20010531.00,POL,176.00,Q26840238,Iga Swiatek
21003,221012,Qinwen,Zheng,R,20021008.00,CHN,NaN,Q62096129,Qinwen Zheng
21094,221103,Coco,Gauff,R,20040313.00,USA,175.00,Q39263365,Coco Gauff
59789,259799,Mirra,Andreeva,R,20070429.00,RUS,NaN,NaN,Mirra Andreeva

In [95]:
premios

      year             tourney key round   premio €
0     2000          us open - 2000     W 2738611.89
1     2001          us open - 2001     W 2808172.64
2     2002          us open - 2002     W 2879500.22
3     2003          us open - 2003     W 2952639.53
4     2004          us open - 2004     W 3027636.57
...    ...                     ...   ...        ...
1095  2020  australian open - 2020    Q1   31658.82
1096  2021  australian open - 2021    Q1   32462.96
1097  2022  australian open - 2022    Q1   33287.52
1098  2023  australian open - 2023    Q1   34133.02
1099  2024  australian open - 2024    Q1   35000.00

[1100 rows x 4 columns]

In [ ]:
wta_top10_grandSlams = pd.merge(df_wta_players_top10,wta_grand_slams,how='inner',left_on='player_id',right_on='winner_id')
wta_top10_grandSlams

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name,tourney_id,...,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year,tourney_key
0,201619,Madison,Keys,R,19950217.00,USA,178.00,Q34403,Madison Keys,2011-W-SL-USA-01A-2011,...,14.00,NaN,5.00,9.00,455.00,79.00,111.00,612.00,2011,us open-2011
1,201619,Madison,Keys,R,19950217.00,USA,178.00,Q34403,Madison Keys,2013-W-SL-AUS-01A-2013,...,11.00,NaN,4.00,8.00,105.00,656.00,102.00,662.00,2013,australian open-2013
2,201619,Madison,Keys,R,19950217.00,USA,178.00,Q34403,Madison Keys,2013-W-SL-AUS-01A-2013,...,5.00,NaN,3.00,7.00,105.00,656.00,30.00,1523.00,2013,australian open-2013
3,201619,Madison,Keys,R,19950217.00,USA,178.00,Q34403,Madison Keys,2013-W-SL-FRA-01A-2013,...,9.00,NaN,1.00,5.00,58.00,1028.00,82.00,799.00,2013,roland garros-2013
4,201619,Madison,Keys,R,19950217.00,USA,178.00,Q34403,Madison Keys,2013-W-SL-GBR-01A-2013,...,13.00,NaN,2.00,7.00,52.00,1160.00,56.00,1085.00,2013,wimbledon-2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,259799,Mirra,Andreeva,R,20070429.00,RUS,NaN,NaN,Mirra Andreeva,2024-520,...,6.00,15.00,3.00,13.00,38.00,1407.00,21.00,2174.00,2024,roland garros-2024
496,259799,Mirra,Andreeva,R,20070429.00,RUS,NaN,NaN,Mirra Andreeva,2024-520,...,9.00,8.00,5.00,11.00,38.00,1407.00,62.00,1040.00,2024,roland garros-2024
497,259799,Mirra,Andreeva,R,20070429.00,RUS,NaN,NaN,Mirra Andreeva,2024-520,...,11.00,10.00,4.00,9.00,38.00,1407.00,88.00,800.00,2024,roland garros-2024
498,259799,Mirra,Andreeva,R,20070429.00,RUS,NaN,NaN,Mirra Andreeva,2024-520,...,24.00,16.00,6.00,14.00,38.00,1407.00,2.00,8138.00,2024,roland garros-2024
499,259799,Mirra,Andreeva,R,20070429.00,RUS,NaN,NaN,Mirra Andreeva,2024-560,...,5.00,10.00,4.00,12.00,23.00,2153.00,82.00,861.00,2024,us open-2024

In [115]:
wta_premios_top10 = wta_top10_grandSlams.iloc[:,[5,8,14,16,23,32,34,35,-1,-2]]
wta_premios_top10

,ioc,full_name,tourney_date,winner_id,winner_age,score,round,minutes,tourney_key,year
0,USA,Madison Keys,20110829,201619,16.50,6-2 6-4,R128,NaN,us open-2011,2011
1,USA,Madison Keys,20130114,201619,17.90,6-4 7-6(0),R128,NaN,australian open-2013,2013
2,USA,Madison Keys,20130114,201619,17.90,6-2 6-1,R64,NaN,australian open-2013,2013
3,USA,Madison Keys,20130527,201619,18.20,6-3 6-2,R128,NaN,roland garros-2013,2013
4,USA,Madison Keys,20130624,201619,18.30,6-3 7-5,R128,NaN,wimbledon-2013,2013
...,...,...,...,...,...,...,...,...,...,...
495,RUS,Mirra Andreeva,20240527,259799,17.00,6-3 3-6 7-5,R64,NaN,roland garros-2024,2024
496,RUS,Mirra Andreeva,20240527,259799,17.00,6-2 6-1,R32,NaN,roland garros-2024,2024
497,RUS,Mirra Andreeva,20240527,259799,17.00,7-5 6-2,R16,NaN,roland garros-2024,2024
498,RUS,Mirra Andreeva,20240527,259799,17.00,6-7(5) 6-4 6-4,QF,NaN,roland garros-2024,2024
499,RUS,Mirra Andreeva,20240826,259799,17.30,6-2 7-6(4),R128,98.00,us open-2024,2024

In [ ]:
wta_premios_top10.to_csv('wta top 10.csv')

In [160]:
wta_premios_top10.rename(columns={'tourney_key': 'tourney key'}, inplace=True)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_16148\1818250900.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wta_premios_top10.rename(columns={'tourney_key': 'tourney key'}, inplace=True)

In [172]:
wta_top10 = wta_premios_top10.rename(columns={'tourney key': 'tourney_key'})
premios = premios.rename(columns={'tourney key': 'tourney_key'})

# normalizar el texto de las llaves
def clean_key(x):
    return x.lower().replace(" - ", "-").strip()

wta_top10["tourney_key"] = wta_top10["tourney_key"].apply(clean_key)
premios["tourney_key"] = premios["tourney_key"].apply(clean_key)

# ahora sí hacer el merge
wta_filter_premio = pd.merge(
    wta_top10,
    premios,
    how="left",
    on=["tourney_key", "year", "round"]
)

wta_filter_premio

,ioc,full_name,tourney_date,winner_id,winner_age,score,round,minutes,tourney_key,year,premio €
0,USA,Madison Keys,20110829,201619,16.50,6-2 6-4,R128,NaN,us open-2011,2011,79392.53
1,USA,Madison Keys,20130114,201619,17.90,6-4 7-6(0),R128,NaN,australian open-2013,2013,100172.26
2,USA,Madison Keys,20130114,201619,17.90,6-2 6-1,R64,NaN,australian open-2013,2013,151776.16
3,USA,Madison Keys,20130527,201619,18.20,6-3 6-2,R128,NaN,roland garros-2013,2013,59192.70
4,USA,Madison Keys,20130624,201619,18.30,6-3 7-5,R128,NaN,wimbledon-2013,2013,50086.13
...,...,...,...,...,...,...,...,...,...,...,...
495,RUS,Mirra Andreeva,20240527,259799,17.00,6-3 3-6 7-5,R64,NaN,roland garros-2024,2024,117000.00
496,RUS,Mirra Andreeva,20240527,259799,17.00,6-2 6-1,R32,NaN,roland garros-2024,2024,168000.00
497,RUS,Mirra Andreeva,20240527,259799,17.00,7-5 6-2,R16,NaN,roland garros-2024,2024,265000.00
498,RUS,Mirra Andreeva,20240527,259799,17.00,6-7(5) 6-4 6-4,QF,NaN,roland garros-2024,2024,440000.00
499,RUS,Mirra Andreeva,20240826,259799,17.30,6-2 7-6(4),R128,98.00,us open-2024,2024,110000.00

In [179]:
wta_filter_premio

,ioc,full_name,tourney_date,winner_id,winner_age,score,round,minutes,tourney_key,year,premio €
0,USA,Madison Keys,20110829,201619,16.50,6-2 6-4,R128,NaN,us open-2011,2011,79392.53
1,USA,Madison Keys,20130114,201619,17.90,6-4 7-6(0),R128,NaN,australian open-2013,2013,100172.26
2,USA,Madison Keys,20130114,201619,17.90,6-2 6-1,R64,NaN,australian open-2013,2013,151776.16
3,USA,Madison Keys,20130527,201619,18.20,6-3 6-2,R128,NaN,roland garros-2013,2013,59192.70
4,USA,Madison Keys,20130624,201619,18.30,6-3 7-5,R128,NaN,wimbledon-2013,2013,50086.13
...,...,...,...,...,...,...,...,...,...,...,...
495,RUS,Mirra Andreeva,20240527,259799,17.00,6-3 3-6 7-5,R64,NaN,roland garros-2024,2024,117000.00
496,RUS,Mirra Andreeva,20240527,259799,17.00,6-2 6-1,R32,NaN,roland garros-2024,2024,168000.00
497,RUS,Mirra Andreeva,20240527,259799,17.00,7-5 6-2,R16,NaN,roland garros-2024,2024,265000.00
498,RUS,Mirra Andreeva,20240527,259799,17.00,6-7(5) 6-4 6-4,QF,NaN,roland garros-2024,2024,440000.00
499,RUS,Mirra Andreeva,20240826,259799,17.30,6-2 7-6(4),R128,98.00,us open-2024,2024,110000.00

In [173]:
# 1. quedarnos solo con finales
wta_finalistas = wta_top10[wta_top10["round"] == "F"]

# 2. normalizar las keys igual que hicimos antes
def clean_key(x):
    return x.lower().replace(" - ", "-").strip()

wta_finalistas["tourney_key"] = wta_finalistas["tourney_key"].apply(clean_key)
premios["tourney_key"] = premios["tourney_key"].apply(clean_key)

# 3. merge con premios
wta_campeonas_premio = pd.merge(
    wta_finalistas,
    premios,
    how="left",
    on=["tourney_key", "year", "round"]
)

# 4. ver la tabla final
wta_campeonas_premio = wta_campeonas_premio[["year","tourney_key","full_name","winner_id","premio €"]]

C:\Users\Usuario\AppData\Local\Temp\ipykernel_16148\3547787787.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wta_finalistas["tourney_key"] = wta_finalistas["tourney_key"].apply(clean_key)

In [ ]:
wta_campeonas_premio

   year           tourney_key        full_name  winner_id   premio €
0  2023  australian open-2023  Aryna Sabalenka     214544 1852935.44
1  2024  australian open-2024  Aryna Sabalenka     214544 1900000.00
2  2024          us open-2024  Aryna Sabalenka     214544 2500000.00
3  2020    roland garros-2020      Iga Swiatek     216347 1153285.77
4  2022    roland garros-2022      Iga Swiatek     216347 1212616.74
5  2022          us open-2022      Iga Swiatek     216347 2377679.88
6  2023    roland garros-2023      Iga Swiatek     216347 1243417.20
7  2024    roland garros-2024      Iga Swiatek     216347 1275000.00
8  2023          us open-2023       Coco Gauff     221103 2438072.95

In [181]:
# función para separar nombre y año
def split_tourney(x):
    parts = x.split("-")
    name = parts[0].strip()
    year = parts[-1].strip() if parts[-1].isdigit() else None
    return name, year

# aplicar a wta_top10
wta_filter_premio[["tourney_name","tourney_year_from_key"]] = wta_top10["tourney_key"].apply(
    lambda x: pd.Series(split_tourney(x))
)

# aplicar a premios
premios[["tourney_name","tourney_year_from_key"]] = premios["tourney_key"].apply(
    lambda x: pd.Series(split_tourney(x))
)

# y también a la tabla de campeonas
wta_campeonas_premio[["tourney_name","tourney_year_from_key"]] = wta_campeonas_premio["tourney_key"].apply(
    lambda x: pd.Series(split_tourney(x))
)

In [ ]:
wta_campeonas_premio

,year,tourney_key,full_name,winner_id,premio €,tourney_name,tourney_year_from_key
0,2023,australian open-2023,Aryna Sabalenka,214544,1852935.44,australian open,2023
1,2024,australian open-2024,Aryna Sabalenka,214544,1900000.00,australian open,2024
2,2024,us open-2024,Aryna Sabalenka,214544,2500000.00,us open,2024
3,2020,roland garros-2020,Iga Swiatek,216347,1153285.77,roland garros,2020
4,2022,roland garros-2022,Iga Swiatek,216347,1212616.74,roland garros,2022
5,2022,us open-2022,Iga Swiatek,216347,2377679.88,us open,2022
6,2023,roland garros-2023,Iga Swiatek,216347,1243417.20,roland garros,2023
7,2024,roland garros-2024,Iga Swiatek,216347,1275000.00,roland garros,2024
8,2023,us open-2023,Coco Gauff,221103,2438072.95,us open,2023

In [183]:
wta_campeonas_premio.to_csv('wta campeonas premio.csv',index=False)

In [182]:
wta_filter_premio

,ioc,full_name,tourney_date,winner_id,winner_age,score,round,minutes,tourney_key,year,premio €,tourney_name,tourney_year_from_key
0,USA,Madison Keys,20110829,201619,16.50,6-2 6-4,R128,NaN,us open-2011,2011,79392.53,us open,2011
1,USA,Madison Keys,20130114,201619,17.90,6-4 7-6(0),R128,NaN,australian open-2013,2013,100172.26,australian open,2013
2,USA,Madison Keys,20130114,201619,17.90,6-2 6-1,R64,NaN,australian open-2013,2013,151776.16,australian open,2013
3,USA,Madison Keys,20130527,201619,18.20,6-3 6-2,R128,NaN,roland garros-2013,2013,59192.70,roland garros,2013
4,USA,Madison Keys,20130624,201619,18.30,6-3 7-5,R128,NaN,wimbledon-2013,2013,50086.13,wimbledon,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,RUS,Mirra Andreeva,20240527,259799,17.00,6-3 3-6 7-5,R64,NaN,roland garros-2024,2024,117000.00,roland garros,2024
496,RUS,Mirra Andreeva,20240527,259799,17.00,6-2 6-1,R32,NaN,roland garros-2024,2024,168000.00,roland garros,2024
497,RUS,Mirra Andreeva,20240527,259799,17.00,7-5 6-2,R16,NaN,roland garros-2024,2024,265000.00,roland garros,2024
498,RUS,Mirra Andreeva,20240527,259799,17.00,6-7(5) 6-4 6-4,QF,NaN,roland garros-2024,2024,440000.00,roland garros,2024
499,RUS,Mirra Andreeva,20240826,259799,17.30,6-2 7-6(4),R128,98.00,us open-2024,2024,110000.00,us open,2024

In [184]:
wta_filter_premio.to_csv('wta premio rondas.csv',index=False)

## <span style="color: rgb(230, 0, 126);">__________________________________________________________________________________________________________________</span>
## <span style="color: rgb(230, 0, 126);">__________________________________________________________________________________________________________________</span>

ATTENDANCE AND TV VIEWERS

In [88]:
import pandas as pd
import numpy as np

# años de análisis
years = list(range(2000, 2025))

# torneos base
tournaments = ["Australian Open", "Roland Garros", "Wimbledon", "US Open"]

# diccionario auxiliar con info de cada torneo
tournament_info = {
    "Australian Open": {"region": "Oceania", "surface": "Hard", "capacity": 900000},
    "Roland Garros": {"region": "Europe", "surface": "Clay", "capacity": 650000},
    "Wimbledon": {"region": "Europe", "surface": "Grass", "capacity": 500000},
    "US Open": {"region": "North America", "surface": "Hard", "capacity": 850000}
}

# crear dataset sintético
data = []
for year in years:
    for t in tournaments:
        capacity = tournament_info[t]["capacity"]

        # asistencia realista con algo de variabilidad
        attendance = np.random.randint(int(capacity*0.7), int(capacity*1.05))

        # distribución demográfica estimada
        pct_under_30 = np.random.uniform(25, 40)
        pct_over_50 = np.random.uniform(20, 35)
        pct_female = np.random.uniform(40, 50)
        pct_male = 100 - pct_female

        # métricas de TV y sesiones nocturnas
        tv_viewers_millions = np.random.uniform(40, 120)
        night_sessions = np.random.randint(5, 15)

        # cálculo de utilización
        utilization_rate = attendance / capacity

        data.append({
            "tournament": t,
            "year": year,
            "attendance": attendance,
            "capacity": capacity,
            "utilization_rate": utilization_rate,
            "pct_under_30": pct_under_30,
            "pct_over_50": pct_over_50,
            "pct_female": pct_female,
            "pct_male": pct_male,
            "region": tournament_info[t]["region"],
            "surface": tournament_info[t]["surface"],
            "tv_viewers_millions": tv_viewers_millions,
            "night_sessions": night_sessions
        })

# convertir a dataframe
df = pd.DataFrame(data)

# guardar csv final
df.to_csv("grand_slams_attendance_final_2000_2024_edit.csv", index=False)

print(df.head())

        tournament  year  attendance  capacity  utilization_rate  \
0  Australian Open  2000      636708    900000              0.71
1    Roland Garros  2000      582906    650000              0.90
2        Wimbledon  2000      431648    500000              0.86
3          US Open  2000      628710    850000              0.74
4  Australian Open  2001      937898    900000              1.04

   pct_under_30  pct_over_50  pct_female  pct_male         region surface  \
0         25.32        31.93       44.13     55.87        Oceania    Hard
1         30.65        34.71       49.94     50.06         Europe    Clay
2         29.01        25.27       41.06     58.94         Europe   Grass
3         35.22        32.68       40.27     59.73  North America    Hard
4         36.57        29.88       40.26     59.74        Oceania    Hard

   tv_viewers_millions  night_sessions
0                75.80               6
1                89.91              11
2                79.25              14
3               112.45               8
4                93.46               6

FUNCTION STATS JUGADORES

In [89]:
def stats_totales_auto(df, jugadores, path_salida="./", plantilla_cols=None, referencia_csv=None):
    import os
    import numpy as np
    import pandas as pd

    # cargar columnas-plantilla para respetar nombre y orden (sinner)
    if plantilla_cols is None and referencia_csv is not None:
        plantilla_cols = list(pd.read_csv(referencia_csv, nrows=1).columns)

    # si no hay plantilla, usamos un orden razonable similar al de sinner
    if plantilla_cols is None:
        plantilla_cols = [
            'tourney_name','round','year',
            'total_2ndWon','total_1stIn','total_bpFaced',
            'total_1stWon','total_SvGms','total_df',
            'total_bpSaved','total_ace',
            '%aces_por_punto','%doble_falta',
            '%primer_serve_in','%primer_serve_won','%segundo_serve_won',
            '%bp_saved','%bp_convertidos','%juegos_de_saques_ganados'
        ]

    # eliminar el duplicado de la plantilla si aparece
    plantilla_cols = [c for c in plantilla_cols if c != 'total Ace']

    # extras que agregaremos SIN alterar el orden de la plantilla (van al final)
    extras_a_agregar = [
        '%puntos_ganados_con_servicio',  # nueva métrica
        'total_svpt',                     # serve points total (nuevo si falta)
        'w_ace', 'l_ace'                  # preservar ace por lado
    ]

    os.makedirs(path_salida, exist_ok=True)

    for jugador in jugadores['full_name']:
        df_j = df[(df['winner_name'] == jugador) | (df['loser_name'] == jugador)].copy()
        if df_j.empty:
            continue

        # agrupar
        g = df_j.groupby(['tourney_name','round','year']).sum(numeric_only=True).reset_index()

        # detectar métricas w_ / l_
        w_cols = [c for c in g.columns if c.startswith('w_')]
        l_cols = [c for c in g.columns if c.startswith('l_')]
        w_metrics = {c[2:]: c for c in w_cols}
        l_metrics = {c[2:]: c for c in l_cols}

        # crear totales (w_ + l_)
        for m in (w_metrics.keys() & l_metrics.keys()):
            g[f'total_{m}'] = g[w_metrics[m]] + g[l_metrics[m]]

        # asegurar total_ace y total_svpt
        if 'total_ace' not in g.columns and 'ace' in w_metrics and 'ace' in l_metrics:
            g['total_ace'] = g[w_metrics['ace']] + g[l_metrics['ace']]
        if 'total_svpt' not in g.columns and 'svpt' in w_metrics and 'svpt' in l_metrics:
            g['total_svpt'] = g[w_metrics['svpt']] + g[l_metrics['svpt']]

        # ratios
        def _den(df, expr):
            if isinstance(expr, str) and '-' in expr:
                a, b = [x.strip() for x in expr.split('-')]
                return df[a] - df[b]
            return df[expr]

        ratios = {
            '%aces_por_punto': ('total_ace', 'total_svpt'),
            '%doble_falta': ('total_df', 'total_svpt'),
            '%primer_serve_in': ('total_1stIn', 'total_svpt'),
            '%primer_serve_won': ('total_1stWon', 'total_1stIn'),
            '%segundo_serve_won': ('total_2ndWon', 'total_svpt - total_1stIn'),
            '%bp_saved': ('total_bpSaved', 'total_bpFaced'),
            '%bp_convertidos': ('total_bpSaved', 'total_bpFaced'),   # igual que tu sinner
            '%juegos_de_saques_ganados': ('total_SvGms', 'total_SvGms')  # mantiene 100 como en sinner
        }

        for col_name, (num, den) in ratios.items():
            if num in g.columns and (den.split('-')[0].strip() if '-' in den else den) in g.columns:
                dv = _den(g, den)
                g[col_name] = np.where(dv != 0, (g[num] / dv) * 100, np.nan)

        # nueva métrica: % puntos ganados con el servicio
        if {'total_svpt','total_1stWon','total_2ndWon'}.issubset(g.columns):
            g['%puntos_ganados_con_servicio'] = np.where(
                g['total_svpt'] != 0,
                (g['total_1stWon'] + g['total_2ndWon']) / g['total_svpt'] * 100,
                np.nan
            )

        # quitar duplicado si existe
        if 'total Ace' in g.columns and 'total_ace' in g.columns:
            g = g.drop(columns=['total Ace'])

        # construir orden final: plantilla (solo las que existan) + extras presentes
        orden_final = [c for c in plantilla_cols if c in g.columns]
        for extra in extras_a_agregar:
            if extra in g.columns and extra not in orden_final:
                orden_final.append(extra)

        # no borrar w_ace ni l_ace (ya incluidos arriba si existen)
        # exportar
        out = g[orden_final].copy()
        filename = f"{path_salida}/{jugador.replace(' ', '_')}_stats.csv"
        out.to_csv(filename, index=False)
        print(f"guardado: {filename}")

In [92]:
# df = tu dataframe de partidos
# jugadores = dataframe con al menos la columna 'full_name'
stats_totales_auto(wta_grand_slams, df_wta_players_top10, path_salida="./csv_jugadoras")

guardado: ./csv_jugadoras/Madison_Keys_stats.csv
guardado: ./csv_jugadoras/Jessica_Pegula_stats.csv
guardado: ./csv_jugadoras/Jasmine_Paolini_stats.csv
guardado: ./csv_jugadoras/Paula_Badosa_stats.csv
guardado: ./csv_jugadoras/Aryna_Sabalenka_stats.csv
guardado: ./csv_jugadoras/Amanda_Anisimova_stats.csv
guardado: ./csv_jugadoras/Iga_Swiatek_stats.csv
guardado: ./csv_jugadoras/Qinwen_Zheng_stats.csv
guardado: ./csv_jugadoras/Coco_Gauff_stats.csv
guardado: ./csv_jugadoras/Mirra_Andreeva_stats.csv

In [93]:
names = df_wta_players_top10['full_name']
names

1620         Madison Keys
2469       Jessica Pegula
11149     Jasmine Paolini
11652        Paula Badosa
14545     Aryna Sabalenka
16154    Amanda Anisimova
16348         Iga Swiatek
21003        Qinwen Zheng
21094          Coco Gauff
59789      Mirra Andreeva
Name: full_name, dtype: object