In [1]:
import pandas as pd

In [19]:
atp2024 = pd.read_csv('atp_matches_2022.csv')
atp2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2917 entries, 0 to 2916
Data columns (total 49 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tourney_id          2917 non-null   object
 1   tourney_name        2917 non-null   object
 2   surface             2917 non-null   object
 3   draw_size           2917 non-null   int64
 4   tourney_level       2917 non-null   object
 5   tourney_date        2917 non-null   int64
 6   match_num           2917 non-null   int64
 7   winner_id           2917 non-null   int64
 8   winner_seed         1220 non-null   float64
 9   winner_entry        428 non-null    object
 10  winner_name         2917 non-null   object
 11  winner_hand         2917 non-null   object
 12  winner_ht           2908 non-null   float64
 13  winner_ioc          2917 non-null   object
 14  winner_age          2916 non-null   float64
 15  loser_id            2917 non-null   int64
 16  loser_seed          705 non-null    float64
 17  loser_entry         654 non-null    object
 18  loser_name          2917 non-null   object
 19  loser_hand          2917 non-null   object
 20  loser_ht            2892 non-null   float64
 21  loser_ioc           2917 non-null   object
 22  loser_age           2917 non-null   float64
 23  score               2917 non-null   object
 24  best_of             2917 non-null   int64
 25  round               2917 non-null   object
 26  minutes             2637 non-null   float64
 27  w_ace               2745 non-null   float64
 28  w_df                2745 non-null   float64
 29  w_svpt              2745 non-null   float64
 30  w_1stIn             2745 non-null   float64
 31  w_1stWon            2745 non-null   float64
 32  w_2ndWon            2745 non-null   float64
 33  w_SvGms             2745 non-null   float64
 34  w_bpSaved           2745 non-null   float64
 35  w_bpFaced           2745 non-null   float64
 36  l_ace               2745 non-null   float64
 37  l_df                2745 non-null   float64
 38  l_svpt              2745 non-null   float64
 39  l_1stIn             2745 non-null   float64
 40  l_1stWon            2745 non-null   float64
 41  l_2ndWon            2745 non-null   float64
 42  l_SvGms             2745 non-null   float64
 43  l_bpSaved           2745 non-null   float64
 44  l_bpFaced           2745 non-null   float64
 45  winner_rank         2910 non-null   float64
 46  winner_rank_points  2910 non-null   float64
 47  loser_rank          2899 non-null   float64
 48  loser_rank_points   2899 non-null   float64
dtypes: float64(29), int64(6), object(14)
memory usage: 1.1+ MB

In [20]:
players = pd.read_csv('atp_players.csv')
players

C:\Users\Usuario\AppData\Local\Temp\ipykernel_35520\4038618507.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  players = pd.read_csv('atp_players.csv')

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id
0,100001,Gardnar,Mulloy,R,19131122.0,USA,185.0,Q54544
1,100002,Pancho,Segura,R,19210620.0,ECU,168.0,Q54581
2,100003,Frank,Sedgman,R,19271002.0,AUS,180.0,Q962049
3,100004,Giuseppe,Merlo,R,19271011.0,ITA,NaN,Q1258752
4,100005,Richard,Gonzalez,R,19280509.0,USA,188.0,Q53554
...,...,...,...,...,...,...,...,...
65984,213700,Matvei,Kobiakov,U,NaN,RUS,NaN,NaN
65985,213701,Tobia Costanzo,Baragiola Mordini,U,NaN,ITA,NaN,NaN
65986,213702,Dominik,Wijntjes,U,NaN,NZL,NaN,NaN
65987,213703,Sam,Wensley,U,NaN,AUS,NaN,NaN
65988,213704,Harry,Roberts,U,NaN,AUS,NaN,NaN

In [21]:
players_atp2024 = pd.merge(players,atp2024,how='inner',left_on='player_id',right_on='winner_id')
players_atp2024.head(50)

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,tourney_id,tourney_name,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-8888,Atp Cup,...,37.0,26.0,13.0,9.0,4.0,6.0,3.0,7840.0,12.0,2945.0
1,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-8888,Atp Cup,...,33.0,24.0,13.0,10.0,0.0,2.0,3.0,7840.0,23.0,2050.0
2,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-580,Australian Open,...,73.0,48.0,22.0,15.0,14.0,18.0,3.0,7970.0,87.0,792.0
3,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-580,Australian Open,...,39.0,18.0,21.0,13.0,3.0,9.0,3.0,7970.0,89.0,788.0
4,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-580,Australian Open,...,49.0,34.0,16.0,14.0,3.0,6.0,3.0,7970.0,124.0,587.0
5,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-0375,Montpellier,...,26.0,13.0,8.0,8.0,0.0,5.0,3.0,7780.0,83.0,793.0
6,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-0375,Montpellier,...,14.0,8.0,3.0,7.0,4.0,10.0,3.0,7780.0,58.0,1049.0
7,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-0375,Montpellier,...,40.0,27.0,8.0,10.0,1.0,4.0,3.0,7780.0,56.0,1119.0
8,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-0807,Acapulco,...,70.0,48.0,26.0,15.0,3.0,5.0,3.0,7515.0,47.0,1153.0
9,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-0403,Miami Masters,...,41.0,32.0,12.0,10.0,6.0,8.0,4.0,7025.0,97.0,700.0
10,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-0403,Miami Masters,...,40.0,24.0,9.0,8.0,4.0,8.0,4.0,7025.0,54.0,981.0
11,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-0403,Miami Masters,...,51.0,33.0,20.0,14.0,1.0,3.0,4.0,7025.0,166.0,359.0
12,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-0410,Monte Carlo Masters,...,55.0,40.0,17.0,16.0,3.0,8.0,3.0,7195.0,12.0,3054.0
13,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-0410,Monte Carlo Masters,...,47.0,27.0,10.0,10.0,9.0,14.0,3.0,7195.0,19.0,2015.0
14,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-0410,Monte Carlo Masters,...,41.0,18.0,12.0,10.0,5.0,11.0,3.0,7195.0,34.0,1279.0
15,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-1536,Madrid Masters,...,43.0,32.0,19.0,14.0,2.0,5.0,3.0,7420.0,5.0,5690.0
16,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-1536,Madrid Masters,...,49.0,32.0,13.0,11.0,6.0,10.0,3.0,7420.0,10.0,3625.0
17,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-1536,Madrid Masters,...,20.0,12.0,4.0,5.0,0.0,2.0,3.0,7420.0,63.0,896.0
18,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-1536,Madrid Masters,...,55.0,42.0,14.0,15.0,6.0,9.0,3.0,7420.0,24.0,1695.0
19,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-0416,Rome Masters,...,43.0,29.0,5.0,10.0,7.0,11.0,3.0,7020.0,45.0,1033.0
20,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-0416,Rome Masters,...,50.0,26.0,19.0,10.0,5.0,9.0,3.0,7020.0,22.0,1691.0
21,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-0416,Rome Masters,...,30.0,26.0,15.0,10.0,0.0,1.0,3.0,7020.0,37.0,1163.0
22,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-520,Roland Garros,...,56.0,39.0,16.0,14.0,11.0,15.0,3.0,7075.0,219.0,255.0
23,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-520,Roland Garros,...,94.0,58.0,18.0,22.0,4.0,11.0,3.0,7075.0,36.0,1178.0
24,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-520,Roland Garros,...,110.0,64.0,11.0,16.0,5.0,7.0,3.0,7075.0,75.0,827.0
25,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-520,Roland Garros,...,85.0,37.0,15.0,16.0,1.0,9.0,3.0,7075.0,131.0,475.0
26,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-520,Roland Garros,...,81.0,58.0,26.0,21.0,5.0,8.0,3.0,7075.0,6.0,4648.0
27,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-M-DC-2022-QLS-M-GER-BRA-01,Davis Cup QLS R1: GER vs BRA,...,41.0,25.0,7.0,9.0,6.0,9.0,3.0,7515.0,216.0,267.0
28,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,2022-M-DC-2022-QLS-M-GER-BRA-01,Davis Cup QLS R1: GER vs BRA,...,35.0,25.0,8.0,9.0,2.0,5.0,3.0,7515.0,114.0,600.0
29,103499,Aqeel,Khan,R,19800130.0,PAK,NaN,Q4782530,2022-M-DC-2022-WG1-PO-PAK-LTU-01,Davis Cup WG1 PO: PAK vs LTU,...,45.0,38.0,22.0,15.0,1.0,3.0,NaN,NaN,1016.0,11.0
30,103529,Aisam Ul Haq,Qureshi,R,19800317.0,PAK,183.0,Q409547,2022-M-DC-2022-WG1-PO-PAK-LTU-01,Davis Cup WG1 PO: PAK vs LTU,...,39.0,29.0,20.0,11.0,3.0,4.0,NaN,NaN,2119.0,1.0
31,104259,Philipp,Kohlschreiber,R,19831016.0,GER,178.0,Q77149,2022-580,Australian Open,...,66.0,45.0,23.0,17.0,5.0,7.0,134.0,533.0,95.0,759.0
32,104269,Fernando,Verdasco,L,19831115.0,ESP,188.0,Q191740,2022-0506,Buenos Aires,...,63.0,47.0,11.0,14.0,5.0,8.0,201.0,325.0,104.0,680.0
33,104269,Fernando,Verdasco,L,19831115.0,ESP,188.0,Q191740,2022-0506,Buenos Aires,...,61.0,40.0,9.0,13.0,3.0,7.0,201.0,325.0,103.0,684.0
34,104269,Fernando,Verdasco,L,19831115.0,ESP,188.0,Q191740,2022-6932,Rio de Janeiro,...,50.0,35.0,6.0,10.0,2.0,5.0,172.0,370.0,39.0,1346.0
35,104269,Fernando,Verdasco,L,19831115.0,ESP,188.0,Q191740,2022-7290,Estoril,...,37.0,23.0,4.0,8.0,2.0,6.0,118.0,554.0,107.0,619.0
36,104269,Fernando,Verdasco,L,19831115.0,ESP,188.0,Q191740,2022-7434,Sofia,...,45.0,31.0,15.0,12.0,2.0,5.0,116.0,464.0,37.0,1185.0
37,104291,Malek,Jaziri,R,19840120.0,TUN,185.0,Q440477,2022-0360,Marrakech,...,55.0,32.0,12.0,12.0,5.0,10.0,329.0,134.0,69.0,860.0
38,104312,Andreas,Seppi,R,19840221.0,ITA,190.0,Q319572,2022-0424,Dallas,...,56.0,39.0,11.0,14.0,6.0,10.0,100.0,704.0,81.0,803.0
39,104312,Andreas,Seppi,R,19840221.0,ITA,190.0,Q319572,2022-0499,Delray Beach,...,36.0,22.0,10.0,11.0,2.0,7.0,123.0,574.0,96.0,713.0
40,104468,Gilles,Simon,R,19841227.0,FRA,183.0,Q212833,2022-0375,Montpellier,...,63.0,47.0,26.0,17.0,5.0,8.0,130.0,553.0,156.0,442.0
41,104468,Gilles,Simon,R,19841227.0,FRA,183.0,Q212833,2022-520,Roland Garros,...,93.0,59.0,22.0,24.0,4.0,13.0,158.0,391.0,18.0,2135.0
42,104468,Gilles,Simon,R,19841227.0,FRA,183.0,Q212833,2022-520,Roland Garros,...,64.0,39.0,16.0,15.0,10.0,17.0,158.0,391.0,92.0,689.0
43,104468,Gilles,Simon,R,19841227.0,FRA,183.0,Q212833,2022-0440,s Hertogenbosch,...,40.0,29.0,25.0,11.0,5.0,7.0,134.0,481.0,71.0,853.0
44,104468,Gilles,Simon,R,19841227.0,FRA,183.0,Q212833,2022-0341,Metz,...,33.0,23.0,12.0,9.0,4.0,8.0,175.0,302.0,62.0,770.0
45,104468,Gilles,Simon,R,19841227.0,FRA,183.0,Q212833,2022-0352,Paris Masters,...,65.0,46.0,23.0,17.0,7.0,11.0,188.0,295.0,11.0,3090.0
46,104468,Gilles,Simon,R,19841227.0,FRA,183.0,Q212833,2022-0352,Paris Masters,...,49.0,34.0,16.0,16.0,6.0,12.0,188.0,295.0,48.0,955.0
47,104527,Stan,Wawrinka,R,19850328.0,SUI,183.0,Q193661,2022-0416,Rome Masters,...,71.0,47.0,32.0,16.0,9.0,11.0,361.0,119.0,58.0,931.0
48,104527,Stan,Wawrinka,R,19850328.0,SUI,183.0,Q193661,2022-0416,Rome Masters,...,56.0,39.0,18.0,15.0,8.0,12.0,361.0,119.0,17.0,2440.0
49,104527,Stan,Wawrinka,R,19850328.0,SUI,183.0,Q193661,2022-0311,Queen's Club,...,91.0,65.0,21.0,18.0,2.0,3.0,290.0,169.0,27.0,1519.0

In [22]:
atp2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2917 entries, 0 to 2916
Data columns (total 49 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tourney_id          2917 non-null   object
 1   tourney_name        2917 non-null   object
 2   surface             2917 non-null   object
 3   draw_size           2917 non-null   int64
 4   tourney_level       2917 non-null   object
 5   tourney_date        2917 non-null   int64
 6   match_num           2917 non-null   int64
 7   winner_id           2917 non-null   int64
 8   winner_seed         1220 non-null   float64
 9   winner_entry        428 non-null    object
 10  winner_name         2917 non-null   object
 11  winner_hand         2917 non-null   object
 12  winner_ht           2908 non-null   float64
 13  winner_ioc          2917 non-null   object
 14  winner_age          2916 non-null   float64
 15  loser_id            2917 non-null   int64
 16  loser_seed          705 non-null    float64
 17  loser_entry         654 non-null    object
 18  loser_name          2917 non-null   object
 19  loser_hand          2917 non-null   object
 20  loser_ht            2892 non-null   float64
 21  loser_ioc           2917 non-null   object
 22  loser_age           2917 non-null   float64
 23  score               2917 non-null   object
 24  best_of             2917 non-null   int64
 25  round               2917 non-null   object
 26  minutes             2637 non-null   float64
 27  w_ace               2745 non-null   float64
 28  w_df                2745 non-null   float64
 29  w_svpt              2745 non-null   float64
 30  w_1stIn             2745 non-null   float64
 31  w_1stWon            2745 non-null   float64
 32  w_2ndWon            2745 non-null   float64
 33  w_SvGms             2745 non-null   float64
 34  w_bpSaved           2745 non-null   float64
 35  w_bpFaced           2745 non-null   float64
 36  l_ace               2745 non-null   float64
 37  l_df                2745 non-null   float64
 38  l_svpt              2745 non-null   float64
 39  l_1stIn             2745 non-null   float64
 40  l_1stWon            2745 non-null   float64
 41  l_2ndWon            2745 non-null   float64
 42  l_SvGms             2745 non-null   float64
 43  l_bpSaved           2745 non-null   float64
 44  l_bpFaced           2745 non-null   float64
 45  winner_rank         2910 non-null   float64
 46  winner_rank_points  2910 non-null   float64
 47  loser_rank          2899 non-null   float64
 48  loser_rank_points   2899 non-null   float64
dtypes: float64(29), int64(6), object(14)
memory usage: 1.1+ MB

In [23]:

countTorneos = players_atp2024.groupby(['name_first','name_last'])[['tourney_name']].count().sort_values(by='tourney_name',ascending=False)

top40 = countTorneos[countTorneos['tourney_name'] >= 40]

top40

                            tourney_name
name_first name_last
Stefanos   Tsitsipas                  61
Felix      Auger Aliassime            60
Carlos     Alcaraz                    57
Casper     Ruud                       51
Andrey     Rublev                     51
Cameron    Norrie                     49
Jannik     Sinner                     47
Alex       De Minaur                  47
Taylor     Fritz                      47
Daniil     Medvedev                   45
Novak      Djokovic                   43
Hubert     Hurkacz                    41
Holger     Rune                       40
Roberto    Bautista Agut              40
Rafael     Nadal                      40
Nick       Kyrgios                    40

In [24]:
wimbledon = players_atp2024[players_atp2024['tourney_name'] == 'Wimbledon']

In [25]:
wimbledon

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,tourney_id,tourney_name,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
70,104545,John,Isner,R,19850426.0,USA,208.0,Q53566,2022-540,Wimbledon,...,116.0,86.0,35.0,28.0,5.0,7.0,24.0,1616.0,206.0,276.0
71,104545,John,Isner,R,19850426.0,USA,208.0,Q53566,2022-540,Wimbledon,...,75.0,61.0,32.0,23.0,1.0,3.0,24.0,1616.0,52.0,995.0
124,104745,Rafael,Nadal,L,19860603.0,ESP,185.0,Q10132,2022-540,Wimbledon,...,87.0,55.0,20.0,19.0,8.0,14.0,4.0,6525.0,41.0,1070.0
125,104745,Rafael,Nadal,L,19860603.0,ESP,185.0,Q10132,2022-540,Wimbledon,...,84.0,57.0,20.0,19.0,12.0,16.0,4.0,6525.0,106.0,545.0
126,104745,Rafael,Nadal,L,19860603.0,ESP,185.0,Q10132,2022-540,Wimbledon,...,43.0,24.0,12.0,12.0,2.0,8.0,4.0,6525.0,54.0,980.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2683,206909,Brandon,Nakashima,R,20010803.0,USA,188.0,Q60676610,2022-540,Wimbledon,...,52.0,35.0,21.0,13.0,12.0,16.0,56.0,969.0,109.0,528.0
2750,207733,Jack,Draper,L,20011222.0,GBR,193.0,Q65030599,2022-540,Wimbledon,...,65.0,46.0,17.0,16.0,2.0,5.0,94.0,627.0,146.0,403.0
2802,207989,Carlos,Alcaraz,R,20030505.0,ESP,183.0,Q85518537,2022-540,Wimbledon,...,113.0,88.0,47.0,28.0,12.0,14.0,7.0,4890.0,155.0,363.0
2803,207989,Carlos,Alcaraz,R,20030505.0,ESP,183.0,Q85518537,2022-540,Wimbledon,...,47.0,34.0,21.0,15.0,6.0,9.0,7.0,4890.0,53.0,984.0
2804,207989,Carlos,Alcaraz,R,20030505.0,ESP,183.0,Q85518537,2022-540,Wimbledon,...,53.0,33.0,13.0,12.0,14.0,20.0,7.0,4890.0,36.0,1155.0

In [27]:
AlcarazWimbledon = wimbledon[wimbledon['name_last'] == 'Alcaraz']

In [ ]:
print(AlcarazWimbledon.columns.tolist())

['player_id', 'name_first', 'name_last', 'hand', 'dob', 'ioc', 'height', 'wikidata_id', 'tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level', 'tourney_date', 'match_num', 'winner_id', 'winner_seed', 'winner_entry', 'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age', 'loser_id', 'loser_seed', 'loser_entry', 'loser_name', 'loser_hand', 'loser_ht', 'loser_ioc', 'loser_age', 'score', 'best_of', 'round', 'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon', 'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt', 'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced', 'winner_rank', 'winner_rank_points', 'loser_rank', 'loser_rank_points']

In [28]:
filt = AlcarazWimbledon[['w_1stIn', 'w_1stWon', 'w_2ndWon','l_1stIn', 'l_2ndWon', 'w_2ndWon']].sum()
filt

w_1stIn     210.0
w_1stWon    167.0
w_2ndWon     73.0
l_1stIn     213.0
l_2ndWon     81.0
w_2ndWon     73.0
dtype: float64

In [29]:
AlcarazWimbledon[['name_first','name_last', 'round','tourney_name','minutes','score','loser_name']]

,name_first,name_last,round,tourney_name,minutes,score,loser_name
2802,Carlos,Alcaraz,R128,Wimbledon,251.0,4-6 7-5 4-6 7-6(3) 6-4,Jan Lennard Struff
2803,Carlos,Alcaraz,R64,Wimbledon,126.0,6-4 7-6(0) 6-3,Tallon Griekspoor
2804,Carlos,Alcaraz,R32,Wimbledon,98.0,6-3 6-1 6-2,Oscar Otte

In [ ]:
import pandas as pd

In [30]:
filter = pd.read_csv('partidos_atp_2000_2024.csv')
df_US = filter[filter['tourney_name'] == 'US Open']
df_US

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
2384,2000-560,US Open,Hard,128,G,20000828,1,101736,1.0,NaN,...,30.0,13.0,12.0,5.0,12.0,1.0,3754.0,432.0,53.0,2000
2385,2000-560,US Open,Hard,128,G,20000828,2,103096,NaN,NaN,...,34.0,12.0,13.0,7.0,12.0,37.0,928.0,26.0,1067.0,2000
2386,2000-560,US Open,Hard,128,G,20000828,3,102271,NaN,NaN,...,58.0,32.0,23.0,10.0,19.0,41.0,889.0,92.0,448.0,2000
2387,2000-560,US Open,Hard,128,G,20000828,4,101965,NaN,NaN,...,41.0,13.0,17.0,5.0,13.0,21.0,1227.0,51.0,794.0,2000
2388,2000-560,US Open,Hard,128,G,20000828,5,103324,NaN,NaN,...,57.0,19.0,19.0,7.0,12.0,63.0,642.0,311.0,98.0,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61101,2019-560,US Open,Hard,128,G,20190826,222,126610,24.0,NaN,...,70.0,29.0,24.0,11.0,17.0,25.0,1535.0,13.0,2140.0,2019
61102,2019-560,US Open,Hard,128,G,20190826,223,104745,2.0,NaN,...,32.0,17.0,15.0,6.0,14.0,2.0,7945.0,21.0,1725.0,2019
61103,2019-560,US Open,Hard,128,G,20190826,224,106421,5.0,NaN,...,37.0,18.0,16.0,4.0,9.0,5.0,4125.0,78.0,722.0,2019
61104,2019-560,US Open,Hard,128,G,20190826,225,104745,2.0,NaN,...,52.0,17.0,16.0,12.0,16.0,2.0,7945.0,25.0,1535.0,2019
61105,2019-560,US Open,Hard,128,G,20190826,226,104745,2.0,NaN,...,76.0,35.0,26.0,15.0,21.0,2.0,7945.0,5.0,4125.0,2019

In [33]:
df_2022 = filter[filter['tourney_date'] == 20220829]
df_2022

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
68022,2022-560,Us Open,Hard,128,G,20220829,100,106421,1.0,NaN,...,25.0,7.0,12.0,8.0,16.0,1.0,6885.0,111.0,493.0,2022
68023,2022-560,Us Open,Hard,128,G,20220829,101,126239,NaN,NaN,...,56.0,23.0,19.0,9.0,14.0,58.0,805.0,76.0,667.0,2022
68024,2022-560,Us Open,Hard,128,G,20220829,102,132686,NaN,NaN,...,90.0,34.0,28.0,4.0,6.0,104.0,513.0,165.0,311.0,2022
68025,2022-560,Us Open,Hard,128,G,20220829,103,200059,NaN,NaN,...,29.0,9.0,12.0,4.0,9.0,174.0,301.0,35.0,1290.0,2022
68026,2022-560,Us Open,Hard,128,G,20220829,104,106401,23.0,NaN,...,47.0,14.0,15.0,3.0,5.0,25.0,1430.0,70.0,697.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68144,2022-560,Us Open,Hard,128,G,20220829,222,207989,3.0,NaN,...,75.0,43.0,27.0,15.0,26.0,4.0,5100.0,13.0,3020.0,2022
68145,2022-560,Us Open,Hard,128,G,20220829,223,126207,22.0,NaN,...,46.0,26.0,18.0,3.0,4.0,26.0,1400.0,11.0,3120.0,2022
68146,2022-560,Us Open,Hard,128,G,20220829,224,134770,5.0,NaN,...,57.0,19.0,20.0,7.0,13.0,7.0,4695.0,31.0,1315.0,2022
68147,2022-560,Us Open,Hard,128,G,20220829,225,207989,3.0,NaN,...,54.0,43.0,25.0,11.0,20.0,4.0,5100.0,26.0,1400.0,2022
68148,2022-560,Us Open,Hard,128,G,20220829,226,207989,3.0,NaN,...,47.0,30.0,20.0,8.0,11.0,4.0,5100.0,7.0,4695.0,2022

In [ ]:
df_2022_new = df_2022[df_2022['round'] == 'F']
df_2022_new

207989

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
68148,2022-560,Us Open,Hard,128,G,20220829,226,207989,3.0,NaN,...,47.0,30.0,20.0,8.0,11.0,4.0,5100.0,7.0,4695.0,2022

In [32]:
df_new = df_2022[df_2022['round'] == 'F']
df_new.tail(20)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
68148,2022-560,Us Open,Hard,128,G,20220829,226,207989,3.0,NaN,...,47.0,30.0,20.0,8.0,11.0,4.0,5100.0,7.0,4695.0,2022

________________________________________________________________________________________________________________________________________________________________________

________________________________________________________________________________________________________________________________________________________________________

PLAYERS CLEAN AND JOIN ROUNDS

In [2]:
import pandas as pd

In [3]:
players = pd.read_csv('atp_players.csv')

C:\Users\Usuario\AppData\Local\Temp\ipykernel_432\761637514.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  players = pd.read_csv('atp_players.csv')

In [4]:
players['full_name'] = players['name_first'] + " " + players['name_last']
players

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
0,100001,Gardnar,Mulloy,R,19131122.0,USA,185.0,Q54544,Gardnar Mulloy
1,100002,Pancho,Segura,R,19210620.0,ECU,168.0,Q54581,Pancho Segura
2,100003,Frank,Sedgman,R,19271002.0,AUS,180.0,Q962049,Frank Sedgman
3,100004,Giuseppe,Merlo,R,19271011.0,ITA,NaN,Q1258752,Giuseppe Merlo
4,100005,Richard,Gonzalez,R,19280509.0,USA,188.0,Q53554,Richard Gonzalez
...,...,...,...,...,...,...,...,...,...
65984,213700,Matvei,Kobiakov,U,NaN,RUS,NaN,NaN,Matvei Kobiakov
65985,213701,Tobia Costanzo,Baragiola Mordini,U,NaN,ITA,NaN,NaN,Tobia Costanzo Baragiola Mordini
65986,213702,Dominik,Wijntjes,U,NaN,NZL,NaN,NaN,Dominik Wijntjes
65987,213703,Sam,Wensley,U,NaN,AUS,NaN,NaN,Sam Wensley
65988,213704,Harry,Roberts,U,NaN,AUS,NaN,NaN,Harry Roberts

In [5]:
partidos = pd.read_csv('partidos_atp_2000_2024.csv')
partidos

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
0,2000-301,Auckland,Hard,32,A,20000110,1,103163,1.0,NaN,...,39.0,29.0,17.0,4.0,7.0,11.0,1612.0,63.0,595.0,2000
1,2000-301,Auckland,Hard,32,A,20000110,2,102607,NaN,Q,...,25.0,18.0,12.0,3.0,6.0,211.0,157.0,49.0,723.0,2000
2,2000-301,Auckland,Hard,32,A,20000110,3,103252,NaN,NaN,...,20.0,7.0,8.0,7.0,11.0,48.0,726.0,59.0,649.0,2000
3,2000-301,Auckland,Hard,32,A,20000110,4,103507,7.0,NaN,...,29.0,14.0,10.0,6.0,8.0,45.0,768.0,61.0,616.0,2000
4,2000-301,Auckland,Hard,32,A,20000110,5,102103,NaN,Q,...,34.0,18.0,12.0,5.0,9.0,167.0,219.0,34.0,873.0,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74901,2024-M-DC-2024-WG2-PO-URU-MDA-01,Davis Cup WG2 PO: URU vs MDA,Clay,4,D,20240203,5,212051,NaN,NaN,...,17.0,7.0,6.0,8.0,14.0,1109.0,8.0,740.0,34.0,2024
74902,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,1,122533,NaN,NaN,...,25.0,6.0,9.0,1.0,4.0,554.0,67.0,748.0,32.0,2024
74903,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,2,144748,NaN,NaN,...,25.0,7.0,11.0,5.0,12.0,416.0,109.0,NaN,NaN,2024
74904,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,4,122533,NaN,NaN,...,32.0,17.0,14.0,5.0,9.0,554.0,67.0,416.0,109.0,2024
74905,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,5,202475,NaN,NaN,...,25.0,8.0,8.0,9.0,14.0,748.0,32.0,NaN,NaN,2024

In [6]:
df_join = pd.merge(players,partidos,how='inner',left_on='player_id',right_on='winner_id')
df_join

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name,tourney_id,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
0,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,Alexander Zverev,2014-414,...,17.0,5.0,7.0,4.0,9.0,285.0,163.0,51.0,865.0,2014
1,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,Alexander Zverev,2014-414,...,25.0,21.0,12.0,7.0,11.0,285.0,163.0,19.0,1735.0,2014
2,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,Alexander Zverev,2014-414,...,35.0,13.0,11.0,3.0,5.0,285.0,163.0,32.0,1160.0,2014
3,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,Alexander Zverev,2014-414,...,29.0,22.0,14.0,7.0,11.0,285.0,163.0,83.0,629.0,2014
4,100644,Alexander,Zverev,R,19970420.0,GER,198.0,Q13990552,Alexander Zverev,2015-403,...,53.0,16.0,17.0,1.0,3.0,129.0,432.0,69.0,701.0,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74901,212051,Joaquin,Aguilar Cardozo,U,20050408.0,URU,NaN,NaN,Joaquin Aguilar Cardozo,2024-M-DC-2024-WG2-PO-URU-MDA-01,...,17.0,7.0,6.0,8.0,14.0,1109.0,8.0,740.0,34.0,2024
74902,212063,Matej,Dodig,R,20050719.0,CRO,188.0,NaN,Matej Dodig,2024-0439,...,29.0,21.0,13.0,6.0,9.0,310.0,172.0,205.0,292.0,2024
74903,212063,Matej,Dodig,R,20050719.0,CRO,188.0,NaN,Matej Dodig,2024-M-DC-2024-WG1-M-CRO-LTU-01,...,NaN,NaN,NaN,NaN,NaN,291.0,182.0,182.0,324.0,2024
74904,212720,Juan Carlos,Fuentes Vasquez,U,20050917.0,ESA,NaN,NaN,Juan Carlos Fuentes Vasquez,2024-M-DC-2024-WG2-PO-ESA-POC-01,...,19.0,8.0,7.0,5.0,10.0,NaN,NaN,NaN,NaN,2024
74905,212721,Benedict,Badza,U,20050519.0,ZIM,NaN,NaN,Benedict Badza,2024-M-DC-2024-WG2-PO-HKG-ZIM-01,...,35.0,17.0,11.0,0.0,2.0,NaN,NaN,NaN,NaN,2024

In [7]:
df_players_clean_Round = df_join.iloc[:,[0,8,5,3,6,10,14,23,58,34]]
df_players_clean_Round

,player_id,full_name,ioc,hand,height,tourney_name,tourney_date,winner_age,year,round
0,100644,Alexander Zverev,GER,R,198.0,Hamburg,20140714,17.2,2014,R64
1,100644,Alexander Zverev,GER,R,198.0,Hamburg,20140714,17.2,2014,R32
2,100644,Alexander Zverev,GER,R,198.0,Hamburg,20140714,17.2,2014,R16
3,100644,Alexander Zverev,GER,R,198.0,Hamburg,20140714,17.2,2014,QF
4,100644,Alexander Zverev,GER,R,198.0,Miami Masters,20150325,17.9,2015,R128
...,...,...,...,...,...,...,...,...,...,...
74901,212051,Joaquin Aguilar Cardozo,URU,U,NaN,Davis Cup WG2 PO: URU vs MDA,20240203,18.8,2024,RR
74902,212063,Matej Dodig,CRO,R,188.0,Umag,20240722,19.0,2024,R32
74903,212063,Matej Dodig,CRO,R,188.0,Davis Cup WG1 R1: CRO vs LTU,20240913,19.1,2024,RR
74904,212720,Juan Carlos Fuentes Vasquez,ESA,U,NaN,Davis Cup WG2 PO: ESA vs POC,20240202,18.3,2024,RR
74905,212721,Benedict Badza,ZIM,U,NaN,Davis Cup WG2 PO: HKG vs ZIM,20240203,18.6,2024,RR

In [8]:
df_players_clean_Round['tourney_name'] = df_players_clean_Round['tourney_name'].str.strip().str.lower()

C:\Users\Usuario\AppData\Local\Temp\ipykernel_432\2148772997.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_players_clean_Round['tourney_name'] = df_players_clean_Round['tourney_name'].str.strip().str.lower()

In [9]:
df_players_clean_Round['tourney key'] = df_players_clean_Round['tourney_name'] + " - " + df_players_clean_Round['year'].astype(str)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_432\307193020.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_players_clean_Round['tourney key'] = df_players_clean_Round['tourney_name'] + " - " + df_players_clean_Round['year'].astype(str)

In [10]:
df_players_clean_Round

,player_id,full_name,ioc,hand,height,tourney_name,tourney_date,winner_age,year,round,tourney key
0,100644,Alexander Zverev,GER,R,198.0,hamburg,20140714,17.2,2014,R64,hamburg - 2014
1,100644,Alexander Zverev,GER,R,198.0,hamburg,20140714,17.2,2014,R32,hamburg - 2014
2,100644,Alexander Zverev,GER,R,198.0,hamburg,20140714,17.2,2014,R16,hamburg - 2014
3,100644,Alexander Zverev,GER,R,198.0,hamburg,20140714,17.2,2014,QF,hamburg - 2014
4,100644,Alexander Zverev,GER,R,198.0,miami masters,20150325,17.9,2015,R128,miami masters - 2015
...,...,...,...,...,...,...,...,...,...,...,...
74901,212051,Joaquin Aguilar Cardozo,URU,U,NaN,davis cup wg2 po: uru vs mda,20240203,18.8,2024,RR,davis cup wg2 po: uru vs mda - 2024
74902,212063,Matej Dodig,CRO,R,188.0,umag,20240722,19.0,2024,R32,umag - 2024
74903,212063,Matej Dodig,CRO,R,188.0,davis cup wg1 r1: cro vs ltu,20240913,19.1,2024,RR,davis cup wg1 r1: cro vs ltu - 2024
74904,212720,Juan Carlos Fuentes Vasquez,ESA,U,NaN,davis cup wg2 po: esa vs poc,20240202,18.3,2024,RR,davis cup wg2 po: esa vs poc - 2024
74905,212721,Benedict Badza,ZIM,U,NaN,davis cup wg2 po: hkg vs zim,20240203,18.6,2024,RR,davis cup wg2 po: hkg vs zim - 2024

In [11]:
df_players_ATP_cleaned = df_players_clean_Round[(df_players_clean_Round['tourney_name'] == 'wimbledon')  
                                        + (df_players_clean_Round['tourney_name'] == 'us open')  
                                        + (df_players_clean_Round['tourney_name'] == 'australian open')  
                                        + (df_players_clean_Round['tourney_name'] == 'roland garros')]
df_players_ATP_cleaned

,player_id,full_name,ioc,hand,height,tourney_name,tourney_date,winner_age,year,round,tourney key
10,100644,Alexander Zverev,GER,R,198.0,wimbledon,20150629,18.1,2015,R128,wimbledon - 2015
39,100644,Alexander Zverev,GER,R,198.0,roland garros,20160523,19.0,2016,R128,roland garros - 2016
40,100644,Alexander Zverev,GER,R,198.0,roland garros,20160523,19.0,2016,R64,roland garros - 2016
45,100644,Alexander Zverev,GER,R,198.0,wimbledon,20160627,19.1,2016,R128,wimbledon - 2016
46,100644,Alexander Zverev,GER,R,198.0,wimbledon,20160627,19.1,2016,R64,wimbledon - 2016
...,...,...,...,...,...,...,...,...,...,...,...
74804,210150,Jakub Mensik,CZE,R,193.0,us open,20240826,18.9,2024,R64,us open - 2024
74834,210506,Alex Michelsen,USA,R,193.0,us open,20230828,19.0,2023,R128,us open - 2023
74835,210506,Alex Michelsen,USA,R,193.0,australian open,20240115,19.3,2024,R128,australian open - 2024
74836,210506,Alex Michelsen,USA,R,193.0,australian open,20240115,19.3,2024,R64,australian open - 2024
74858,210506,Alex Michelsen,USA,R,193.0,us open,20240826,20.0,2024,R128,us open - 2024

In [12]:
torneo_id_map = {
    'australian open': 1,
    'roland garros': 2,
    'wimbledon': 3,
    'us open': 4
}

df_players_ATP_cleaned['torneo_id'] = df_players_ATP_cleaned['tourney_name'].map(torneo_id_map)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_432\3884906889.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_players_ATP_cleaned['torneo_id'] = df_players_ATP_cleaned['tourney_name'].map(torneo_id_map)

In [13]:
df_players_ATP_cleaned

,player_id,full_name,ioc,hand,height,tourney_name,tourney_date,winner_age,year,round,tourney key,torneo_id
10,100644,Alexander Zverev,GER,R,198.0,wimbledon,20150629,18.1,2015,R128,wimbledon - 2015,3
39,100644,Alexander Zverev,GER,R,198.0,roland garros,20160523,19.0,2016,R128,roland garros - 2016,2
40,100644,Alexander Zverev,GER,R,198.0,roland garros,20160523,19.0,2016,R64,roland garros - 2016,2
45,100644,Alexander Zverev,GER,R,198.0,wimbledon,20160627,19.1,2016,R128,wimbledon - 2016,3
46,100644,Alexander Zverev,GER,R,198.0,wimbledon,20160627,19.1,2016,R64,wimbledon - 2016,3
...,...,...,...,...,...,...,...,...,...,...,...,...
74804,210150,Jakub Mensik,CZE,R,193.0,us open,20240826,18.9,2024,R64,us open - 2024,4
74834,210506,Alex Michelsen,USA,R,193.0,us open,20230828,19.0,2023,R128,us open - 2023,4
74835,210506,Alex Michelsen,USA,R,193.0,australian open,20240115,19.3,2024,R128,australian open - 2024,1
74836,210506,Alex Michelsen,USA,R,193.0,australian open,20240115,19.3,2024,R64,australian open - 2024,1
74858,210506,Alex Michelsen,USA,R,193.0,us open,20240826,20.0,2024,R128,us open - 2024,4

In [14]:
us = df_players_ATP_cleaned[df_players_ATP_cleaned['tourney_name'] == 'us open']
us

,player_id,full_name,ioc,hand,height,tourney_name,tourney_date,winner_age,year,round,tourney key,torneo_id
50,100644,Alexander Zverev,GER,R,198.0,us open,20160829,19.3,2016,R128,us open - 2016,4
108,100644,Alexander Zverev,GER,R,198.0,us open,20170828,20.3,2017,R128,us open - 2017,4
162,100644,Alexander Zverev,GER,R,198.0,us open,20180827,21.3,2018,R128,us open - 2018,4
163,100644,Alexander Zverev,GER,R,198.0,us open,20180827,21.3,2018,R64,us open - 2018,4
207,100644,Alexander Zverev,GER,R,198.0,us open,20190826,22.3,2019,R128,us open - 2019,4
...,...,...,...,...,...,...,...,...,...,...,...,...
74786,210150,Jakub Mensik,CZE,R,193.0,us open,20230828,17.9,2023,R64,us open - 2023,4
74803,210150,Jakub Mensik,CZE,R,193.0,us open,20240826,18.9,2024,R128,us open - 2024,4
74804,210150,Jakub Mensik,CZE,R,193.0,us open,20240826,18.9,2024,R64,us open - 2024,4
74834,210506,Alex Michelsen,USA,R,193.0,us open,20230828,19.0,2023,R128,us open - 2023,4
74858,210506,Alex Michelsen,USA,R,193.0,us open,20240826,20.0,2024,R128,us open - 2024,4

In [15]:
alcar = df_players_ATP_cleaned[df_players_ATP_cleaned['full_name'] == 'Carlos Alcaraz']
alcar

,player_id,full_name,ioc,hand,height,tourney_name,tourney_date,winner_age,year,round,tourney key,torneo_id
73795,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20210531,18.0,2021,R128,roland garros - 2021,2
73796,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20210531,18.0,2021,R64,roland garros - 2021,2
73797,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20210628,18.1,2021,R128,wimbledon - 2021,3
73798,207989,Carlos Alcaraz,ESP,R,183.0,us open,20210830,18.3,2021,R128,us open - 2021,4
73799,207989,Carlos Alcaraz,ESP,R,183.0,us open,20210830,18.3,2021,R64,us open - 2021,4
73800,207989,Carlos Alcaraz,ESP,R,183.0,us open,20210830,18.3,2021,R32,us open - 2021,4
73801,207989,Carlos Alcaraz,ESP,R,183.0,us open,20210830,18.3,2021,R16,us open - 2021,4
73802,207989,Carlos Alcaraz,ESP,R,183.0,australian open,20210208,17.7,2021,R128,australian open - 2021,1
73816,207989,Carlos Alcaraz,ESP,R,183.0,australian open,20220117,18.7,2022,R128,australian open - 2022,1
73817,207989,Carlos Alcaraz,ESP,R,183.0,australian open,20220117,18.7,2022,R64,australian open - 2022,1
73843,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20220523,19.0,2022,R128,roland garros - 2022,2
73844,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20220523,19.0,2022,R64,roland garros - 2022,2
73845,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20220523,19.0,2022,R32,roland garros - 2022,2
73846,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20220523,19.0,2022,R16,roland garros - 2022,2
73847,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20220627,19.1,2022,R128,wimbledon - 2022,3
73848,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20220627,19.1,2022,R64,wimbledon - 2022,3
73849,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20220627,19.1,2022,R32,wimbledon - 2022,3
73859,207989,Carlos Alcaraz,ESP,R,183.0,us open,20220829,19.3,2022,R128,us open - 2022,4
73860,207989,Carlos Alcaraz,ESP,R,183.0,us open,20220829,19.3,2022,R64,us open - 2022,4
73861,207989,Carlos Alcaraz,ESP,R,183.0,us open,20220829,19.3,2022,R32,us open - 2022,4
73862,207989,Carlos Alcaraz,ESP,R,183.0,us open,20220829,19.3,2022,R16,us open - 2022,4
73863,207989,Carlos Alcaraz,ESP,R,183.0,us open,20220829,19.3,2022,QF,us open - 2022,4
73864,207989,Carlos Alcaraz,ESP,R,183.0,us open,20220829,19.3,2022,SF,us open - 2022,4
73865,207989,Carlos Alcaraz,ESP,R,183.0,us open,20220829,19.3,2022,F,us open - 2022,4
73903,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20230529,20.0,2023,R128,roland garros - 2023,2
73904,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20230529,20.0,2023,R64,roland garros - 2023,2
73905,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20230529,20.0,2023,R32,roland garros - 2023,2
73906,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20230529,20.0,2023,R16,roland garros - 2023,2
73907,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20230529,20.0,2023,QF,roland garros - 2023,2
73913,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20230703,20.1,2023,R128,wimbledon - 2023,3
73914,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20230703,20.1,2023,R64,wimbledon - 2023,3
73915,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20230703,20.1,2023,R32,wimbledon - 2023,3
73916,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20230703,20.1,2023,R16,wimbledon - 2023,3
73917,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20230703,20.1,2023,QF,wimbledon - 2023,3
73918,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20230703,20.1,2023,SF,wimbledon - 2023,3
73919,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20230703,20.1,2023,F,wimbledon - 2023,3
73926,207989,Carlos Alcaraz,ESP,R,183.0,us open,20230828,20.3,2023,R128,us open - 2023,4
73927,207989,Carlos Alcaraz,ESP,R,183.0,us open,20230828,20.3,2023,R64,us open - 2023,4
73928,207989,Carlos Alcaraz,ESP,R,183.0,us open,20230828,20.3,2023,R32,us open - 2023,4
73929,207989,Carlos Alcaraz,ESP,R,183.0,us open,20230828,20.3,2023,R16,us open - 2023,4
73930,207989,Carlos Alcaraz,ESP,R,183.0,us open,20230828,20.3,2023,QF,us open - 2023,4
73938,207989,Carlos Alcaraz,ESP,R,183.0,australian open,20240115,20.6,2024,R128,australian open - 2024,1
73939,207989,Carlos Alcaraz,ESP,R,183.0,australian open,20240115,20.6,2024,R64,australian open - 2024,1
73940,207989,Carlos Alcaraz,ESP,R,183.0,australian open,20240115,20.6,2024,R32,australian open - 2024,1
73941,207989,Carlos Alcaraz,ESP,R,183.0,australian open,20240115,20.6,2024,R16,australian open - 2024,1
73956,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20240527,21.0,2024,F,roland garros - 2024,2
73957,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20240527,21.0,2024,SF,roland garros - 2024,2
73958,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20240527,21.0,2024,QF,roland garros - 2024,2
73959,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20240527,21.0,2024,R16,roland garros - 2024,2
73960,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20240527,21.0,2024,R32,roland garros - 2024,2
73961,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20240527,21.0,2024,R64,roland garros - 2024,2
73962,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20240527,21.0,2024,R128,roland garros - 2024,2
73964,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20240701,21.1,2024,R128,wimbledon - 2024,3
73965,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20240701,21.1,2024,R64,wimbledon - 2024,3
73966,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20240701,21.1,2024,R32,wimbledon - 2024,3
73967,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20240701,21.1,2024,R16,wimbledon - 2024,3
73968,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20240701,21.1,2024,QF,wimbledon - 2024,3
73969,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20240701,21.1,2024,SF,wimbledon - 2024,3
73970,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20240701,21.1,2024,F,wimbledon - 2024,3
73976,207989,Carlos Alcaraz,ESP,R,183.0,us open,20240826,21.3,2024,R128,us open - 2024,4

In [16]:
df_players_ATP_cleaned.to_csv('df_players_ATP_cleaned.csv', index=False)

In [17]:
fil = pd.read_csv('df_players_ATP_cleaned.csv')

In [19]:
al = fil[fil['full_name'] == 'Carlos Alcaraz']
al

,player_id,full_name,ioc,hand,height,tourney_name,tourney_date,winner_age,year,round,tourney key,torneo_id
12394,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20210531,18.0,2021,R128,roland garros - 2021,2
12395,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20210531,18.0,2021,R64,roland garros - 2021,2
12396,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20210628,18.1,2021,R128,wimbledon - 2021,3
12397,207989,Carlos Alcaraz,ESP,R,183.0,us open,20210830,18.3,2021,R128,us open - 2021,4
12398,207989,Carlos Alcaraz,ESP,R,183.0,us open,20210830,18.3,2021,R64,us open - 2021,4
12399,207989,Carlos Alcaraz,ESP,R,183.0,us open,20210830,18.3,2021,R32,us open - 2021,4
12400,207989,Carlos Alcaraz,ESP,R,183.0,us open,20210830,18.3,2021,R16,us open - 2021,4
12401,207989,Carlos Alcaraz,ESP,R,183.0,australian open,20210208,17.7,2021,R128,australian open - 2021,1
12402,207989,Carlos Alcaraz,ESP,R,183.0,australian open,20220117,18.7,2022,R128,australian open - 2022,1
12403,207989,Carlos Alcaraz,ESP,R,183.0,australian open,20220117,18.7,2022,R64,australian open - 2022,1
12404,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20220523,19.0,2022,R128,roland garros - 2022,2
12405,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20220523,19.0,2022,R64,roland garros - 2022,2
12406,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20220523,19.0,2022,R32,roland garros - 2022,2
12407,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20220523,19.0,2022,R16,roland garros - 2022,2
12408,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20220627,19.1,2022,R128,wimbledon - 2022,3
12409,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20220627,19.1,2022,R64,wimbledon - 2022,3
12410,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20220627,19.1,2022,R32,wimbledon - 2022,3
12411,207989,Carlos Alcaraz,ESP,R,183.0,us open,20220829,19.3,2022,R128,us open - 2022,4
12412,207989,Carlos Alcaraz,ESP,R,183.0,us open,20220829,19.3,2022,R64,us open - 2022,4
12413,207989,Carlos Alcaraz,ESP,R,183.0,us open,20220829,19.3,2022,R32,us open - 2022,4
12414,207989,Carlos Alcaraz,ESP,R,183.0,us open,20220829,19.3,2022,R16,us open - 2022,4
12415,207989,Carlos Alcaraz,ESP,R,183.0,us open,20220829,19.3,2022,QF,us open - 2022,4
12416,207989,Carlos Alcaraz,ESP,R,183.0,us open,20220829,19.3,2022,SF,us open - 2022,4
12417,207989,Carlos Alcaraz,ESP,R,183.0,us open,20220829,19.3,2022,F,us open - 2022,4
12418,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20230529,20.0,2023,R128,roland garros - 2023,2
12419,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20230529,20.0,2023,R64,roland garros - 2023,2
12420,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20230529,20.0,2023,R32,roland garros - 2023,2
12421,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20230529,20.0,2023,R16,roland garros - 2023,2
12422,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20230529,20.0,2023,QF,roland garros - 2023,2
12423,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20230703,20.1,2023,R128,wimbledon - 2023,3
12424,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20230703,20.1,2023,R64,wimbledon - 2023,3
12425,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20230703,20.1,2023,R32,wimbledon - 2023,3
12426,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20230703,20.1,2023,R16,wimbledon - 2023,3
12427,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20230703,20.1,2023,QF,wimbledon - 2023,3
12428,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20230703,20.1,2023,SF,wimbledon - 2023,3
12429,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20230703,20.1,2023,F,wimbledon - 2023,3
12430,207989,Carlos Alcaraz,ESP,R,183.0,us open,20230828,20.3,2023,R128,us open - 2023,4
12431,207989,Carlos Alcaraz,ESP,R,183.0,us open,20230828,20.3,2023,R64,us open - 2023,4
12432,207989,Carlos Alcaraz,ESP,R,183.0,us open,20230828,20.3,2023,R32,us open - 2023,4
12433,207989,Carlos Alcaraz,ESP,R,183.0,us open,20230828,20.3,2023,R16,us open - 2023,4
12434,207989,Carlos Alcaraz,ESP,R,183.0,us open,20230828,20.3,2023,QF,us open - 2023,4
12435,207989,Carlos Alcaraz,ESP,R,183.0,australian open,20240115,20.6,2024,R128,australian open - 2024,1
12436,207989,Carlos Alcaraz,ESP,R,183.0,australian open,20240115,20.6,2024,R64,australian open - 2024,1
12437,207989,Carlos Alcaraz,ESP,R,183.0,australian open,20240115,20.6,2024,R32,australian open - 2024,1
12438,207989,Carlos Alcaraz,ESP,R,183.0,australian open,20240115,20.6,2024,R16,australian open - 2024,1
12439,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20240527,21.0,2024,F,roland garros - 2024,2
12440,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20240527,21.0,2024,SF,roland garros - 2024,2
12441,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20240527,21.0,2024,QF,roland garros - 2024,2
12442,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20240527,21.0,2024,R16,roland garros - 2024,2
12443,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20240527,21.0,2024,R32,roland garros - 2024,2
12444,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20240527,21.0,2024,R64,roland garros - 2024,2
12445,207989,Carlos Alcaraz,ESP,R,183.0,roland garros,20240527,21.0,2024,R128,roland garros - 2024,2
12446,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20240701,21.1,2024,R128,wimbledon - 2024,3
12447,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20240701,21.1,2024,R64,wimbledon - 2024,3
12448,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20240701,21.1,2024,R32,wimbledon - 2024,3
12449,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20240701,21.1,2024,R16,wimbledon - 2024,3
12450,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20240701,21.1,2024,QF,wimbledon - 2024,3
12451,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20240701,21.1,2024,SF,wimbledon - 2024,3
12452,207989,Carlos Alcaraz,ESP,R,183.0,wimbledon,20240701,21.1,2024,F,wimbledon - 2024,3
12453,207989,Carlos Alcaraz,ESP,R,183.0,us open,20240826,21.3,2024,R128,us open - 2024,4