### <span style="color: rgb(230, 215, 0);"> Sprint 8 </span> <span style="color: rgb(230, 0, 126);"> Andrés Vidal Monge </span>
### <span style="color: rgb(230, 215, 0);"> Nivel 1</span>
### <span style="color: rgb(230, 0, 126);"> - Ejercicio 1</span> 
Importa como un DataFrame el archivo sprint10.xlsx. Asegúrate de que el archivo se importa correctamente, con los nombres de columnas que le corresponden, sin manipular el archivo original.
- Ordena el DataFrame por el país de origen. En caso de empate, ordena por el nombre de la ciudad.
- Muestra las primeras 10 filas.
<!-- - Adicionalmente, realiza un print donde compruebe que el DNI sólo tiene valores únicos. -->

### <span style="color: rgb(230, 215, 0);">___________________________________________________________________________________________________________________________</span>

In [89]:
import pandas as pd

# importar el archivo sin las primera 3 lineas para que lea bien las columnas 
df_trabajadores = pd.read_excel("sprint10.xlsx",skiprows=3,index_col=0)


# borrar columnas Unnamed
df_trabajadores = df_trabajadores.loc[:, ~df_trabajadores.columns.str.contains('^Unnamed')]

# limpiar columna salari mensual
df_trabajadores['Salari mensual'] = df_trabajadores['Salari mensual'].replace('[€,.]', '', regex=True).astype(float)

df_trabajadores.head(10).sort_values(by=["País d'origen",'Ciutat'])

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
1,Clara,Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1253.0,1.0,NaN,Grup A
4,Toni,Sánchez García,69630528M,Espanya,Barcelona,9,8,1999,H,1043.0,NaN,1.0,Grup A
9,Toni,Martínez,14219925Z,Espanya,Barcelona,16,5,1964,H,891.0,NaN,1.0,Grup A
5,Laia,Castells Ferrer,26930927E,Espanya,Madrid,16,12,1953,A,2611.0,NaN,1.0,Grup D
6,Carla,García,78247593G,Espanya,València,24,12,1957,D,942.0,NaN,1.0,Grup A
8,Alessia,Rossi,87316866D,Itàlia,Milà,6,12,1989,D,1366.0,NaN,1.0,Grup A
7,Marco,Rossi,21774231J,Itàlia,Torí,3,11,2002,A,1494.0,NaN,1.0,Grup A
2,Fatima,Fassi,38141675A,Marroc,Rabat,6,11,2005,A,1441.0,1.0,NaN,Grup A
3,Khadija,Bennani Bennani,59157262R,Marroc,Rabat,20,1,1995,D,1944.0,NaN,1.0,Grup B
0,Inês,Ferreira Silva,16928694K,Portugal,Lisboa,25,2,1953,D,1144.0,NaN,1.0,Grup B

- Adicionalmente un print donde compruebe que el DNI sólo tiene valores únicos.

In [90]:
df_trabajadores['DNI'].nunique()

1000

### <span style="color: rgb(230, 0, 126);">___________________________________________________________________________________________________________________________</span>

### <span style="color: rgb(230, 0, 126);"> - Ejercicio 2</span> 
<!-- - Crea una columna que sea el nombre completo -->
<!-- - Crea una columna si la persona ha nacido en España o no -->
<!-- - Pone el DNI como índice del DataFrame (nombres de filas) -->
<!-- - Sustituye el nombre de las columnas Día de Nacimiento, Mes de Nacimiento y Año de Nacimiento por Día, Mes y Año -->
<!-- - Sustituye a H por Hombre, D por Mujer, A por Otros y NC por un dato faltante (enano/null/na) -->

### <span style="color: rgb(230, 215, 0);">___________________________________________________________________________________________________________________________</span>

- Crea una columna que sea el nombre completo

In [91]:
df_trabajadores['Nom i Cognoms'] = df_trabajadores['Nom'] + ' ' + df_trabajadores['Cognoms']
df_trabajadores

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom i Cognoms
0,Inês,Ferreira Silva,16928694K,Portugal,Lisboa,25,2,1953,D,1144.0,NaN,1.0,Grup B,Inês Ferreira Silva
1,Clara,Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1253.0,1.0,NaN,Grup A,Clara Sánchez Martínez
2,Fatima,Fassi,38141675A,Marroc,Rabat,6,11,2005,A,1441.0,1.0,NaN,Grup A,Fatima Fassi
3,Khadija,Bennani Bennani,59157262R,Marroc,Rabat,20,1,1995,D,1944.0,NaN,1.0,Grup B,Khadija Bennani Bennani
4,Toni,Sánchez García,69630528M,Espanya,Barcelona,9,8,1999,H,1043.0,NaN,1.0,Grup A,Toni Sánchez García
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Marta,Ferrer Ferrer,25161375F,Espanya,Sevilla,1,6,1951,D,1216.0,NaN,1.0,Grup B,Marta Ferrer Ferrer
996,Joan,García,52145541P,Espanya,Sevilla,11,4,1959,H,971.0,NaN,1.0,Grup A,Joan García
997,Laia,Ferrer Martínez,69760120X,Espanya,Barcelona,11,11,1980,D,682.0,NaN,1.0,Grup A,Laia Ferrer Martínez
998,Jordi,García,82947791W,Espanya,Barcelona,23,5,1984,H,1699.0,1.0,NaN,Grup C,Jordi García
999,Clara,Sánchez López,89253307W,Espanya,Bilbao,1,8,1952,D,1217.0,NaN,1.0,Grup A,Clara Sánchez López

- Crea una columna si la persona ha nacido en España o no

In [92]:
data_trabajadores_new = df_trabajadores.reset_index()

data_trabajadores_new = data_trabajadores_new.rename(columns={"País d'origen": 'Pais'})
data_trabajadores_new['Español'] = data_trabajadores_new['Pais'] == 'Espanya'
data_trabajadores_new

,index,Nom,Cognoms,DNI,Pais,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom i Cognoms,Español
0,0,Inês,Ferreira Silva,16928694K,Portugal,Lisboa,25,2,1953,D,1144.0,NaN,1.0,Grup B,Inês Ferreira Silva,False
1,1,Clara,Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1253.0,1.0,NaN,Grup A,Clara Sánchez Martínez,True
2,2,Fatima,Fassi,38141675A,Marroc,Rabat,6,11,2005,A,1441.0,1.0,NaN,Grup A,Fatima Fassi,False
3,3,Khadija,Bennani Bennani,59157262R,Marroc,Rabat,20,1,1995,D,1944.0,NaN,1.0,Grup B,Khadija Bennani Bennani,False
4,4,Toni,Sánchez García,69630528M,Espanya,Barcelona,9,8,1999,H,1043.0,NaN,1.0,Grup A,Toni Sánchez García,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,Marta,Ferrer Ferrer,25161375F,Espanya,Sevilla,1,6,1951,D,1216.0,NaN,1.0,Grup B,Marta Ferrer Ferrer,True
996,996,Joan,García,52145541P,Espanya,Sevilla,11,4,1959,H,971.0,NaN,1.0,Grup A,Joan García,True
997,997,Laia,Ferrer Martínez,69760120X,Espanya,Barcelona,11,11,1980,D,682.0,NaN,1.0,Grup A,Laia Ferrer Martínez,True
998,998,Jordi,García,82947791W,Espanya,Barcelona,23,5,1984,H,1699.0,1.0,NaN,Grup C,Jordi García,True
999,999,Clara,Sánchez López,89253307W,Espanya,Bilbao,1,8,1952,D,1217.0,NaN,1.0,Grup A,Clara Sánchez López,True

- Pone el DNI como índice del DataFrame (nombres de filas)

In [93]:
df_trabajadores_index = data_trabajadores_new.set_index('DNI')
df_trabajadores_index

,index,Nom,Cognoms,Pais,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom i Cognoms,Español
DNI,,,,,,,,,,,,,,,
16928694K,0,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,D,1144.0,NaN,1.0,Grup B,Inês Ferreira Silva,False
27724652S,1,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,D,1253.0,1.0,NaN,Grup A,Clara Sánchez Martínez,True
38141675A,2,Fatima,Fassi,Marroc,Rabat,6,11,2005,A,1441.0,1.0,NaN,Grup A,Fatima Fassi,False
59157262R,3,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,D,1944.0,NaN,1.0,Grup B,Khadija Bennani Bennani,False
69630528M,4,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,H,1043.0,NaN,1.0,Grup A,Toni Sánchez García,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,995,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,D,1216.0,NaN,1.0,Grup B,Marta Ferrer Ferrer,True
52145541P,996,Joan,García,Espanya,Sevilla,11,4,1959,H,971.0,NaN,1.0,Grup A,Joan García,True
69760120X,997,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,D,682.0,NaN,1.0,Grup A,Laia Ferrer Martínez,True
82947791W,998,Jordi,García,Espanya,Barcelona,23,5,1984,H,1699.0,1.0,NaN,Grup C,Jordi García,True
89253307W,999,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,D,1217.0,NaN,1.0,Grup A,Clara Sánchez López,True

- Sustituye el nombre de las columnas Día de Nacimiento, Mes de Nacimiento y Año de Nacimiento por Día, Mes y Año

In [94]:
df_trabajadores_index = df_trabajadores_index.rename(columns={'Dia de Naixement':'Dia', 'Mes de Naixement': 'Mes', 'Any de Naixement' : 'Any'})
df_trabajadores_index

,index,Nom,Cognoms,Pais,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom i Cognoms,Español
DNI,,,,,,,,,,,,,,,
16928694K,0,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,D,1144.0,NaN,1.0,Grup B,Inês Ferreira Silva,False
27724652S,1,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,D,1253.0,1.0,NaN,Grup A,Clara Sánchez Martínez,True
38141675A,2,Fatima,Fassi,Marroc,Rabat,6,11,2005,A,1441.0,1.0,NaN,Grup A,Fatima Fassi,False
59157262R,3,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,D,1944.0,NaN,1.0,Grup B,Khadija Bennani Bennani,False
69630528M,4,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,H,1043.0,NaN,1.0,Grup A,Toni Sánchez García,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,995,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,D,1216.0,NaN,1.0,Grup B,Marta Ferrer Ferrer,True
52145541P,996,Joan,García,Espanya,Sevilla,11,4,1959,H,971.0,NaN,1.0,Grup A,Joan García,True
69760120X,997,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,D,682.0,NaN,1.0,Grup A,Laia Ferrer Martínez,True
82947791W,998,Jordi,García,Espanya,Barcelona,23,5,1984,H,1699.0,1.0,NaN,Grup C,Jordi García,True
89253307W,999,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,D,1217.0,NaN,1.0,Grup A,Clara Sánchez López,True

- Sustituye a H por Hombre, D por Mujer, A por Otros y NC por un dato faltante (enano/null/na)

In [95]:
# data_trabajadores_replace = data_trabajadores_index
df_trabajadores_index['Gènere'].replace({'H':'Hombre', 'D':'Mujer', 'A':'Otros', 'NC':'Null'}, inplace=True)
df_trabajadores_index

C:\Users\Usuario\AppData\Local\Temp\ipykernel_12420\531692796.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_trabajadores_index['Gènere'].replace({'H':'Hombre', 'D':'Mujer', 'A':'Otros', 'NC':'Null'}, inplace=True)

,index,Nom,Cognoms,Pais,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom i Cognoms,Español
DNI,,,,,,,,,,,,,,,
16928694K,0,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Mujer,1144.0,NaN,1.0,Grup B,Inês Ferreira Silva,False
27724652S,1,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Mujer,1253.0,1.0,NaN,Grup A,Clara Sánchez Martínez,True
38141675A,2,Fatima,Fassi,Marroc,Rabat,6,11,2005,Otros,1441.0,1.0,NaN,Grup A,Fatima Fassi,False
59157262R,3,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Mujer,1944.0,NaN,1.0,Grup B,Khadija Bennani Bennani,False
69630528M,4,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Hombre,1043.0,NaN,1.0,Grup A,Toni Sánchez García,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,995,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,Mujer,1216.0,NaN,1.0,Grup B,Marta Ferrer Ferrer,True
52145541P,996,Joan,García,Espanya,Sevilla,11,4,1959,Hombre,971.0,NaN,1.0,Grup A,Joan García,True
69760120X,997,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,Mujer,682.0,NaN,1.0,Grup A,Laia Ferrer Martínez,True
82947791W,998,Jordi,García,Espanya,Barcelona,23,5,1984,Hombre,1699.0,1.0,NaN,Grup C,Jordi García,True
89253307W,999,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,Mujer,1217.0,NaN,1.0,Grup A,Clara Sánchez López,True

Mostra tots els canvis que has realitzat en una sola taula.

In [96]:
df_trabajadores_index[['Nom i Cognoms','Pais','Dia','Mes','Any','Gènere']]

                     Nom i Cognoms      Pais  Dia  Mes   Any  Gènere
DNI
16928694K      Inês Ferreira Silva  Portugal   25    2  1953   Mujer
27724652S   Clara Sánchez Martínez   Espanya   18    3  1996   Mujer
38141675A             Fatima Fassi    Marroc    6   11  2005   Otros
59157262R  Khadija Bennani Bennani    Marroc   20    1  1995   Mujer
69630528M      Toni Sánchez García   Espanya    9    8  1999  Hombre
...                            ...       ...  ...  ...   ...     ...
25161375F      Marta Ferrer Ferrer   Espanya    1    6  1951   Mujer
52145541P              Joan García   Espanya   11    4  1959  Hombre
69760120X     Laia Ferrer Martínez   Espanya   11   11  1980   Mujer
82947791W             Jordi García   Espanya   23    5  1984  Hombre
89253307W      Clara Sánchez López   Espanya    1    8  1952   Mujer

[1000 rows x 6 columns]

### <span style="color: rgb(230, 0, 126);">___________________________________________________________________________________________________________________________</span>

### <span style="color: rgb(230, 0, 126);"> - Ejercicio 3</span>
Junta las columnas Hijos y No Hijos en una sola columna, utilizando el método .apply() y definiendo una función que resuelva el problema. La columna nueva debe llamarse "Hijos" y tomar los valores "Sí" o "No"

### <span style="color: rgb(230, 215, 0);">___________________________________________________________________________________________________________________________</span>

In [97]:
df_trabajadores_index['Hijos'] = df_trabajadores_index['Fills'].apply(lambda x: 'Sí' if x == 1 else 'No')
df_trabajadores_index
# df['mayor_de_edad'] = df['edad'].apply(lambda x: 'Sí' if x >= 18 else 'No')

,index,Nom,Cognoms,Pais,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom i Cognoms,Español,Hijos
DNI,,,,,,,,,,,,,,,,
16928694K,0,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Mujer,1144.0,NaN,1.0,Grup B,Inês Ferreira Silva,False,No
27724652S,1,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Mujer,1253.0,1.0,NaN,Grup A,Clara Sánchez Martínez,True,Sí
38141675A,2,Fatima,Fassi,Marroc,Rabat,6,11,2005,Otros,1441.0,1.0,NaN,Grup A,Fatima Fassi,False,Sí
59157262R,3,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Mujer,1944.0,NaN,1.0,Grup B,Khadija Bennani Bennani,False,No
69630528M,4,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Hombre,1043.0,NaN,1.0,Grup A,Toni Sánchez García,True,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,995,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,Mujer,1216.0,NaN,1.0,Grup B,Marta Ferrer Ferrer,True,No
52145541P,996,Joan,García,Espanya,Sevilla,11,4,1959,Hombre,971.0,NaN,1.0,Grup A,Joan García,True,No
69760120X,997,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,Mujer,682.0,NaN,1.0,Grup A,Laia Ferrer Martínez,True,No
82947791W,998,Jordi,García,Espanya,Barcelona,23,5,1984,Hombre,1699.0,1.0,NaN,Grup C,Jordi García,True,Sí
89253307W,999,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,Mujer,1217.0,NaN,1.0,Grup A,Clara Sánchez López,True,No

### <span style="color: rgb(230, 0, 126);">___________________________________________________________________________________________________________________________</span>

### <span style="color: rgb(230, 0, 126);"> - Ejercicio 4</span>
Crea una tabla resumen que permita ver el sueldo medio, medio, mínimo y máximo por Género.
Ordena la tabla en función del sueldo medio.

### <span style="color: rgb(230, 215, 0);">___________________________________________________________________________________________________________________________</span>

In [98]:
df_trabajadores_index.groupby('Gènere')[['Salari mensual']].agg({'Salari mensual':['mean','median','min','max']})

       Salari mensual
                 mean  median    min     max
Gènere
Hombre    1643.249443  1531.0  737.0  3356.0
Mujer     1469.443182  1361.5  665.0  3021.0
Null      1568.866667  1443.0  758.0  2969.0
Otros     1626.588235  1545.0  703.0  3175.0

### <span style="color: rgb(230, 0, 126);">___________________________________________________________________________________________________________________________</span>

### <span style="color: rgb(230, 0, 126);"> - Ejercicio 5</span>
Crea una tabla resumen con el salario medio por género (filas) y país de origen (columnas).
Añade las medias a los márgenes de la mesa.

(EXTRA): Aplica formato condicional en la tabla para ver en un color más intenso los valores más elevados

### <span style="color: rgb(230, 215, 0);">___________________________________________________________________________________________________________________________</span>

In [99]:
group_Pais = df_trabajadores_index.groupby(['Gènere','Pais'])[['Salari mensual']].mean().unstack().style.background_gradient(cmap='cividis')
group_Pais

### <span style="color: rgb(230, 0, 126);">___________________________________________________________________________________________________________________________</span>

### <span style="color: rgb(230, 0, 126);"> - Ejercicio 6</span>
Crea una nueva columna que sea la fecha de nacimiento en formato Datetime a partir de las columnas día, mes y año Utilizando esta columna crea una función que dada una fecha, te calcule la edad actual a día de hoy.
Utiliza la función que acabas de crear para generar una columna nueva en DataFrame con la edad actual.

### <span style="color: rgb(230, 215, 0);">___________________________________________________________________________________________________________________________</span>

In [100]:
datos_fecha = df_trabajadores_index[['Dia','Mes','Any']]
datos_fecha = datos_fecha.rename(columns={'Dia':'day','Mes':'month','Any':'year'})
df_trabajadores_index['Fecha Nacimiento'] = pd.to_datetime(datos_fecha)
df_trabajadores_index

,index,Nom,Cognoms,Pais,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom i Cognoms,Español,Hijos,Fecha Nacimiento
DNI,,,,,,,,,,,,,,,,,
16928694K,0,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Mujer,1144.0,NaN,1.0,Grup B,Inês Ferreira Silva,False,No,1953-02-25
27724652S,1,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Mujer,1253.0,1.0,NaN,Grup A,Clara Sánchez Martínez,True,Sí,1996-03-18
38141675A,2,Fatima,Fassi,Marroc,Rabat,6,11,2005,Otros,1441.0,1.0,NaN,Grup A,Fatima Fassi,False,Sí,2005-11-06
59157262R,3,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Mujer,1944.0,NaN,1.0,Grup B,Khadija Bennani Bennani,False,No,1995-01-20
69630528M,4,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Hombre,1043.0,NaN,1.0,Grup A,Toni Sánchez García,True,No,1999-08-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,995,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,Mujer,1216.0,NaN,1.0,Grup B,Marta Ferrer Ferrer,True,No,1951-06-01
52145541P,996,Joan,García,Espanya,Sevilla,11,4,1959,Hombre,971.0,NaN,1.0,Grup A,Joan García,True,No,1959-04-11
69760120X,997,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,Mujer,682.0,NaN,1.0,Grup A,Laia Ferrer Martínez,True,No,1980-11-11
82947791W,998,Jordi,García,Espanya,Barcelona,23,5,1984,Hombre,1699.0,1.0,NaN,Grup C,Jordi García,True,Sí,1984-05-23
89253307W,999,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,Mujer,1217.0,NaN,1.0,Grup A,Clara Sánchez López,True,No,1952-08-01

In [101]:
print(datos_fecha.columns)

Index(['day', 'month', 'year'], dtype='object')

In [102]:
hoy = pd.to_datetime('today')
df_trabajadores_index['Edad Actual'] = df_trabajadores_index['Fecha Nacimiento'].apply(lambda fecha: hoy.year - fecha.year - ((hoy.month, hoy.day) < (fecha.month, fecha.day)))
df_trabajadores_index

,index,Nom,Cognoms,Pais,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom i Cognoms,Español,Hijos,Fecha Nacimiento,Edad Actual
DNI,,,,,,,,,,,,,,,,,,
16928694K,0,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Mujer,1144.0,NaN,1.0,Grup B,Inês Ferreira Silva,False,No,1953-02-25,72
27724652S,1,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Mujer,1253.0,1.0,NaN,Grup A,Clara Sánchez Martínez,True,Sí,1996-03-18,29
38141675A,2,Fatima,Fassi,Marroc,Rabat,6,11,2005,Otros,1441.0,1.0,NaN,Grup A,Fatima Fassi,False,Sí,2005-11-06,19
59157262R,3,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Mujer,1944.0,NaN,1.0,Grup B,Khadija Bennani Bennani,False,No,1995-01-20,30
69630528M,4,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Hombre,1043.0,NaN,1.0,Grup A,Toni Sánchez García,True,No,1999-08-09,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,995,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,Mujer,1216.0,NaN,1.0,Grup B,Marta Ferrer Ferrer,True,No,1951-06-01,74
52145541P,996,Joan,García,Espanya,Sevilla,11,4,1959,Hombre,971.0,NaN,1.0,Grup A,Joan García,True,No,1959-04-11,66
69760120X,997,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,Mujer,682.0,NaN,1.0,Grup A,Laia Ferrer Martínez,True,No,1980-11-11,44
82947791W,998,Jordi,García,Espanya,Barcelona,23,5,1984,Hombre,1699.0,1.0,NaN,Grup C,Jordi García,True,Sí,1984-05-23,41
89253307W,999,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,Mujer,1217.0,NaN,1.0,Grup A,Clara Sánchez López,True,No,1952-08-01,72

### <span style="color: rgb(230, 0, 126);">___________________________________________________________________________________________________________________________</span>

### <span style="color: rgb(230, 215, 0);"> Nivel 2</span>

<!-- Exercici 1
Utilitzant el següent DataFrame, adjunta la columna "Increment" al dataframe del nivell anterior.
Actualitza la columna salari en funció dels percentatges que s'adjunten. No modifiquis manualment els increments, escriu codi Python per fer les conversions necessàries.
df_increment = pd.DataFrame({"Grup":["Grup A","Grup B","Grup C", "Grup D" ] ,  "Increment": ["5%","3,5%","2%","8%"]}) -->
### <span style="color: rgb(230, 0, 126);"> - Ejercicio 1</span>
Utilizando el siguiente DataFrame, adjunta la columna "Incremento" al dataframe del nivel anterior.
Actualiza la columna salario en función de los porcentajes que se adjuntan. No modifiques manualmente los incrementos, escribe código Python para realizar las conversiones necesarias.

### <span style="color: rgb(230, 215, 0);">___________________________________________________________________________________________________________________________</span>

In [103]:
df_increment = pd.DataFrame({"Grup":["Grup A","Grup B","Grup C", "Grup D" ] ,  "Increment": ["5%","3,5%","2%","8%"]})

In [104]:
df_trabajadores_incremento = df_trabajadores_index.merge(df_increment, left_on='Grup Professional', right_on='Grup')
df_trabajadores_incremento

,index,Nom,Cognoms,Pais,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom i Cognoms,Español,Hijos,Fecha Nacimiento,Edad Actual,Grup,Increment
0,0,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Mujer,1144.0,NaN,1.0,Grup B,Inês Ferreira Silva,False,No,1953-02-25,72,Grup B,"3,5%"
1,1,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Mujer,1253.0,1.0,NaN,Grup A,Clara Sánchez Martínez,True,Sí,1996-03-18,29,Grup A,5%
2,2,Fatima,Fassi,Marroc,Rabat,6,11,2005,Otros,1441.0,1.0,NaN,Grup A,Fatima Fassi,False,Sí,2005-11-06,19,Grup A,5%
3,3,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Mujer,1944.0,NaN,1.0,Grup B,Khadija Bennani Bennani,False,No,1995-01-20,30,Grup B,"3,5%"
4,4,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Hombre,1043.0,NaN,1.0,Grup A,Toni Sánchez García,True,No,1999-08-09,25,Grup A,5%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,Mujer,1216.0,NaN,1.0,Grup B,Marta Ferrer Ferrer,True,No,1951-06-01,74,Grup B,"3,5%"
996,996,Joan,García,Espanya,Sevilla,11,4,1959,Hombre,971.0,NaN,1.0,Grup A,Joan García,True,No,1959-04-11,66,Grup A,5%
997,997,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,Mujer,682.0,NaN,1.0,Grup A,Laia Ferrer Martínez,True,No,1980-11-11,44,Grup A,5%
998,998,Jordi,García,Espanya,Barcelona,23,5,1984,Hombre,1699.0,1.0,NaN,Grup C,Jordi García,True,Sí,1984-05-23,41,Grup C,2%
999,999,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,Mujer,1217.0,NaN,1.0,Grup A,Clara Sánchez López,True,No,1952-08-01,72,Grup A,5%

In [105]:
# limpiar el simbolo de porcentaje
df_trabajadores_incremento['Increment'] = df_trabajadores_incremento['Increment'].replace('[%,.]', '', regex=True).astype(float).round(2) / 100

In [106]:
df_trabajadores_incremento['Salari mensual'] = (df_trabajadores_incremento['Salari mensual'] * (1 + df_trabajadores_incremento['Increment'])).round(2)
df_trabajadores_incremento

,index,Nom,Cognoms,Pais,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom i Cognoms,Español,Hijos,Fecha Nacimiento,Edad Actual,Grup,Increment
0,0,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Mujer,1544.40,NaN,1.0,Grup B,Inês Ferreira Silva,False,No,1953-02-25,72,Grup B,0.35
1,1,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Mujer,1315.65,1.0,NaN,Grup A,Clara Sánchez Martínez,True,Sí,1996-03-18,29,Grup A,0.05
2,2,Fatima,Fassi,Marroc,Rabat,6,11,2005,Otros,1513.05,1.0,NaN,Grup A,Fatima Fassi,False,Sí,2005-11-06,19,Grup A,0.05
3,3,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Mujer,2624.40,NaN,1.0,Grup B,Khadija Bennani Bennani,False,No,1995-01-20,30,Grup B,0.35
4,4,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Hombre,1095.15,NaN,1.0,Grup A,Toni Sánchez García,True,No,1999-08-09,25,Grup A,0.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,Mujer,1641.60,NaN,1.0,Grup B,Marta Ferrer Ferrer,True,No,1951-06-01,74,Grup B,0.35
996,996,Joan,García,Espanya,Sevilla,11,4,1959,Hombre,1019.55,NaN,1.0,Grup A,Joan García,True,No,1959-04-11,66,Grup A,0.05
997,997,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,Mujer,716.10,NaN,1.0,Grup A,Laia Ferrer Martínez,True,No,1980-11-11,44,Grup A,0.05
998,998,Jordi,García,Espanya,Barcelona,23,5,1984,Hombre,1732.98,1.0,NaN,Grup C,Jordi García,True,Sí,1984-05-23,41,Grup C,0.02
999,999,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,Mujer,1277.85,NaN,1.0,Grup A,Clara Sánchez López,True,No,1952-08-01,72,Grup A,0.05

### <span style="color: rgb(230, 0, 126);">___________________________________________________________________________________________________________________________</span>

### <span style="color: rgb(230, 0, 126);"> - Ejercicio 2</span>
<!-- Utilitzant un bucle, exporta en 4 fitxers (format .xlsx o .csv) les dades de cada Grup Professional.
Per exemple: "dades_GrupA.xlsx" , "dades_GrupB.xlsx" ...
Exporta un 5è DataFrame en format .xlsx o .csv que contingui quants treballadors hi ha per cada Grup Professional, quin és el seu sou mig i quina és la seva edat mediana.
(Extra: Explora com fer-ho tot en un sol excel, on hi hagi una pestanya per cada dataframe) -->
Utilizando un bucle, exporta en 4 archivos (formato .xlsx o .csv) los datos de cada Grupo Profesional.
Por ejemplo: "datos_GrupA.xlsx" , "datos_GrupB.xlsx" ...
Exporta un 5º DataFrame en formato .xlsx o .csv que contenga cuántos trabajadores hay por cada Grupo Profesional, cuál es su sueldo medio y cuál es su edad media.
>(Extra: Explora cómo hacerlo todo en un solo excel, donde haya una pestaña por cada dataframe)

In [114]:
df_trabajadores_incremento['Grup Professional'].unique()

array(['Grup B', 'Grup A', 'Grup D', 'Grup C'], dtype=object)

In [123]:
df_grup_A = df_trabajadores_incremento.loc[df_trabajadores_incremento['Grup Professional'] == 'Grup A']	
df_grup_B = df_trabajadores_incremento.loc[df_trabajadores_incremento['Grup Professional'] == 'Grup B']
df_grup_C = df_trabajadores_incremento.loc[df_trabajadores_incremento['Grup Professional'] == 'Grup C']
df_grup_D = df_trabajadores_incremento.loc[df_trabajadores_incremento['Grup Professional'] == 'Grup D']

In [124]:
df_grup_D

,index,Nom,Cognoms,Pais,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom i Cognoms,Español,Hijos,Fecha Nacimiento,Edad Actual,Grup,Increment
5,5,Laia,Castells Ferrer,Espanya,Madrid,16,12,1953,Otros,2819.88,NaN,1.0,Grup D,Laia Castells Ferrer,True,No,1953-12-16,71,Grup D,0.08
15,15,Marta,Romero,Espanya,Madrid,10,5,2001,Mujer,3034.80,1.0,NaN,Grup D,Marta Romero,True,Sí,2001-05-10,24,Grup D,0.08
22,22,Laia,Martínez Sánchez,Espanya,Madrid,14,6,1961,Mujer,2803.68,NaN,1.0,Grup D,Laia Martínez Sánchez,True,No,1961-06-14,63,Grup D,0.08
25,25,Clara,Ferrer,Espanya,Madrid,17,7,1990,Mujer,2893.32,NaN,1.0,Grup D,Clara Ferrer,True,No,1990-07-17,34,Grup D,0.08
68,68,Michel,Lefevre,França,París,21,8,1974,Hombre,2873.88,NaN,1.0,Grup D,Michel Lefevre,False,No,1974-08-21,50,Grup D,0.08
70,70,Marc,Martínez,Espanya,Sevilla,1,8,1977,Hombre,3283.20,NaN,1.0,Grup D,Marc Martínez,True,No,1977-08-01,47,Grup D,0.08
71,71,Lea,Schneider,Alemanya,Munic,22,9,1950,Mujer,2881.44,1.0,NaN,Grup D,Lea Schneider,False,Sí,1950-09-22,74,Grup D,0.08
80,80,Laia,Castells,Espanya,Bilbao,19,4,1950,Mujer,2643.84,NaN,1.0,Grup D,Laia Castells,True,No,1950-04-19,75,Grup D,0.08
87,87,Eva,Sánchez,Espanya,Madrid,9,9,1992,Mujer,3115.80,1.0,NaN,Grup D,Eva Sánchez,True,Sí,1992-09-09,32,Grup D,0.08
99,99,Carla,Martínez,Espanya,Madrid,21,3,1973,Mujer,3078.00,NaN,1.0,Grup D,Carla Martínez,True,No,1973-03-21,52,Grup D,0.08
115,115,Arnau,Sánchez García,Espanya,València,24,2,1978,Hombre,3545.64,NaN,1.0,Grup D,Arnau Sánchez García,True,No,1978-02-24,47,Grup D,0.08
147,147,Núria,Sánchez Castells,Espanya,Madrid,12,5,1981,Null,2961.36,NaN,1.0,Grup D,Núria Sánchez Castells,True,No,1981-05-12,44,Grup D,0.08
173,173,Carla,López Ferrer,Espanya,Sevilla,4,9,1962,Mujer,3089.88,NaN,1.0,Grup D,Carla López Ferrer,True,No,1962-09-04,62,Grup D,0.08
177,177,Amina,Bennani,Marroc,Casablanca,22,10,2004,Mujer,3183.84,1.0,NaN,Grup D,Amina Bennani,False,Sí,2004-10-22,20,Grup D,0.08
180,180,Jordi,Sánchez,Espanya,Barcelona,6,6,1981,Hombre,2976.48,NaN,1.0,Grup D,Jordi Sánchez,True,No,1981-06-06,44,Grup D,0.08
181,181,Pau,Martínez López,Espanya,Madrid,3,11,2000,Hombre,3007.80,1.0,NaN,Grup D,Pau Martínez López,True,Sí,2000-11-03,24,Grup D,0.08
220,220,Arnau,Castells Sánchez,Espanya,València,17,4,1998,Hombre,3014.28,NaN,1.0,Grup D,Arnau Castells Sánchez,True,No,1998-04-17,27,Grup D,0.08
238,238,Maria,Silva Oliveira,Portugal,Lisboa,4,9,1993,Null,3125.52,NaN,1.0,Grup D,Maria Silva Oliveira,False,No,1993-09-04,31,Grup D,0.08
254,254,Joan,Romero,Espanya,Barcelona,26,4,1969,Otros,3429.00,NaN,1.0,Grup D,Joan Romero,True,No,1969-04-26,56,Grup D,0.08
255,255,Arnau,Ferrer,Espanya,València,24,3,1990,Otros,2813.40,1.0,NaN,Grup D,Arnau Ferrer,True,Sí,1990-03-24,35,Grup D,0.08
259,259,María,Cruz,Mèxic,Ciutat de Mèxic,14,3,1958,Mujer,2865.24,1.0,NaN,Grup D,María Cruz,False,Sí,1958-03-14,67,Grup D,0.08
341,341,Eva,Castells Romero,Espanya,Bilbao,25,7,1988,Mujer,2627.64,1.0,NaN,Grup D,Eva Castells Romero,True,Sí,1988-07-25,36,Grup D,0.08
376,376,Marc,López,Espanya,Sevilla,8,2,1987,Null,3206.52,NaN,1.0,Grup D,Marc López,True,No,1987-02-08,38,Grup D,0.08
394,394,Joan,Martínez Sánchez,Espanya,València,18,2,1986,Hombre,3583.44,1.0,NaN,Grup D,Joan Martínez Sánchez,True,Sí,1986-02-18,39,Grup D,0.08
406,406,Laia,Ferrer,Espanya,Barcelona,21,12,1987,Mujer,3051.00,1.0,NaN,Grup D,Laia Ferrer,True,Sí,1987-12-21,37,Grup D,0.08
412,412,Laia,Sánchez López,Espanya,Bilbao,5,8,1972,Mujer,3201.12,NaN,1.0,Grup D,Laia Sánchez López,True,No,1972-08-05,52,Grup D,0.08
427,427,Clara,García Martínez,Espanya,Sevilla,2,9,1986,Mujer,2587.68,NaN,1.0,Grup D,Clara García Martínez,True,No,1986-09-02,38,Grup D,0.08
431,431,Marta,Castells,Espanya,Barcelona,2,10,2003,Mujer,2897.64,NaN,1.0,Grup D,Marta Castells,True,No,2003-10-02,21,Grup D,0.08
432,432,Florencia,Rodríguez Álvarez,Argentina,Còrdova,27,11,1999,Mujer,3255.12,NaN,1.0,Grup D,Florencia Rodríguez Álvarez,False,No,1999-11-27,25,Grup D,0.08
438,438,Laura,Schneider Müller,Alemanya,Munic,28,11,1990,Mujer,3000.24,NaN,1.0,Grup D,Laura Schneider Müller,False,No,1990-11-28,34,Grup D,0.08
448,448,Carla,Sánchez,Espanya,València,6,3,1957,Mujer,3187.08,1.0,NaN,Grup D,Carla Sánchez,True,Sí,1957-03-06,68,Grup D,0.08
451,451,Clara,López,Espanya,València,17,2,1951,Mujer,3150.36,1.0,NaN,Grup D,Clara López,True,Sí,1951-02-17,74,Grup D,0.08
470,470,Pau,García Romero,Espanya,Madrid,27,12,1983,Hombre,3046.68,NaN,1.0,Grup D,Pau García Romero,True,No,1983-12-27,41,Grup D,0.08
479,479,Arnau,Romero,Espanya,Bilbao,26,6,1951,Hombre,3595.32,1.0,NaN,Grup D,Arnau Romero,True,Sí,1951-06-26,73,Grup D,0.08
518,518,Joan,Martínez Romero,Espanya,Sevilla,4,7,1971,Hombre,3213.00,NaN,1.0,Grup D,Joan Martínez Romero,True,No,1971-07-04,53,Grup D,0.08
537,537,Clara,Romero,Espanya,València,4,1,1974,Mujer,3262.68,1.0,NaN,Grup D,Clara Romero,True,Sí,1974-01-04,51,Grup D,0.08
553,553,Arnau,López Martínez,Espanya,València,24,1,1970,Hombre,3513.24,1.0,NaN,Grup D,Arnau López Martínez,True,Sí,1970-01-24,55,Grup D,0.08
602,602,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Hombre,2974.32,1.0,NaN,Grup D,Jonas Schneider,False,Sí,1985-11-22,39,Grup D,0.08
639,639,Toni,López,Espanya,Sevilla,10,3,1989,Hombre,3112.56,NaN,1.0,Grup D,Toni López,True,No,1989-03-10,36,Grup D,0.08
650,650,Pau,Castells,Espanya,Bilbao,20,7,1953,Hombre,3188.16,NaN,1.0,Grup D,Pau Castells,True,No,1953-07-20,71,Grup D,0.08
687,687,Pau,García,Espanya,Madrid,11,3,1976,Null,3142.80,NaN,1.0,Grup D,Pau García,True,No,1976-03-11,49,Grup D,0.08
708,708,Eva,Ferrer Romero,Espanya,Barcelona,1,11,2005,Mujer,3130.92,NaN,1.0,Grup D,Eva Ferrer Romero,True,No,2005-11-01,19,Grup D,0.08
710,710,Michel,Girard Dubois,França,París,9,8,1970,Hombre,3210.84,NaN,1.0,Grup D,Michel Girard Dubois,False,No,1970-08-09,54,Grup D,0.08
725,725,Jordi,López,Espanya,Madrid,25,6,1995,Hombre,3518.64,NaN,1.0,Grup D,Jordi López,True,No,1995-06-25,29,Grup D,0.08
741,741,Clara,Sánchez,Espanya,Madrid,1,10,2002,Otros,3393.36,1.0,NaN,Grup D,Clara Sánchez,True,Sí,2002-10-01,22,Grup D,0.08
744,744,Laia,López Castells,Espanya,Madrid,13,8,1971,Null,2824.20,1.0,NaN,Grup D,Laia López Castells,True,Sí,1971-08-13,53,Grup D,0.08
749,749,Oriol,López Castells,Espanya,Madrid,14,4,1987,Hombre,3624.48,NaN,1.0,Grup D,Oriol López Castells,True,No,1987-04-14,38,Grup D,0.08
777,777,Leon,Schneider Schneider,Alemanya,Hamburg,16,10,1977,Hombre,3222.72,NaN,1.0,Grup D,Leon Schneider Schneider,False,No,1977-10-16,47,Grup D,0.08
784,784,Joan,Martínez Ferrer,Espanya,València,12,3,1964,Hombre,3137.40,NaN,1.0,Grup D,Joan Martínez Ferrer,True,No,1964-03-12,61,Grup D,0.08
832,832,Giovanni,Rossi Russo,Itàlia,Torí,10,12,2000,Hombre,3093.12,1.0,NaN,Grup D,Giovanni Rossi Russo,False,Sí,2000-12-10,24,Grup D,0.08
863,863,Oriol,Ferrer,Espanya,Madrid,12,3,1995,Hombre,3517.56,1.0,NaN,Grup D,Oriol Ferrer,True,Sí,1995-03-12,30,Grup D,0.08
873,873,Beatriz,Ferreira Pereira,Portugal,Lisboa,25,10,2004,Mujer,2566.08,1.0,NaN,Grup D,Beatriz Ferreira Pereira,False,Sí,2004-10-25,20,Grup D,0.08
879,879,Marta,López,Espanya,Madrid,9,7,2004,Mujer,2986.20,NaN,1.0,Grup D,Marta López,True,No,2004-07-09,20,Grup D,0.08
890,890,Clara,López Castells,Espanya,València,9,4,1982,Mujer,3242.16,NaN,1.0,Grup D,Clara López Castells,True,No,1982-04-09,43,Grup D,0.08
952,952,Anna,Sánchez Castells,Espanya,Sevilla,1,2,1960,Mujer,2840.40,NaN,1.0,Grup D,Anna Sánchez Castells,True,No,1960-02-01,65,Grup D,0.08